import type { ExpandedExamplePair, ExpandedStudyItem } from "./expanded-study-data";

export const ADDITIONAL_WORDS: ExpandedStudyItem[] = [
  { id: "w-211", level: "A1", term: "airport", japanese: "空港", category: "移動", label: "名詞", pronunciation: "/ˈerpɔːrt/", example: "The airport is near the city.", exampleJapanese: "空港は街の近くにあります。", note: "at the airport で「空港で」、go to the airport で「空港へ行く」。" },
  { id: "w-212", level: "A1", term: "bottle", japanese: "びん、ボトル", category: "日常", label: "名詞", pronunciation: "/ˈbɑːtəl/", example: "I need a bottle of water.", exampleJapanese: "私は水を1本必要です。", note: "a bottle of + 飲み物 の形で、容器に入った量を表せます。" },
  { id: "w-213", level: "A1", term: "calendar", japanese: "カレンダー、予定表", category: "時間", label: "名詞", pronunciation: "/ˈkælɪndər/", example: "Write the date on the calendar.", exampleJapanese: "カレンダーに日付を書いてください。", note: "予定を確認するカレンダーにも使います。" },
  { id: "w-214", level: "A1", term: "camera", japanese: "カメラ", category: "日常", label: "名詞", pronunciation: "/ˈkæmərə/", example: "My camera is in my bag.", exampleJapanese: "私のカメラはバッグの中にあります。", note: "take a photo with a camera で「カメラで写真を撮る」。" },
  { id: "w-215", level: "A1", term: "corner", japanese: "角、曲がり角", category: "移動", label: "名詞", pronunciation: "/ˈkɔːrnər/", example: "The bank is on the corner.", exampleJapanese: "銀行は角にあります。", note: "on the corner は通りの角にある場所を表します。" },
  { id: "w-216", level: "A1", term: "elevator", japanese: "エレベーター", category: "移動", label: "名詞", pronunciation: "/ˈelɪveɪtər/", example: "Take the elevator to the third floor.", exampleJapanese: "エレベーターで3階へ行ってください。", note: "イギリス英語では lift と言います。" },
  { id: "w-217", level: "A1", term: "entrance", japanese: "入口", category: "移動", label: "名詞", pronunciation: "/ˈentrəns/", example: "Meet me at the entrance.", exampleJapanese: "入口で私と会いましょう。", note: "exit は「出口」、entrance は「入口」です。" },
  { id: "w-218", level: "A1", term: "floor", japanese: "床、階", category: "家・生活", label: "名詞", pronunciation: "/flɔːr/", example: "Your room is on the second floor.", exampleJapanese: "あなたの部屋は2階にあります。", note: "建物の階を表すときにも使います。" },
  { id: "w-219", level: "A1", term: "hospital", japanese: "病院", category: "日常", label: "名詞", pronunciation: "/ˈhɑːspɪtəl/", example: "The hospital is open all day.", exampleJapanese: "その病院は一日中開いています。", note: "go to the hospital で「病院へ行く」。" },
  { id: "w-220", level: "A1", term: "map", japanese: "地図", category: "移動", label: "名詞", pronunciation: "/mæp/", example: "Can you show me the map?", exampleJapanese: "地図を見せてもらえますか。", note: "on a map で「地図上で」と表せます。" },
  { id: "w-221", level: "A2", term: "abroad", japanese: "海外へ、海外で", category: "移動", label: "副詞", pronunciation: "/əˈbrɔːd/", example: "I want to study abroad.", exampleJapanese: "私は海外で勉強したいです。", note: "go abroad / live abroad のように、通常は前置詞なしで使います。" },
  { id: "w-222", level: "A2", term: "luggage", japanese: "手荷物、旅行かばん", category: "旅行", label: "名詞", pronunciation: "/ˈlʌɡɪdʒ/", example: "Where can I leave my luggage?", exampleJapanese: "荷物はどこに預けられますか。", note: "luggage は通常数えない名詞です。a piece of luggage と数えます。" },
  { id: "w-223", level: "A2", term: "bridge", japanese: "橋", category: "移動", label: "名詞", pronunciation: "/brɪdʒ/", example: "Walk across the bridge.", exampleJapanese: "橋を渡ってください。", note: "across a bridge で「橋を横切って」。" },
  { id: "w-224", level: "A2", term: "distance", japanese: "距離", category: "移動", label: "名詞", pronunciation: "/ˈdɪstəns/", example: "The distance is about two kilometers.", exampleJapanese: "距離は約2キロメートルです。", note: "a long distance は「長い距離」を表します。" },
  { id: "w-225", level: "A2", term: "equipment", japanese: "設備、用具", category: "日常", label: "名詞", pronunciation: "/ɪˈkwɪpmənt/", example: "The gym has new equipment.", exampleJapanese: "そのジムには新しい設備があります。", note: "equipment は通常数えない名詞です。" },
  { id: "w-226", level: "A2", term: "guide", japanese: "案内する、ガイド", category: "旅行", label: "動詞/名詞", pronunciation: "/ɡaɪd/", example: "Our guide showed us the museum.", exampleJapanese: "ガイドが私たちに博物館を案内してくれました。", note: "名詞では案内人、動詞では案内する意味です。" },
  { id: "w-227", level: "A2", term: "journey", japanese: "旅、移動", category: "旅行", label: "名詞", pronunciation: "/ˈdʒɜːrni/", example: "The journey took three hours.", exampleJapanese: "その旅には3時間かかりました。", note: "journey は目的地までの移動そのものに注目する語です。" },
  { id: "w-228", level: "A2", term: "language", japanese: "言語", category: "学習", label: "名詞", pronunciation: "/ˈlæŋɡwɪdʒ/", example: "English is an international language.", exampleJapanese: "英語は国際的な言語です。", note: "a foreign language は「外国語」です。" },
  { id: "w-229", level: "A2", term: "passenger", japanese: "乗客", category: "旅行", label: "名詞", pronunciation: "/ˈpæsɪndʒər/", example: "All passengers must show a ticket.", exampleJapanese: "すべての乗客はチケットを見せなければなりません。", note: "bus passenger や airline passenger のように使います。" },
  { id: "w-230", level: "A2", term: "platform", japanese: "駅のホーム", category: "移動", label: "名詞", pronunciation: "/ˈplætfɔːrm/", example: "The train leaves from platform two.", exampleJapanese: "電車は2番ホームから出発します。", note: "駅で列車に乗る場所を表します。" },
  { id: "w-231", level: "B1", term: "attitude", japanese: "態度、考え方", category: "人間関係", label: "名詞", pronunciation: "/ˈætɪtuːd/", example: "Your attitude can affect the team.", exampleJapanese: "あなたの態度はチームに影響を与えることがあります。", note: "a positive attitude は「前向きな態度」です。" },
  { id: "w-232", level: "B1", term: "awareness", japanese: "認識、意識", category: "仕事・学習", label: "名詞", pronunciation: "/əˈwernəs/", example: "The campaign raised awareness of the problem.", exampleJapanese: "そのキャンペーンは問題への意識を高めました。", note: "awareness of + 問題・話題 の形で使います。" },
  { id: "w-233", level: "B1", term: "balance", japanese: "バランス、均衡", category: "日常", label: "名詞", pronunciation: "/ˈbæləns/", example: "It's important to keep a balance between work and rest.", exampleJapanese: "仕事と休息のバランスを保つことは大切です。", note: "balance between A and B で二つの間の均衡を表します。" },
  { id: "w-234", level: "B1", term: "behavior", japanese: "行動、ふるまい", category: "人間関係", label: "名詞", pronunciation: "/bɪˈheɪvjər/", example: "His behavior was polite.", exampleJapanese: "彼のふるまいは礼儀正しかったです。", note: "behavior は人の行動やふるまいを表す通常数えない名詞です。" },
  { id: "w-235", level: "B1", term: "budget", japanese: "予算", category: "仕事・学習", label: "名詞", pronunciation: "/ˈbʌdʒɪt/", example: "We need to stay within our budget.", exampleJapanese: "私たちは予算内に収める必要があります。", note: "within a budget で「予算の範囲内で」。" },
  { id: "w-236", level: "B1", term: "concern", japanese: "心配事、懸念", category: "仕事・学習", label: "名詞", pronunciation: "/kənˈsɜːrn/", example: "Safety is our main concern.", exampleJapanese: "安全が私たちの主な懸念です。", note: "concern about + 話題 で心配している内容を表せます。" },
  { id: "w-237", level: "B1", term: "confidence", japanese: "自信", category: "感情・状態", label: "名詞", pronunciation: "/ˈkɑːnfɪdəns/", example: "Practice builds confidence.", exampleJapanese: "練習は自信を育てます。", note: "confidence は confident の名詞形です。" },
  { id: "w-238", level: "B1", term: "evidence", japanese: "証拠、根拠", category: "仕事・学習", label: "名詞", pronunciation: "/ˈevɪdəns/", example: "There is no evidence of a problem.", exampleJapanese: "問題があるという証拠はありません。", note: "evidence は通常数えない名詞です。" },
  { id: "w-239", level: "B1", term: "impact", japanese: "影響、影響を与える", category: "仕事・学習", label: "名詞/動詞", pronunciation: "/ˈɪmpækt/", example: "The new rule had a big impact on our work.", exampleJapanese: "新しい規則は私たちの仕事に大きな影響を与えました。", note: "have an impact on + 名詞で「〜に影響を与える」。" },
  { id: "w-240", level: "B1", term: "outcome", japanese: "結果、成果", category: "仕事・学習", label: "名詞", pronunciation: "/ˈaʊtkʌm/", example: "We are waiting for the outcome of the meeting.", exampleJapanese: "私たちは会議の結果を待っています。", note: "outcome of + 出来事 で、その結果を表します。" }
];

export const ADDITIONAL_PHRASES: ExpandedStudyItem[] = [
  { id: "p-061", level: "A1", term: "How do you spell that?", japanese: "それはどうつづりますか。", category: "会話", label: "定型表現", example: "How do you spell that? - B-A-L-I.", exampleJapanese: "それはどうつづりますか。- B-A-L-Iです。", note: "名前や知らない単語のつづりをたずねる表現です。" },
  { id: "p-062", level: "A1", term: "Where are you from?", japanese: "どこの出身ですか。", category: "あいさつ", label: "定型表現", example: "Where are you from? - I'm from Indonesia.", exampleJapanese: "どこの出身ですか。- インドネシア出身です。", note: "出身地をたずねる初対面の基本表現です。" },
  { id: "p-063", level: "A1", term: "Can you speak slowly?", japanese: "ゆっくり話してもらえますか。", category: "会話", label: "定型表現", example: "Can you speak slowly, please?", exampleJapanese: "ゆっくり話してもらえますか。", note: "聞き取りにくいときに使える、丁寧で簡単な頼み方です。" },
  { id: "p-064", level: "A1", term: "This is my ...", japanese: "こちらは私の〜です。", category: "あいさつ", label: "定型表現", example: "This is my friend, Ana.", exampleJapanese: "こちらは私の友人のアナです。", note: "人を紹介するときに、This is my + 関係 を使います。" },
  { id: "p-065", level: "A1", term: "I need some help.", japanese: "助けが必要です。", category: "お願い", label: "定型表現", example: "I need some help with this form.", exampleJapanese: "この用紙について助けが必要です。", note: "with + 困っていること を続けると内容を伝えられます。" },
  { id: "p-066", level: "A1", term: "I'm hungry.", japanese: "おなかがすきました。", category: "食事", label: "定型表現", example: "I'm hungry. Let's have lunch.", exampleJapanese: "おなかがすきました。昼食にしましょう。", note: "hungry は「空腹の」、thirsty は「のどが渇いた」です。" },
  { id: "p-067", level: "A1", term: "Let's go.", japanese: "行きましょう。", category: "日常", label: "定型表現", example: "Let's go. The bus is here.", exampleJapanese: "行きましょう。バスが来ています。", note: "一緒に出発しようと促すカジュアルな表現です。" },
  { id: "p-068", level: "A1", term: "Excuse me.", japanese: "すみません。", category: "会話", label: "定型表現", example: "Excuse me, where is the station?", exampleJapanese: "すみません、駅はどこですか。", note: "人に話しかけるときや、軽く注意を引くときに使います。" },
  { id: "p-069", level: "A1", term: "Please wait a moment.", japanese: "少々お待ちください。", category: "会話", label: "定型表現", example: "Please wait a moment.", exampleJapanese: "少々お待ちください。", note: "相手に短い間待ってほしいときの丁寧な表現です。" },
  { id: "p-070", level: "A1", term: "Where is the restroom?", japanese: "トイレはどこですか。", category: "日常", label: "定型表現", example: "Where is the restroom?", exampleJapanese: "トイレはどこですか。", note: "restroom は主にアメリカ英語で公共のトイレを表します。" },
  { id: "p-071", level: "A2", term: "Could you repeat that?", japanese: "もう一度言っていただけますか。", category: "会話", label: "定型表現", example: "Sorry, could you repeat that?", exampleJapanese: "すみません、もう一度言っていただけますか。", note: "聞き取れなかった内容を、丁寧に聞き返す表現です。" },
  { id: "p-072", level: "A2", term: "I'm on my way.", japanese: "今向かっています。", category: "移動", label: "定型表現", example: "I'm on my way to the station.", exampleJapanese: "駅へ向かっています。", note: "約束の場所へ移動中だと伝える自然な表現です。" },
  { id: "p-073", level: "A2", term: "What should I do?", japanese: "私は何をすればよいですか。", category: "会話", label: "定型表現", example: "What should I do next?", exampleJapanese: "次に何をすればよいですか。", note: "助言や次の行動をたずねるときに使います。" },
  { id: "p-074", level: "A2", term: "I'd rather ...", japanese: "どちらかといえば〜したいです。", category: "会話", label: "定型表現", example: "I'd rather stay home tonight.", exampleJapanese: "今夜はどちらかといえば家にいたいです。", note: "I'd rather の後ろには動詞の原形を置きます。" },
  { id: "p-075", level: "A2", term: "I'm looking forward to ...", japanese: "〜を楽しみにしています。", category: "会話", label: "定型表現", example: "I'm looking forward to the trip.", exampleJapanese: "旅行を楽しみにしています。", note: "to の後ろには名詞か -ing 形を置きます。" },
  { id: "p-076", level: "A2", term: "Could you point me to ...?", japanese: "〜の場所を教えていただけますか。", category: "お願い", label: "定型表現", example: "Could you point me to the nearest bank?", exampleJapanese: "一番近い銀行の場所を教えていただけますか。", note: "point 人 to + 場所で、場所や方向を案内することを頼めます。" },
  { id: "p-077", level: "A2", term: "Is ... available?", japanese: "〜は利用できますか。", category: "買い物", label: "定型表現", example: "Is this room available tonight?", exampleJapanese: "この部屋は今夜利用できますか。", note: "席・部屋・商品などが利用できるかをたずねる表現です。" },
  { id: "p-078", level: "A2", term: "I'll think about it.", japanese: "考えておきます。", category: "会話", label: "定型表現", example: "That's an interesting idea. I'll think about it.", exampleJapanese: "面白い考えですね。考えておきます。", note: "すぐに決めず、検討したいと伝える表現です。" },
  { id: "p-079", level: "A2", term: "That works for me.", japanese: "それで大丈夫です。", category: "予定", label: "定型表現", example: "We can meet at six. - That works for me.", exampleJapanese: "6時に会えます。- それで大丈夫です。", note: "提案された予定や方法を受け入れる自然な返答です。" },
  { id: "p-080", level: "A2", term: "I've changed my mind.", japanese: "気が変わりました。", category: "会話", label: "定型表現", example: "I've changed my mind. Let's take the train.", exampleJapanese: "気が変わりました。電車にしましょう。", note: "前に決めていたことを変えるときに使います。" },
  { id: "p-081", level: "B1", term: "Would you be able to ...?", japanese: "〜していただくことは可能ですか。", category: "お願い", label: "定型表現", example: "Would you be able to send the file today?", exampleJapanese: "今日そのファイルを送っていただくことは可能ですか。", note: "Could you ...? より少し改まった依頼表現です。" },
  { id: "p-082", level: "B1", term: "I see what you mean.", japanese: "言いたいことが分かります。", category: "会話", label: "定型表現", example: "I see what you mean, but I have a different idea.", exampleJapanese: "言いたいことは分かりますが、私は別の考えがあります。", note: "相手の意図を理解したと示してから意見を述べられます。" },
  { id: "p-083", level: "B1", term: "That's a good point.", japanese: "それはもっともな点です。", category: "意見", label: "定型表現", example: "That's a good point. We should check the cost.", exampleJapanese: "それはもっともです。費用を確認すべきです。", note: "相手の意見の価値を認めるときに使います。" },
  { id: "p-084", level: "B1", term: "From my point of view, ...", japanese: "私の見方では、〜です。", category: "意見", label: "定型表現", example: "From my point of view, the plan is realistic.", exampleJapanese: "私の見方では、その計画は現実的です。", note: "自分の立場からの意見だと明確にする表現です。" },
  { id: "p-085", level: "B1", term: "I would prefer to ...", japanese: "できれば〜したいです。", category: "会話", label: "定型表現", example: "I would prefer to discuss this tomorrow.", exampleJapanese: "できればこれを明日話し合いたいです。", note: "would prefer to + 動詞で、丁寧に希望を伝えます。" },
  { id: "p-086", level: "B1", term: "It might be better to ...", japanese: "〜したほうがよいかもしれません。", category: "意見", label: "定型表現", example: "It might be better to leave earlier.", exampleJapanese: "もっと早く出発したほうがよいかもしれません。", note: "断定を避けて提案をするときに使います。" },
  { id: "p-087", level: "B1", term: "What I mean is ...", japanese: "私が言いたいのは、〜です。", category: "会話", label: "定型表現", example: "What I mean is that we need more time.", exampleJapanese: "私が言いたいのは、私たちにはもっと時間が必要だということです。", note: "誤解されそうなときに、自分の意図を言い換える表現です。" },
  { id: "p-088", level: "B1", term: "I'm responsible for ...", japanese: "私は〜を担当しています。", category: "仕事・学習", label: "定型表現", example: "I'm responsible for the weekly report.", exampleJapanese: "私は週報を担当しています。", note: "responsible for + 名詞・-ing で担当内容を表します。" },
  { id: "p-089", level: "B1", term: "I'd appreciate it if ...", japanese: "〜していただけるとありがたいです。", category: "お願い", label: "定型表現", example: "I'd appreciate it if you could reply today.", exampleJapanese: "今日返信していただけるとありがたいです。", note: "丁寧な依頼で、if の後ろには would / could をよく使います。" },
  { id: "p-090", level: "B1", term: "There is no need to ...", japanese: "〜する必要はありません。", category: "会話", label: "定型表現", example: "There is no need to hurry.", exampleJapanese: "急ぐ必要はありません。", note: "相手を安心させたり、不要な行動を伝えたりする表現です。" }
];

export const ADDITIONAL_GRAMMAR: ExpandedStudyItem[] = [
  { id: "g-061", level: "A1", term: "主格の代名詞", japanese: "主語になる代名詞", category: "基本文", label: "文法", pattern: "I / you / he / she / it / we / they", example: "They are my friends.", exampleJapanese: "彼らは私の友人です。", note: "主格の代名詞は、文の主語の位置に置きます。" },
  { id: "g-062", level: "A1", term: "形容詞 + 名詞", japanese: "名詞の前で特徴を表す", category: "名詞", label: "文法", pattern: "a small bag / a red dress", example: "This is a useful map.", exampleJapanese: "これは役に立つ地図です。", note: "英語では形容詞を通常、名詞の前に置きます。" },
  { id: "g-063", level: "A1", term: "Don't + 動詞", japanese: "〜しないで、と禁止を表す", category: "基本文", label: "文法", pattern: "Don't + 動詞の原形", example: "Don't open the door.", exampleJapanese: "ドアを開けないでください。", note: "否定の命令文では、文頭に Don't を置きます。" },
  { id: "g-064", level: "A1", term: "頻度を表す副詞", japanese: "どのくらいよくするかを表す", category: "時制", label: "文法", pattern: "always / usually / often / sometimes / never", example: "I usually walk to work.", exampleJapanese: "私は普段、歩いて仕事へ行きます。", note: "一般動詞の前、be動詞の後に置くのが基本です。" },
  { id: "g-065", level: "A1", term: "現在進行形の疑問文", japanese: "いま行っていることをたずねる", category: "時制", label: "文法", pattern: "Are / Is + 主語 + 動詞-ing?", example: "Are you waiting for someone?", exampleJapanese: "誰かを待っていますか。", note: "be動詞を主語の前に置いて疑問文にします。" },
  { id: "g-066", level: "A1", term: "have got", japanese: "持っていることを表す", category: "基本文", label: "文法", pattern: "have / has got + 名詞", example: "I've got a new phone.", exampleJapanese: "私は新しい携帯電話を持っています。", note: "特にイギリス英語の日常会話で have の代わりによく使います。" },
  { id: "g-067", level: "A1", term: "How many / How much", japanese: "数・量をたずねる", category: "疑問文", label: "文法", pattern: "How many + 複数名詞? / How much + 不可算名詞?", example: "How many tickets do we need?", exampleJapanese: "チケットは何枚必要ですか。", note: "数えられる名詞には many、数えられない名詞には much を使います。" },
  { id: "g-068", level: "A1", term: "Whose ...?", japanese: "誰のものかをたずねる", category: "疑問文", label: "文法", pattern: "Whose + 名詞 + be ...?", example: "Whose bag is this?", exampleJapanese: "これは誰のバッグですか。", note: "whose は所有者をたずねる疑問詞です。" },
  { id: "g-069", level: "A1", term: "三人称単数のつづり", japanese: "he / she / it の現在形の変化", category: "時制", label: "文法", pattern: "watch -> watches / study -> studies", example: "My father watches TV at night.", exampleJapanese: "父は夜にテレビを見ます。", note: "-s、-es、-ies の付け方を動詞ごとに確認します。" },
  { id: "g-070", level: "A1", term: "短い答え", japanese: "Yes / No で簡潔に答える", category: "会話", label: "文法", pattern: "Yes, I do. / No, she isn't.", example: "Do you like coffee? - Yes, I do.", exampleJapanese: "コーヒーは好きですか。- はい、好きです。", note: "質問に使われた助動詞や be動詞を繰り返して答えます。" },
  { id: "g-071", level: "A2", term: "would like", japanese: "丁寧に希望を伝える", category: "動詞の形", label: "文法", pattern: "would like + 名詞 / to + 動詞", example: "I'd like to book a room.", exampleJapanese: "部屋を予約したいです。", note: "would like は want より丁寧な言い方です。" },
  { id: "g-072", level: "A2", term: "a few / a little", japanese: "少しの量を表す", category: "名詞", label: "文法", pattern: "a few + 複数名詞 / a little + 不可算名詞", example: "We have a few questions.", exampleJapanese: "私たちにはいくつか質問があります。", note: "a few と a little は「少しはある」という前向きな意味です。" },
  { id: "g-073", level: "A2", term: "too + 形容詞 / 形容詞 + enough", japanese: "程度が強すぎる・十分であることを表す", category: "比較", label: "文法", pattern: "too heavy / warm enough", example: "This bag is too heavy.", exampleJapanese: "このバッグは重すぎます。", note: "too は「〜すぎる」、enough は「十分に」を表します。" },
  { id: "g-074", level: "A2", term: "each / every", japanese: "それぞれの、毎〜", category: "名詞", label: "文法", pattern: "each + 単数名詞 / every + 単数名詞", example: "Each student has a card.", exampleJapanese: "それぞれの生徒がカードを持っています。", note: "どちらの後ろにも通常は単数名詞を置きます。" },
  { id: "g-075", level: "A2", term: "one / ones", japanese: "同じ種類の物を指し直す", category: "名詞", label: "文法", pattern: "the blue one / the red ones", example: "I like the blue one.", exampleJapanese: "私は青いほうが好きです。", note: "one は単数、ones は複数の名詞の繰り返しを避けます。" },
  { id: "g-076", level: "A2", term: "過去進行形と過去形", japanese: "進行中の出来事に別の出来事が起きたことを表す", category: "時制", label: "文法", pattern: "was / were -ing when + 過去形", example: "I was cooking when you called.", exampleJapanese: "あなたが電話したとき、私は料理をしていました。", note: "長く続いていた動作は過去進行形、途中で起きたことは過去形を使います。" },
  { id: "g-077", level: "A2", term: "may / might", japanese: "可能性を表す", category: "助動詞", label: "文法", pattern: "may / might + 動詞の原形", example: "It may rain later.", exampleJapanese: "あとで雨が降るかもしれません。", note: "might は may より可能性が低い印象になることがあります。" },
  { id: "g-078", level: "A2", term: "must / mustn't", japanese: "強い必要・禁止を表す", category: "助動詞", label: "文法", pattern: "must / mustn't + 動詞の原形", example: "You must wear a seat belt.", exampleJapanese: "シートベルトを着けなければなりません。", note: "mustn't は「してはいけない」で、don't have to とは意味が異なります。" },
  { id: "g-079", level: "A2", term: "動名詞を主語にする", japanese: "行動を主語として表す", category: "動詞の形", label: "文法", pattern: "動詞-ing + 動詞", example: "Learning languages takes time.", exampleJapanese: "言語を学ぶことには時間がかかります。", note: "動詞の -ing 形を文の主語にできます。" },
  { id: "g-080", level: "A2", term: "because / so", japanese: "理由と結果をつなぐ", category: "文のつながり", label: "文法", pattern: "because + 理由 / so + 結果", example: "I stayed home because I was tired.", exampleJapanese: "疲れていたので、私は家にいました。", note: "because と so を同じ文で重ねて使わないようにします。" },
  { id: "g-081", level: "B1", term: "現在完了進行形", japanese: "過去から今まで続く動作を表す", category: "時制", label: "文法", pattern: "have / has been + 動詞-ing", example: "I've been studying for two hours.", exampleJapanese: "私は2時間勉強し続けています。", note: "for や since と一緒に、継続時間を表すことが多いです。" },
  { id: "g-082", level: "B1", term: "make / let + 人 + 動詞の原形", japanese: "人に〜させる、〜するのを許す", category: "動詞の形", label: "文法", pattern: "make / let + 人 + 動詞の原形", example: "The teacher made us repeat the sentence.", exampleJapanese: "先生は私たちにその文を繰り返させました。", note: "make は強制、let は許可を表します。" },
  { id: "g-083", level: "B1", term: "have + 目的語 + 過去分詞", japanese: "サービスを受ける・依頼する", category: "動詞の形", label: "文法", pattern: "have + 物 + 過去分詞", example: "I had my hair cut yesterday.", exampleJapanese: "私は昨日髪を切ってもらいました。", note: "自分で行うのでなく、他の人にしてもらうときに使います。" },
  { id: "g-084", level: "B1", term: "despite / in spite of", japanese: "〜にもかかわらず", category: "文のつながり", label: "文法", pattern: "despite / in spite of + 名詞・-ing", example: "Despite the rain, we went out.", exampleJapanese: "雨にもかかわらず、私たちは出かけました。", note: "後ろには文ではなく、名詞か -ing 形を置きます。" },
  { id: "g-085", level: "B1", term: "unless", japanese: "〜でない限り", category: "文のつながり", label: "文法", pattern: "unless + 文", example: "I won't go unless you come with me.", exampleJapanese: "あなたが一緒に来ない限り、私は行きません。", note: "unless は if ... not に近い意味です。" },
  { id: "g-086", level: "B1", term: "wish + 過去形", japanese: "現在と違う願いを表す", category: "文のつながり", label: "文法", pattern: "wish + 過去形", example: "I wish I had more time.", exampleJapanese: "もっと時間があればいいのに。", note: "現在の事実とは違う願いを表すとき、過去形を使います。" },
  { id: "g-087", level: "B1", term: "so that", japanese: "〜できるように、〜するために", category: "文のつながり", label: "文法", pattern: "so that + 主語 + can / could", example: "I wrote it down so that I could remember it.", exampleJapanese: "覚えられるように、それを書き留めました。", note: "目的を、主語を含む文で説明するときに使います。" },
  { id: "g-088", level: "B1", term: "whose / where", japanese: "所有者・場所を説明する関係詞", category: "文のつながり", label: "文法", pattern: "the person whose ... / the place where ...", example: "I know a woman whose son lives in Bali.", exampleJapanese: "私は息子がバリに住んでいる女性を知っています。", note: "whose は所有、where は場所を後ろから説明します。" },
  { id: "g-089", level: "B1", term: "must / might / can't", japanese: "根拠からの推測を表す", category: "助動詞", label: "文法", pattern: "must / might / can't + 動詞の原形", example: "She must be at home; the lights are on.", exampleJapanese: "電気がついているので、彼女は家にいるに違いありません。", note: "must は強い確信、might は可能性、can't は不可能だという判断です。" },
  { id: "g-090", level: "B1", term: "prefer A to B", japanese: "BよりAを好む", category: "比較", label: "文法", pattern: "prefer + 名詞・-ing + to + 名詞・-ing", example: "I prefer tea to coffee.", exampleJapanese: "私はコーヒーよりお茶のほうが好きです。", note: "prefer の比較では than ではなく to を使います。" }
];

export const ADDITIONAL_IDIOMS: ExpandedStudyItem[] = [
  { id: "i-091", level: "A1", term: "get back", japanese: "戻る、帰る", category: "移動", label: "熟語", example: "When did you get back from work?", exampleJapanese: "仕事からいつ戻りましたか。", note: "get back from + 場所で「〜から戻る」と表せます。" },
  { id: "i-092", level: "A1", term: "put down", japanese: "置く", category: "毎日の行動", label: "熟語", example: "Put down your bag here.", exampleJapanese: "ここにバッグを置いてください。", note: "代名詞では put it down の語順にします。" },
  { id: "i-093", level: "A1", term: "take out", japanese: "取り出す", category: "毎日の行動", label: "熟語", example: "Take out your phone.", exampleJapanese: "携帯電話を取り出してください。", note: "take out + 物で、中から物を取り出すことを表します。" },
  { id: "i-094", level: "A1", term: "turn around", japanese: "振り向く、向きを変える", category: "移動", label: "熟語", example: "Turn around and look at the board.", exampleJapanese: "振り向いて黒板を見てください。", note: "体や車の向きを反対に変えるときに使います。" },
  { id: "i-095", level: "A1", term: "move in", japanese: "引っ越して住み始める", category: "家・生活", label: "熟語", example: "We moved in last month.", exampleJapanese: "私たちは先月引っ越してきました。", note: "新しい家や部屋に住み始めることを表します。" },
  { id: "i-096", level: "A1", term: "move out", japanese: "引っ越して出る", category: "家・生活", label: "熟語", example: "He moved out of his parents' house.", exampleJapanese: "彼は両親の家を出ました。", note: "move in の反対で、住んでいた場所を出ることを表します。" },
  { id: "i-097", level: "A1", term: "go upstairs", japanese: "上の階へ行く", category: "移動", label: "熟語", example: "Go upstairs and get your coat.", exampleJapanese: "上の階へ行ってコートを取ってきてください。", note: "upstairs は副詞なので、通常 to を付けません。" },
  { id: "i-098", level: "A1", term: "come downstairs", japanese: "下の階へ降りてくる", category: "移動", label: "熟語", example: "Come downstairs when you're ready.", exampleJapanese: "準備ができたら下の階へ降りてきてください。", note: "downstairs も副詞なので、通常 to を付けません。" },
  { id: "i-099", level: "A1", term: "look inside", japanese: "中を見る", category: "毎日の行動", label: "熟語", example: "Look inside the box.", exampleJapanese: "箱の中を見てください。", note: "look inside + 容器・場所 の形で使います。" },
  { id: "i-100", level: "A1", term: "come on", japanese: "さあ、急いで、がんばって", category: "会話", label: "熟語", example: "Come on, we're late.", exampleJapanese: "さあ、急がないと遅れます。", note: "急がせるときや、相手を励ますときに使うカジュアルな表現です。" },
  { id: "i-101", level: "A2", term: "get ready for", japanese: "〜の準備をする", category: "毎日の行動", label: "熟語", example: "Get ready for school.", exampleJapanese: "学校の準備をしてください。", note: "get ready for + 名詞で、これから始まることへの準備を表します。" },
  { id: "i-102", level: "A2", term: "look up", japanese: "調べる", category: "学習", label: "熟語", example: "Look up this word in a dictionary.", exampleJapanese: "この単語を辞書で調べてください。", note: "辞書やインターネットで情報を調べるときに使います。" },
  { id: "i-103", level: "A2", term: "take back", japanese: "持ち帰って返品する、撤回する", category: "買い物", label: "熟語", example: "I'd like to take this shirt back.", exampleJapanese: "このシャツを返品したいです。", note: "店へ返品する意味のほか、発言を撤回する意味もあります。" },
  { id: "i-104", level: "A2", term: "try out", japanese: "試してみる", category: "日常", label: "熟語", example: "Let's try out the new restaurant.", exampleJapanese: "新しいレストランを試してみましょう。", note: "新しい物や方法を実際に使って試すときに使います。" },
  { id: "i-105", level: "A2", term: "go on", japanese: "続ける", category: "会話", label: "熟語", example: "Please go on with your story.", exampleJapanese: "話を続けてください。", note: "go on with + 名詞、または go on -ing で継続を表します。" },
  { id: "i-106", level: "A2", term: "come true", japanese: "実現する", category: "感情・状態", label: "熟語", example: "Her dream came true.", exampleJapanese: "彼女の夢は実現しました。", note: "dream や wish が主語になり、願いが実現することを表します。" },
  { id: "i-107", level: "A2", term: "fall asleep", japanese: "眠りに落ちる", category: "毎日の行動", label: "熟語", example: "I fell asleep on the bus.", exampleJapanese: "私はバスの中で眠ってしまいました。", note: "sleep は「眠っている」、fall asleep は「眠り始める」です。" },
  { id: "i-108", level: "A2", term: "get lost", japanese: "道に迷う", category: "旅行", label: "熟語", example: "We got lost in the old town.", exampleJapanese: "私たちは旧市街で道に迷いました。", note: "場所が分からなくなって迷うことを表します。" },
  { id: "i-109", level: "A2", term: "leave behind", japanese: "置き忘れる、残していく", category: "旅行", label: "熟語", example: "Don't leave your bag behind.", exampleJapanese: "バッグを置き忘れないでください。", note: "leave + 物 + behind の語順でも使えます。" },
  { id: "i-110", level: "A2", term: "take a break", japanese: "休憩する", category: "毎日の行動", label: "熟語", example: "Let's take a break.", exampleJapanese: "休憩しましょう。", note: "短い休憩には take a short break と言えます。" },
  { id: "i-111", level: "B1", term: "catch up with", japanese: "〜に追いつく、最新情報を得る", category: "仕事・学習", label: "熟語", example: "I need to catch up with the latest news.", exampleJapanese: "最新のニュースを確認して遅れを取り戻す必要があります。", note: "人や情報、進み具合に遅れず追いつくことを表します。" },
  { id: "i-112", level: "B1", term: "come down with", japanese: "（病気に）かかる", category: "日常", label: "熟語", example: "He came down with a cold.", exampleJapanese: "彼は風邪をひきました。", note: "come down with + 病気で、病気にかかり始めることを表します。" },
  { id: "i-113", level: "B1", term: "get over", japanese: "回復する、乗り越える", category: "感情・状態", label: "熟語", example: "It took her a week to get over the flu.", exampleJapanese: "彼女がインフルエンザから回復するのに1週間かかりました。", note: "病気から回復する意味と、つらい経験を乗り越える意味があります。" },
  { id: "i-114", level: "B1", term: "look into", japanese: "調査する、詳しく調べる", category: "仕事・学習", label: "熟語", example: "The company is looking into the problem.", exampleJapanese: "会社はその問題を調査しています。", note: "問題や可能性を詳しく調べるときに使います。" },
  { id: "i-115", level: "B1", term: "make out", japanese: "見分ける、聞き取る、理解する", category: "会話", label: "熟語", example: "I couldn't make out what he said.", exampleJapanese: "私は彼が言ったことを聞き取れませんでした。", note: "はっきり見えない・聞こえないものを理解する意味で使います。" },
  { id: "i-116", level: "B1", term: "pass on", japanese: "伝える、渡す", category: "会話", label: "熟語", example: "Please pass on this message to Ken.", exampleJapanese: "このメッセージをケンに伝えてください。", note: "情報や物を別の人へ渡したり伝えたりするときに使います。" },
  { id: "i-117", level: "B1", term: "put down to", japanese: "〜のせいだと考える", category: "会話", label: "熟語", example: "I put the delay down to bad traffic.", exampleJapanese: "私は遅れの原因をひどい渋滞だと考えました。", note: "put A down to B で、Aの原因をBだと考える意味です。" },
  { id: "i-118", level: "B1", term: "run through", japanese: "ざっと確認する、通して練習する", category: "仕事・学習", label: "熟語", example: "Let's run through the presentation once more.", exampleJapanese: "もう一度プレゼンテーションを通して確認しましょう。", note: "手順・発表・説明などを最初から最後まで確認するときに使います。" },
  { id: "i-119", level: "B1", term: "take up", japanese: "始める、占める", category: "日常", label: "熟語", example: "He took up tennis last year.", exampleJapanese: "彼は昨年テニスを始めました。", note: "趣味や活動を始める意味のほか、場所や時間を占める意味があります。" },
  { id: "i-120", level: "B1", term: "turn to", japanese: "〜に頼る、相談する", category: "人間関係", label: "熟語", example: "She turned to her teacher for advice.", exampleJapanese: "彼女は助言を求めて先生に相談しました。", note: "turn to + 人 for + 助け で、困ったときに頼る相手を表します。" }
];

export const ADDITIONAL_INDONESIAN_TRANSLATIONS: Record<string, string> = {
  "w-211": "bandara", "w-212": "botol", "w-213": "kalender", "w-214": "kamera", "w-215": "sudut", "w-216": "lift; elevator", "w-217": "pintu masuk", "w-218": "lantai; tingkat", "w-219": "rumah sakit", "w-220": "peta",
  "w-221": "ke luar negeri; di luar negeri", "w-222": "bagasi; barang bawaan", "w-223": "jembatan", "w-224": "jarak", "w-225": "peralatan", "w-226": "pemandu; memandu", "w-227": "perjalanan", "w-228": "bahasa", "w-229": "penumpang", "w-230": "peron",
  "w-231": "sikap", "w-232": "kesadaran", "w-233": "keseimbangan", "w-234": "perilaku", "w-235": "anggaran", "w-236": "kekhawatiran", "w-237": "kepercayaan diri", "w-238": "bukti", "w-239": "dampak; memengaruhi", "w-240": "hasil",
  "p-061": "Bagaimana mengejanya?", "p-062": "Anda dari mana?", "p-063": "Bisakah Anda berbicara perlahan?", "p-064": "Ini ... saya.", "p-065": "Saya butuh bantuan.", "p-066": "Saya lapar.", "p-067": "Ayo pergi.", "p-068": "Permisi.", "p-069": "Mohon tunggu sebentar.", "p-070": "Di mana toilet?",
  "p-071": "Bisakah Anda mengulanginya?", "p-072": "Saya sedang dalam perjalanan.", "p-073": "Apa yang harus saya lakukan?", "p-074": "Saya lebih suka ...", "p-075": "Saya menantikan ...", "p-076": "Dapatkah Anda menunjukkan arah ke ...?", "p-077": "Apakah ... tersedia?", "p-078": "Saya akan memikirkannya.", "p-079": "Itu cocok untuk saya.", "p-080": "Saya berubah pikiran.",
  "p-081": "Apakah Anda dapat ...?", "p-082": "Saya mengerti maksud Anda.", "p-083": "Itu poin yang bagus.", "p-084": "Dari sudut pandang saya, ...", "p-085": "Saya lebih memilih untuk ...", "p-086": "Mungkin lebih baik untuk ...", "p-087": "Maksud saya adalah ...", "p-088": "Saya bertanggung jawab atas ...", "p-089": "Saya akan menghargainya jika ...", "p-090": "Tidak perlu untuk ...",
  "g-061": "kata ganti subjek", "g-062": "kata sifat + kata benda", "g-063": "jangan + kata kerja", "g-064": "kata keterangan frekuensi", "g-065": "pertanyaan bentuk sedang", "g-066": "memiliki", "g-067": "berapa banyak", "g-068": "milik siapa", "g-069": "ejaan orang ketiga tunggal", "g-070": "jawaban singkat",
  "g-071": "ingin secara sopan", "g-072": "beberapa; sedikit", "g-073": "terlalu; cukup", "g-074": "masing-masing; setiap", "g-075": "satu; yang-jamak", "g-076": "sedang berlangsung di masa lalu + lampau", "g-077": "mungkin", "g-078": "harus; dilarang", "g-079": "gerund sebagai subjek", "g-080": "karena; jadi",
  "g-081": "present perfect continuous", "g-082": "membuat; mengizinkan seseorang melakukan", "g-083": "meminta layanan dilakukan", "g-084": "meskipun", "g-085": "kecuali jika", "g-086": "berharap (berlawanan dengan keadaan sekarang)", "g-087": "agar", "g-088": "yang; tempat di mana", "g-089": "dugaan kuat; kemungkinan; tidak mungkin", "g-090": "lebih memilih A daripada B",
  "i-091": "kembali", "i-092": "meletakkan", "i-093": "mengeluarkan", "i-094": "berbalik", "i-095": "pindah masuk", "i-096": "pindah keluar", "i-097": "naik ke lantai atas", "i-098": "turun ke lantai bawah", "i-099": "melihat ke dalam", "i-100": "ayo; cepatlah",
  "i-101": "bersiap untuk", "i-102": "mencari informasi", "i-103": "mengembalikan; menarik kembali", "i-104": "mencoba", "i-105": "melanjutkan", "i-106": "menjadi kenyataan", "i-107": "tertidur", "i-108": "tersesat", "i-109": "meninggalkan; lupa membawa", "i-110": "beristirahat",
  "i-111": "mengejar; mengikuti perkembangan", "i-112": "terkena penyakit", "i-113": "pulih; mengatasi", "i-114": "menyelidiki", "i-115": "mengenali; memahami", "i-116": "meneruskan", "i-117": "menganggap disebabkan oleh", "i-118": "meninjau; berlatih secara keseluruhan", "i-119": "mulai; mengambil ruang", "i-120": "berpaling kepada; meminta bantuan"
};

export const ADDITIONAL_SECOND_EXAMPLES: Record<string, ExpandedExamplePair> = {
  "w-211": { english: "We arrived at the airport early.", japanese: "私たちは早く空港に到着しました。" },
  "w-212": { english: "Please recycle this bottle.", japanese: "このボトルをリサイクルしてください。" },
  "w-213": { english: "I check my calendar every morning.", japanese: "私は毎朝カレンダーを確認します。" },
  "w-214": { english: "She took a photo with her camera.", japanese: "彼女はカメラで写真を撮りました。" },
  "w-215": { english: "Turn left at the next corner.", japanese: "次の角を左に曲がってください。" },
  "w-216": { english: "The elevator is over there.", japanese: "エレベーターはあちらです。" },
  "w-217": { english: "Use the main entrance.", japanese: "正面入口を使ってください。" },
  "w-218": { english: "The keys are on the floor.", japanese: "鍵は床の上にあります。" },
  "w-219": { english: "She works at the local hospital.", japanese: "彼女は地元の病院で働いています。" },
  "w-220": { english: "This map shows the bus stops.", japanese: "この地図にはバス停が示されています。" },
  "w-221": { english: "She has never traveled abroad.", japanese: "彼女は海外旅行をしたことがありません。" },
  "w-222": { english: "Your luggage is on the cart.", japanese: "あなたの荷物はカートの上にあります。" },
  "w-223": { english: "The bridge is closed today.", japanese: "その橋は今日は閉鎖されています。" },
  "w-224": { english: "We walked a short distance.", japanese: "私たちは短い距離を歩きました。" },
  "w-225": { english: "Please put the equipment away after class.", japanese: "授業の後で用具を片付けてください。" },
  "w-226": { english: "This book will guide you step by step.", japanese: "この本はあなたを段階的に案内してくれます。" },
  "w-227": { english: "Have a safe journey home.", japanese: "気をつけて帰ってください。" },
  "w-228": { english: "She speaks three languages.", japanese: "彼女は3つの言語を話します。" },
  "w-229": { english: "The passengers are waiting to board.", japanese: "乗客は搭乗を待っています。" },
  "w-230": { english: "Please wait on platform five.", japanese: "5番ホームでお待ちください。" },
  "w-231": { english: "He has a positive attitude toward learning.", japanese: "彼は学習に前向きな姿勢を持っています。" },
  "w-232": { english: "We need greater awareness of online safety.", japanese: "私たちはオンライン安全への意識をもっと高める必要があります。" },
  "w-233": { english: "She lost her balance on the stairs.", japanese: "彼女は階段でバランスを崩しました。" },
  "w-234": { english: "The teacher spoke about classroom behavior.", japanese: "先生は教室での行動について話しました。" },
  "w-235": { english: "She made a budget for the trip.", japanese: "彼女は旅行の予算を立てました。" },
  "w-236": { english: "The manager listened to their concerns.", japanese: "管理者は彼らの懸念を聞きました。" },
  "w-237": { english: "He spoke with confidence.", japanese: "彼は自信を持って話しました。" },
  "w-238": { english: "The report provides evidence for the idea.", japanese: "その報告書はその考えを支持する根拠を示しています。" },
  "w-239": { english: "This decision may impact the schedule.", japanese: "この決定はスケジュールに影響するかもしれません。" },
  "w-240": { english: "The outcome was better than expected.", japanese: "結果は予想より良かったです。" },
  "p-061": { english: "Could you spell your name, please?", japanese: "お名前をつづっていただけますか。" },
  "p-062": { english: "I'm from a small town near Jakarta.", japanese: "私はジャカルタ近くの小さな町の出身です。" },
  "p-063": { english: "Sorry, could you say that more slowly?", japanese: "すみません、もう少しゆっくり言ってもらえますか。" },
  "p-064": { english: "This is my brother, Ken.", japanese: "こちらは私の兄弟のケンです。" },
  "p-065": { english: "Do you need any help?", japanese: "何か助けが必要ですか。" },
  "p-066": { english: "Are you hungry after the walk?", japanese: "歩いた後でおなかがすきましたか。" },
  "p-067": { english: "Let's go to the park.", japanese: "公園へ行きましょう。" },
  "p-068": { english: "Excuse me, is this seat free?", japanese: "すみません、この席は空いていますか。" },
  "p-069": { english: "Wait a moment. I'll check.", japanese: "少し待ってください。確認します。" },
  "p-070": { english: "Is there a restroom near here?", japanese: "この近くにトイレはありますか。" },
  "p-071": { english: "Could you repeat the last part?", japanese: "最後の部分をもう一度言っていただけますか。" },
  "p-072": { english: "Don't worry. I'm on my way.", japanese: "心配しないでください。今向かっています。" },
  "p-073": { english: "I made a mistake. What should I do?", japanese: "間違えました。私は何をすればよいですか。" },
  "p-074": { english: "I'd rather take the train than drive.", japanese: "運転するより電車に乗りたいです。" },
  "p-075": { english: "We're looking forward to meeting you.", japanese: "私たちはお会いできるのを楽しみにしています。" },
  "p-076": { english: "Could you point me to the exit?", japanese: "出口の場所を教えていただけますか。" },
  "p-077": { english: "Are there any tickets available?", japanese: "利用できるチケットはありますか。" },
  "p-078": { english: "Thanks for the offer. I'll think about it.", japanese: "申し出をありがとう。考えておきます。" },
  "p-079": { english: "Tuesday morning works for me.", japanese: "火曜日の朝で大丈夫です。" },
  "p-080": { english: "I've changed my mind about the color.", japanese: "色について気が変わりました。" },
  "p-081": { english: "Would you be able to meet next week?", japanese: "来週お会いすることは可能ですか。" },
  "p-082": { english: "I see what you mean now.", japanese: "今、言いたいことが分かりました。" },
  "p-083": { english: "That's a good point about safety.", japanese: "安全についてのそれはもっともな点です。" },
  "p-084": { english: "From my point of view, we need more information.", japanese: "私の見方では、私たちにはもっと情報が必要です。" },
  "p-085": { english: "I would prefer to pay by card.", japanese: "できればカードで支払いたいです。" },
  "p-086": { english: "It might be better to ask first.", japanese: "まず聞いたほうがよいかもしれません。" },
  "p-087": { english: "What I mean is that the deadline is too soon.", japanese: "私が言いたいのは、締め切りが早すぎるということです。" },
  "p-088": { english: "I'm responsible for answering customer emails.", japanese: "私は顧客メールへの返信を担当しています。" },
  "p-089": { english: "I'd appreciate it if you let me know.", japanese: "知らせていただけるとありがたいです。" },
  "p-090": { english: "There is no need to bring anything.", japanese: "何も持ってくる必要はありません。" },
  "g-061": { english: "She lives near here.", japanese: "彼女はこの近くに住んでいます。" },
  "g-062": { english: "She bought a red dress.", japanese: "彼女は赤いドレスを買いました。" },
  "g-063": { english: "Don't worry about it.", japanese: "そのことは心配しないでください。" },
  "g-064": { english: "He is always kind.", japanese: "彼はいつも親切です。" },
  "g-065": { english: "What are they doing?", japanese: "彼らは何をしていますか。" },
  "g-066": { english: "Has she got your address?", japanese: "彼女はあなたの住所を知っていますか。" },
  "g-067": { english: "How much water do you drink?", japanese: "どのくらい水を飲みますか。" },
  "g-068": { english: "Whose shoes are by the door?", japanese: "ドアのそばにある靴は誰のですか。" },
  "g-069": { english: "She studies English every day.", japanese: "彼女は毎日英語を勉強します。" },
  "g-070": { english: "Is he ready? - No, he isn't.", japanese: "彼は準備ができていますか。- いいえ、できていません。" },
  "g-071": { english: "Would you like some tea?", japanese: "紅茶はいかがですか。" },
  "g-072": { english: "Add a little sugar.", japanese: "砂糖を少し加えてください。" },
  "g-073": { english: "Is the room warm enough?", japanese: "その部屋は十分暖かいですか。" },
  "g-074": { english: "I study English every day.", japanese: "私は毎日英語を勉強します。" },
  "g-075": { english: "Which ones do you want?", japanese: "どれが欲しいですか。" },
  "g-076": { english: "They were walking home when it started to rain.", japanese: "雨が降り始めたとき、彼らは歩いて帰宅していました。" },
  "g-077": { english: "She might be busy now.", japanese: "彼女は今忙しいかもしれません。" },
  "g-078": { english: "You mustn't use your phone here.", japanese: "ここで携帯電話を使ってはいけません。" },
  "g-079": { english: "Cooking at home saves money.", japanese: "家で料理をするとお金の節約になります。" },
  "g-080": { english: "It was raining, so we took a taxi.", japanese: "雨が降っていたので、私たちはタクシーに乗りました。" },
  "g-081": { english: "She has been working here since May.", japanese: "彼女は5月からここで働き続けています。" },
  "g-082": { english: "My parents let me use the car.", japanese: "両親は私が車を使うことを許可してくれました。" },
  "g-083": { english: "We're having the kitchen painted.", japanese: "私たちはキッチンを塗装してもらっています。" },
  "g-084": { english: "In spite of feeling tired, he kept working.", japanese: "疲れているにもかかわらず、彼は働き続けました。" },
  "g-085": { english: "You can't enter unless you have a ticket.", japanese: "チケットを持っていない限り、入場できません。" },
  "g-086": { english: "She wishes she lived closer.", japanese: "彼女はもっと近くに住んでいればいいのにと思っています。" },
  "g-087": { english: "Speak clearly so that everyone can understand.", japanese: "みんなが理解できるように、はっきり話してください。" },
  "g-088": { english: "This is the cafe where we first met.", japanese: "ここは私たちが初めて会ったカフェです。" },
  "g-089": { english: "He might be busy.", japanese: "彼は忙しいかもしれません。" },
  "g-090": { english: "They prefer walking to taking the bus.", japanese: "彼らはバスに乗るより歩くほうを好みます。" },
  "i-091": { english: "I'll get back before dinner.", japanese: "夕食前に戻ります。" },
  "i-092": { english: "She put the cup down carefully.", japanese: "彼女はカップを慎重に置きました。" },
  "i-093": { english: "He took the keys out of his pocket.", japanese: "彼はポケットから鍵を取り出しました。" },
  "i-094": { english: "The car turned around at the end of the road.", japanese: "車は道の終わりで向きを変えました。" },
  "i-095": { english: "When are you moving in?", japanese: "いつ引っ越して住み始めますか。" },
  "i-096": { english: "They are moving out next week.", japanese: "彼らは来週引っ越して出ます。" },
  "i-097": { english: "The children went upstairs to bed.", japanese: "子どもたちは寝るために上の階へ行きました。" },
  "i-098": { english: "She came downstairs for breakfast.", japanese: "彼女は朝食のために下の階へ降りてきました。" },
  "i-099": { english: "I looked inside my bag for the ticket.", japanese: "私はチケットを探してバッグの中を見ました。" },
  "i-100": { english: "Come on! You can do it.", japanese: "がんばって！ あなたならできます。" },
  "i-101": { english: "We need to get ready for the meeting.", japanese: "私たちは会議の準備をする必要があります。" },
  "i-102": { english: "I looked up the train times online.", japanese: "私は電車の時刻をオンラインで調べました。" },
  "i-103": { english: "He took back what he said.", japanese: "彼は自分の発言を撤回しました。" },
  "i-104": { english: "She tried out the app before buying it.", japanese: "彼女は購入前にそのアプリを試しました。" },
  "i-105": { english: "The class went on for an hour.", japanese: "授業は1時間続きました。" },
  "i-106": { english: "I hope your wish comes true.", japanese: "あなたの願いがかないますように。" },
  "i-107": { english: "The baby fell asleep quickly.", japanese: "赤ちゃんはすぐに眠りました。" },
  "i-108": { english: "Use this map so you don't get lost.", japanese: "道に迷わないようにこの地図を使ってください。" },
  "i-109": { english: "I left my umbrella behind at the cafe.", japanese: "私はカフェに傘を置き忘れました。" },
  "i-110": { english: "She takes a short break every hour.", japanese: "彼女は毎時間短い休憩を取ります。" },
  "i-111": { english: "She worked late to catch up with her classmates.", japanese: "彼女はクラスメートに追いつくために遅くまで勉強しました。" },
  "i-112": { english: "I think I'm coming down with something.", japanese: "何かの病気にかかり始めている気がします。" },
  "i-113": { english: "He's still getting over the disappointment.", japanese: "彼はまだその失望を乗り越えようとしています。" },
  "i-114": { english: "I'll look into the cost and tell you.", japanese: "費用を調べてお伝えします。" },
  "i-115": { english: "Can you make out the sign in the distance?", japanese: "遠くにある標識を見分けられますか。" },
  "i-116": { english: "She passed on some useful advice.", japanese: "彼女は役に立つ助言を伝えてくれました。" },
  "i-117": { english: "They put his success down to hard work.", japanese: "彼らは彼の成功を努力の結果だと考えました。" },
  "i-118": { english: "She ran through the instructions before we started.", japanese: "彼女は始める前に説明をざっと確認しました。" },
  "i-119": { english: "The sofa takes up too much space.", japanese: "そのソファは場所を取りすぎます。" },
  "i-120": { english: "When I have a problem, I turn to my family.", japanese: "問題があるとき、私は家族に頼ります。" }
};
