export type ExpandedStudyItem = {
  id: string;
  level: "A1" | "A2" | "B1";
  term: string;
  japanese: string;
  category: string;
  label: string;
  pronunciation?: string;
  example: string;
  exampleJapanese: string;
  note: string;
  pattern?: string;
};

export type ExpandedExamplePair = { english: string; japanese: string };

export const EXTRA_WORDS: ExpandedStudyItem[] = [
  { id: "w-031", level: "A1", term: "like", japanese: "好き、好む", category: "基本", label: "動詞", pronunciation: "/laɪk/", example: "I like this song.", exampleJapanese: "私はこの歌が好きです。", note: "like + 名詞 / -ing で、好きな物や行動を表せます。" },
  { id: "w-032", level: "A1", term: "live", japanese: "住む、生きる", category: "日常", label: "動詞", pronunciation: "/lɪv/", example: "They live near the station.", exampleJapanese: "彼らは駅の近くに住んでいます。", note: "live in + 場所 で「〜に住む」。" },
  { id: "w-033", level: "A1", term: "work", japanese: "働く、仕事", category: "仕事・学習", label: "動詞/名詞", pronunciation: "/wɜːrk/", example: "She works at a hotel.", exampleJapanese: "彼女はホテルで働いています。", note: "動詞と名詞の両方で使える基本語です。" },
  { id: "w-034", level: "A1", term: "eat", japanese: "食べる", category: "日常", label: "動詞", pronunciation: "/iːt/", example: "We eat dinner at home.", exampleJapanese: "私たちは家で夕食を食べます。", note: "過去形は ate、過去分詞は eaten です。" },
  { id: "w-035", level: "A1", term: "drink", japanese: "飲む、飲み物", category: "日常", label: "動詞/名詞", pronunciation: "/drɪŋk/", example: "He drinks tea in the morning.", exampleJapanese: "彼は朝にお茶を飲みます。", note: "動詞にも名詞にもなります。" },
  { id: "w-036", level: "A1", term: "family", japanese: "家族", category: "人", label: "名詞", pronunciation: "/ˈfæməli/", example: "My family lives in Osaka.", exampleJapanese: "私の家族は大阪に住んでいます。", note: "家族を一つの集団として扱うときは単数扱いにできます。" },
  { id: "w-037", level: "A1", term: "friend", japanese: "友人", category: "人", label: "名詞", pronunciation: "/frend/", example: "Mika is my best friend.", exampleJapanese: "ミカは私の親友です。", note: "make friends で「友だちを作る」。" },
  { id: "w-038", level: "A1", term: "morning", japanese: "朝、午前", category: "時間", label: "名詞", pronunciation: "/ˈmɔːrnɪŋ/", example: "I study English every morning.", exampleJapanese: "私は毎朝英語を勉強します。", note: "in the morning で「朝に」。" },
  { id: "w-039", level: "A1", term: "week", japanese: "週", category: "時間", label: "名詞", pronunciation: "/wiːk/", example: "The class starts next week.", exampleJapanese: "授業は来週始まります。", note: "a week は「1週間」、every week は「毎週」。" },
  { id: "w-040", level: "A1", term: "small", japanese: "小さい", category: "感情・状態", label: "形容詞", pronunciation: "/smɔːl/", example: "They live in a small apartment.", exampleJapanese: "彼らは小さなアパートに住んでいます。", note: "small は大きさや規模が小さいことを表します。" },
  { id: "w-041", level: "A1", term: "near", japanese: "近くに、近い", category: "移動", label: "前置詞/形容詞", pronunciation: "/nɪr/", example: "The bank is near the station.", exampleJapanese: "銀行は駅の近くにあります。", note: "be near + 場所 の形がよく使われます。" },
  { id: "w-042", level: "A1", term: "because", japanese: "なぜなら、〜だから", category: "基本", label: "接続詞", pronunciation: "/bɪˈkɔːz/", example: "I stayed home because it was raining.", exampleJapanese: "雨が降っていたので、私は家にいました。", note: "because の後ろには主語と動詞を含む文を続けます。" },
  { id: "w-043", level: "A2", term: "plan", japanese: "計画、計画する", category: "仕事・学習", label: "名詞/動詞", pronunciation: "/plæn/", example: "We plan to visit Bali in July.", exampleJapanese: "私たちは7月にバリを訪れる予定です。", note: "plan to + 動詞で「〜する予定を立てる」。" },
  { id: "w-044", level: "A2", term: "invite", japanese: "招待する", category: "人", label: "動詞", pronunciation: "/ɪnˈvaɪt/", example: "They invited us to dinner.", exampleJapanese: "彼らは私たちを夕食に招待しました。", note: "invite 人 to + 場所・行事 の形で使います。" },
  { id: "w-045", level: "A2", term: "arrive", japanese: "到着する", category: "移動", label: "動詞", pronunciation: "/əˈraɪv/", example: "The bus arrived late.", exampleJapanese: "バスは遅れて到着しました。", note: "arrive at + 小さい場所 / in + 都市・国 を使います。" },
  { id: "w-046", level: "A2", term: "leave", japanese: "出発する、残す", category: "移動", label: "動詞", pronunciation: "/liːv/", example: "The train leaves at six.", exampleJapanese: "電車は6時に出発します。", note: "出発する、物を置き去りにする、という二つの意味があります。" },
  { id: "w-047", level: "A2", term: "borrow", japanese: "借りる", category: "日常", label: "動詞", pronunciation: "/ˈbɑːroʊ/", example: "Can I borrow your pen?", exampleJapanese: "あなたのペンを借りてもいいですか。", note: "borrow は借りる側、lend は貸す側の動詞です。" },
  { id: "w-048", level: "A2", term: "return", japanese: "返す、戻る", category: "日常", label: "動詞", pronunciation: "/rɪˈtɜːrn/", example: "Please return the key tomorrow.", exampleJapanese: "明日、鍵を返してください。", note: "return + 物 で「返す」、return to + 場所 で「戻る」。" },
  { id: "w-049", level: "A2", term: "message", japanese: "メッセージ、連絡する", category: "日常", label: "名詞/動詞", pronunciation: "/ˈmesɪdʒ/", example: "I sent her a message.", exampleJapanese: "私は彼女にメッセージを送りました。", note: "send a message / message 人 のどちらも使えます。" },
  { id: "w-050", level: "A2", term: "ticket", japanese: "切符、チケット", category: "移動", label: "名詞", pronunciation: "/ˈtɪkɪt/", example: "I bought two train tickets.", exampleJapanese: "私は電車の切符を2枚買いました。", note: "train ticket や concert ticket のように使います。" },
  { id: "w-051", level: "A2", term: "problem", japanese: "問題、困ったこと", category: "仕事・学習", label: "名詞", pronunciation: "/ˈprɑːbləm/", example: "We have a small problem.", exampleJapanese: "私たちには小さな問題があります。", note: "have a problem / solve a problem が基本の組み合わせです。" },
  { id: "w-052", level: "A2", term: "solution", japanese: "解決策、答え", category: "仕事・学習", label: "名詞", pronunciation: "/səˈluːʃən/", example: "Let's find a solution together.", exampleJapanese: "一緒に解決策を見つけましょう。", note: "solution to + 問題 で「〜への解決策」。" },
  { id: "w-053", level: "A2", term: "local", japanese: "地元の、地域の", category: "移動", label: "形容詞", pronunciation: "/ˈloʊkəl/", example: "We ate at a local restaurant.", exampleJapanese: "私たちは地元のレストランで食べました。", note: "local people や local food のように名詞の前に置きます。" },
  { id: "w-054", level: "A2", term: "crowded", japanese: "混んでいる", category: "移動", label: "形容詞", pronunciation: "/ˈkraʊdɪd/", example: "The train is crowded this morning.", exampleJapanese: "今朝は電車が混んでいます。", note: "be crowded で「混雑している」。" },
  { id: "w-055", level: "A2", term: "expensive", japanese: "高価な", category: "日常", label: "形容詞", pronunciation: "/ɪkˈspensɪv/", example: "This hotel is too expensive.", exampleJapanese: "このホテルは高すぎます。", note: "物の値段が高いことを表します。" },
  { id: "w-056", level: "A2", term: "enough", japanese: "十分な、十分に", category: "感情・状態", label: "形容詞/副詞", pronunciation: "/ɪˈnʌf/", example: "We have enough time.", exampleJapanese: "私たちには十分な時間があります。", note: "名詞の前では enough time、形容詞の後では warm enough の語順です。" },
  { id: "w-057", level: "A2", term: "instead", japanese: "その代わりに", category: "基本", label: "副詞", pronunciation: "/ɪnˈsted/", example: "Let's walk instead of taking a taxi.", exampleJapanese: "タクシーに乗る代わりに歩きましょう。", note: "instead of の後ろは名詞か -ing 形です。" },
  { id: "w-058", level: "A2", term: "already", japanese: "すでに、もう", category: "時間", label: "副詞", pronunciation: "/ɔːlˈredi/", example: "I've already finished my homework.", exampleJapanese: "私はもう宿題を終えました。", note: "現在完了と一緒に使われることが多い語です。" },
  { id: "w-059", level: "A2", term: "recently", japanese: "最近", category: "時間", label: "副詞", pronunciation: "/ˈriːsəntli/", example: "I recently started a new job.", exampleJapanese: "私は最近、新しい仕事を始めました。", note: "過去形・現在完了のどちらとも使えます。" },
  { id: "w-060", level: "A2", term: "usually", japanese: "たいてい、普段は", category: "時間", label: "副詞", pronunciation: "/ˈjuːʒuəli/", example: "I usually take the bus.", exampleJapanese: "私は普段バスに乗ります。", note: "一般動詞の前、be動詞の後に置くのが基本です。" },
  { id: "w-061", level: "A2", term: "during", japanese: "〜の間に", category: "時間", label: "前置詞", pronunciation: "/ˈdʊrɪŋ/", example: "Please be quiet during the meeting.", exampleJapanese: "会議中は静かにしてください。", note: "during の後ろには名詞を置きます。" },
  { id: "w-062", level: "A2", term: "before", japanese: "〜の前に、以前に", category: "時間", label: "前置詞/副詞", pronunciation: "/bɪˈfɔːr/", example: "Wash your hands before dinner.", exampleJapanese: "夕食の前に手を洗ってください。", note: "before + 名詞・-ing のほか、副詞としても使えます。" },
  { id: "w-063", level: "A2", term: "after", japanese: "〜の後に", category: "時間", label: "前置詞/接続詞", pronunciation: "/ˈæftər/", example: "Let's talk after class.", exampleJapanese: "授業の後で話しましょう。", note: "after + 名詞・-ing の形がよく使われます。" },
  { id: "w-064", level: "A2", term: "together", japanese: "一緒に", category: "人", label: "副詞", pronunciation: "/təˈɡeðər/", example: "We can study together.", exampleJapanese: "私たちは一緒に勉強できます。", note: "動詞の後ろに置くことが多い副詞です。" },
  { id: "w-065", level: "B1", term: "achieve", japanese: "達成する", category: "仕事・学習", label: "動詞", pronunciation: "/əˈtʃiːv/", example: "She achieved her goal.", exampleJapanese: "彼女は目標を達成しました。", note: "achieve a goal / result のように使います。" },
  { id: "w-066", level: "B1", term: "avoid", japanese: "避ける", category: "日常", label: "動詞", pronunciation: "/əˈvɔɪd/", example: "Try to avoid making the same mistake.", exampleJapanese: "同じ間違いをしないようにしましょう。", note: "avoid の後ろには名詞か -ing 形を置きます。" },
  { id: "w-067", level: "B1", term: "compare", japanese: "比較する", category: "仕事・学習", label: "動詞", pronunciation: "/kəmˈper/", example: "Compare these two prices.", exampleJapanese: "この二つの価格を比べてください。", note: "compare A with B で二つを比較します。" },
  { id: "w-068", level: "B1", term: "consider", japanese: "検討する、考慮する", category: "仕事・学習", label: "動詞", pronunciation: "/kənˈsɪdər/", example: "We're considering moving next year.", exampleJapanese: "私たちは来年引っ越すことを検討しています。", note: "consider の後ろには名詞か -ing 形を置きます。" },
  { id: "w-069", level: "B1", term: "depend", japanese: "依存する、次第である", category: "仕事・学習", label: "動詞", pronunciation: "/dɪˈpend/", example: "It depends on the weather.", exampleJapanese: "それは天気次第です。", note: "depend on + 名詞・疑問詞節 の形で使います。" },
  { id: "w-070", level: "B1", term: "develop", japanese: "発展させる、身につける", category: "仕事・学習", label: "動詞", pronunciation: "/dɪˈveləp/", example: "She wants to develop her skills.", exampleJapanese: "彼女はスキルを伸ばしたいと思っています。", note: "develop skills / ability の組み合わせが重要です。" },
  { id: "w-071", level: "B1", term: "manage", japanese: "何とかやり遂げる、管理する", category: "仕事・学習", label: "動詞", pronunciation: "/ˈmænɪdʒ/", example: "I managed to catch the last bus.", exampleJapanese: "私は何とか終電に間に合いました。", note: "manage to + 動詞で「何とか〜する」。" },
  { id: "w-072", level: "B1", term: "prevent", japanese: "防ぐ", category: "日常", label: "動詞", pronunciation: "/prɪˈvent/", example: "A mask can prevent the spread of germs.", exampleJapanese: "マスクは細菌の拡散を防ぐことができます。", note: "prevent 人 from -ing で「人が〜するのを防ぐ」。" },
  { id: "w-073", level: "B1", term: "recommend", japanese: "勧める", category: "日常", label: "動詞", pronunciation: "/ˌrekəˈmend/", example: "I recommend trying the local food.", exampleJapanese: "地元の料理を試すことをおすすめします。", note: "recommend の後ろには名詞か -ing 形を置けます。" },
  { id: "w-074", level: "B1", term: "require", japanese: "必要とする、求める", category: "仕事・学習", label: "動詞", pronunciation: "/rɪˈkwaɪər/", example: "This job requires good communication skills.", exampleJapanese: "この仕事には優れたコミュニケーション能力が必要です。", note: "require + 名詞 / require 人 to + 動詞 の形を使います。" },
  { id: "w-075", level: "B1", term: "benefit", japanese: "利点、役に立つ", category: "仕事・学習", label: "名詞/動詞", pronunciation: "/ˈbenɪfɪt/", example: "Regular exercise has many benefits.", exampleJapanese: "定期的な運動には多くの利点があります。", note: "benefit from + 名詞で「〜から利益を得る」。" },
  { id: "w-076", level: "B1", term: "challenge", japanese: "課題、挑戦", category: "仕事・学習", label: "名詞/動詞", pronunciation: "/ˈtʃælɪndʒ/", example: "Learning a language is a challenge.", exampleJapanese: "言語を学ぶことは挑戦です。", note: "名詞と動詞の両方で使えます。" },
  { id: "w-077", level: "B1", term: "experience", japanese: "経験、体験", category: "仕事・学習", label: "名詞", pronunciation: "/ɪkˈspɪriəns/", example: "She has experience in customer service.", exampleJapanese: "彼女は接客業の経験があります。", note: "experience in + 分野 で経験のある分野を示せます。" },
  { id: "w-078", level: "B1", term: "goal", japanese: "目標", category: "仕事・学習", label: "名詞", pronunciation: "/ɡoʊl/", example: "My goal is to speak more clearly.", exampleJapanese: "私の目標はもっとはっきり話すことです。", note: "set a goal で「目標を立てる」。" },
  { id: "w-079", level: "B1", term: "habit", japanese: "習慣", category: "日常", label: "名詞", pronunciation: "/ˈhæbɪt/", example: "Reading is a good habit.", exampleJapanese: "読むことは良い習慣です。", note: "build a habit で習慣を身につけることを表せます。" },
  { id: "w-080", level: "B1", term: "issue", japanese: "問題、論点", category: "仕事・学習", label: "名詞", pronunciation: "/ˈɪʃuː/", example: "We need to discuss this issue.", exampleJapanese: "私たちはこの問題について話し合う必要があります。", note: "issue は problem よりやや公式な場面でも使われます。" },
  { id: "w-081", level: "B1", term: "progress", japanese: "進歩、進捗", category: "仕事・学習", label: "名詞", pronunciation: "/ˈprɑːɡres/", example: "You're making good progress.", exampleJapanese: "あなたは順調に進歩しています。", note: "progress は通常、数えない名詞です。" },
  { id: "w-082", level: "B1", term: "research", japanese: "調査、研究", category: "仕事・学習", label: "名詞", pronunciation: "/rɪˈsɜːrtʃ/", example: "The team is doing research on the topic.", exampleJapanese: "チームはそのテーマについて調査しています。", note: "research は通常、数えない名詞です。" },
  { id: "w-083", level: "B1", term: "responsible", japanese: "責任がある", category: "仕事・学習", label: "形容詞", pronunciation: "/rɪˈspɑːnsəbəl/", example: "She is responsible for the schedule.", exampleJapanese: "彼女はスケジュールを担当しています。", note: "responsible for + 名詞・-ing の形で使います。" },
  { id: "w-084", level: "B1", term: "flexible", japanese: "柔軟な、融通が利く", category: "仕事・学習", label: "形容詞", pronunciation: "/ˈfleksəbəl/", example: "My work hours are flexible.", exampleJapanese: "私の勤務時間は柔軟です。", note: "計画・勤務時間・考え方などに使えます。" },
  { id: "w-085", level: "B1", term: "effective", japanese: "効果的な", category: "仕事・学習", label: "形容詞", pronunciation: "/ɪˈfektɪv/", example: "This is an effective way to learn.", exampleJapanese: "これは効果的な学び方です。", note: "effective way / method の組み合わせがよく使われます。" },
  { id: "w-086", level: "B1", term: "familiar", japanese: "よく知っている、見慣れた", category: "感情・状態", label: "形容詞", pronunciation: "/fəˈmɪliər/", example: "Are you familiar with this software?", exampleJapanese: "このソフトウェアに詳しいですか。", note: "be familiar with + 名詞で「〜をよく知っている」。" },
  { id: "w-087", level: "B1", term: "likely", japanese: "ありそうな、可能性が高い", category: "感情・状態", label: "形容詞", pronunciation: "/ˈlaɪkli/", example: "It is likely to rain tomorrow.", exampleJapanese: "明日は雨が降りそうです。", note: "be likely to + 動詞で可能性の高さを表します。" },
  { id: "w-088", level: "B1", term: "specific", japanese: "具体的な、特定の", category: "仕事・学習", label: "形容詞", pronunciation: "/spəˈsɪfɪk/", example: "Could you give a specific example?", exampleJapanese: "具体的な例を挙げてもらえますか。", note: "specific information / example のように使います。" },
  { id: "w-089", level: "B1", term: "communicate", japanese: "伝える、意思疎通する", category: "仕事・学習", label: "動詞", pronunciation: "/kəˈmjuːnɪkeɪt/", example: "It's important to communicate clearly.", exampleJapanese: "明確に伝えることは重要です。", note: "communicate with 人 / by 手段 の形で使えます。" },
  { id: "w-090", level: "B1", term: "environment", japanese: "環境", category: "日常", label: "名詞", pronunciation: "/ɪnˈvaɪrənmənt/", example: "We should protect the environment.", exampleJapanese: "私たちは環境を守るべきです。", note: "自然環境のほか、学習・職場環境にも使えます。" }
];

export const EXTRA_PHRASES: ExpandedStudyItem[] = [
  { id: "p-011", level: "A1", term: "Where is ...?", japanese: "〜はどこですか。", category: "移動", label: "定型表現", example: "Where is the nearest station?", exampleJapanese: "一番近い駅はどこですか。", note: "場所を尋ねる基本の疑問文です。" },
  { id: "p-012", level: "A1", term: "Can I have ...?", japanese: "〜をいただけますか。", category: "お願い", label: "定型表現", example: "Can I have a glass of water, please?", exampleJapanese: "お水を一杯いただけますか。", note: "飲食店などで丁寧に注文するときに使えます。" },
  { id: "p-013", level: "A1", term: "I'm sorry.", japanese: "ごめんなさい。すみません。", category: "あいさつ", label: "定型表現", example: "I'm sorry I'm late.", exampleJapanese: "遅れてすみません。", note: "謝るときにも、軽く注意を引くときにも使えます。" },
  { id: "p-014", level: "A1", term: "See you later.", japanese: "またあとで。", category: "あいさつ", label: "定型表現", example: "Bye, see you later.", exampleJapanese: "じゃあ、またあとで。", note: "近いうちにまた会う相手へのカジュアルな別れのあいさつです。" },
  { id: "p-015", level: "A1", term: "I like ... .", japanese: "〜が好きです。", category: "会話", label: "定型表現", example: "I like listening to music.", exampleJapanese: "私は音楽を聴くのが好きです。", note: "like の後ろには名詞か -ing 形を置けます。" },
  { id: "p-016", level: "A2", term: "How long does it take?", japanese: "どのくらいかかりますか。", category: "移動", label: "定型表現", example: "How long does it take to get there?", exampleJapanese: "そこへ行くのにどのくらいかかりますか。", note: "時間の長さを尋ねる表現です。" },
  { id: "p-017", level: "A2", term: "Could I try this on?", japanese: "これを試着してもいいですか。", category: "買い物", label: "定型表現", example: "Could I try this jacket on?", exampleJapanese: "このジャケットを試着してもいいですか。", note: "try on は衣服を試着する句動詞です。" },
  { id: "p-018", level: "A2", term: "I'm looking for ... .", japanese: "〜を探しています。", category: "移動", label: "定型表現", example: "I'm looking for the museum.", exampleJapanese: "博物館を探しています。", note: "道を尋ねるときや店で探し物を伝えるときに便利です。" },
  { id: "p-019", level: "A2", term: "What happened?", japanese: "何が起きましたか。", category: "会話", label: "定型表現", example: "You look worried. What happened?", exampleJapanese: "心配そうですね。何がありましたか。", note: "相手に起きた出来事をたずねる表現です。" },
  { id: "p-020", level: "A2", term: "I'm not sure.", japanese: "よくわかりません。確信がありません。", category: "会話", label: "定型表現", example: "I'm not sure which bus to take.", exampleJapanese: "どのバスに乗るべきかよくわかりません。", note: "断定を避ける、やわらかい言い方です。" },
  { id: "p-021", level: "A2", term: "It depends.", japanese: "場合によります。", category: "会話", label: "定型表現", example: "Will it be busy? - It depends.", exampleJapanese: "混みますか。- 場合によります。", note: "It depends on ... と続けて理由を加えられます。" },
  { id: "p-022", level: "A2", term: "Would you like to ...?", japanese: "〜しませんか。", category: "お願い", label: "定型表現", example: "Would you like to join us for lunch?", exampleJapanese: "私たちとランチをご一緒しませんか。", note: "丁寧に誘うときの表現です。" },
  { id: "p-023", level: "B1", term: "Could you tell me ...?", japanese: "〜を教えていただけますか。", category: "お願い", label: "定型表現", example: "Could you tell me where the restroom is?", exampleJapanese: "お手洗いがどこにあるか教えていただけますか。", note: "後ろは疑問文の語順ではなく、主語 + 動詞の語順にします。" },
  { id: "p-024", level: "B1", term: "I agree with you.", japanese: "あなたに賛成です。", category: "意見", label: "定型表現", example: "I agree with you about that.", exampleJapanese: "その点についてあなたに賛成です。", note: "agree with + 人 で人の意見に賛成することを表します。" },
  { id: "p-025", level: "B1", term: "I'm afraid that ... .", japanese: "残念ですが、〜です。", category: "会話", label: "定型表現", example: "I'm afraid that the shop is closed.", exampleJapanese: "残念ですが、その店は閉まっています。", note: "悪い知らせをやわらかく伝える丁寧な表現です。" },
  { id: "p-026", level: "B1", term: "The reason is that ... .", japanese: "理由は〜です。", category: "意見", label: "定型表現", example: "The reason is that I have an appointment.", exampleJapanese: "理由は予定が入っているからです。", note: "理由を説明するときに使います。" },
  { id: "p-027", level: "B1", term: "As far as I know, ... .", japanese: "私の知る限り、〜です。", category: "意見", label: "定型表現", example: "As far as I know, the meeting starts at nine.", exampleJapanese: "私の知る限り、会議は9時に始まります。", note: "情報が完全ではない可能性を示す表現です。" },
  { id: "p-028", level: "B1", term: "I'd recommend ... .", japanese: "〜をおすすめします。", category: "意見", label: "定型表現", example: "I'd recommend taking the train.", exampleJapanese: "電車に乗ることをおすすめします。", note: "recommend の後ろには名詞か -ing 形を置けます。" },
  { id: "p-029", level: "B1", term: "Would it be possible to ...?", japanese: "〜することは可能でしょうか。", category: "お願い", label: "定型表現", example: "Would it be possible to change the date?", exampleJapanese: "日付を変更することは可能でしょうか。", note: "依頼をとても丁寧に伝える表現です。" },
  { id: "p-030", level: "B1", term: "I was wondering if ... .", japanese: "〜かと思っていたのですが。", category: "お願い", label: "定型表現", example: "I was wondering if you could help me.", exampleJapanese: "手伝っていただけないかと思っていたのですが。", note: "依頼をやわらかく切り出す表現です。" }
];

export const EXTRA_GRAMMAR: ExpandedStudyItem[] = [
  { id: "g-010", level: "A1", term: "冠詞 a / an / the", japanese: "名詞が特定かどうかを表す", category: "基本文", label: "文法", pattern: "a/an + 単数名詞 / the + 特定の名詞", example: "I saw a dog. The dog was friendly.", exampleJapanese: "私は犬を一匹見ました。その犬は人なつこかったです。", note: "初めて出す単数名詞には a/an、特定できるものには the を使います。" },
  { id: "g-011", level: "A1", term: "there is / there are", japanese: "〜がある、いる", category: "基本文", label: "文法", pattern: "There is + 単数 / There are + 複数", example: "There are two chairs in the room.", exampleJapanese: "部屋には椅子が二つあります。", note: "数によって is と are を使い分けます。" },
  { id: "g-012", level: "A1", term: "所有格", japanese: "誰のものかを表す", category: "基本文", label: "文法", pattern: "my / your / his / her / our / their + 名詞", example: "Her phone is on the table.", exampleJapanese: "彼女の電話はテーブルの上にあります。", note: "its は「それの」、it's は it is の短縮形です。" },
  { id: "g-013", level: "A1", term: "命令文", japanese: "指示・依頼を表す", category: "基本文", label: "文法", pattern: "動詞の原形 ... / Don't + 動詞", example: "Please open the window.", exampleJapanese: "窓を開けてください。", note: "主語を省き、動詞の原形で始めます。" },
  { id: "g-014", level: "A1", term: "疑問詞", japanese: "何、どこ、いつなどを尋ねる", category: "基本文", label: "文法", pattern: "What / Where / When / Why / How + ...?", example: "Where do you live?", exampleJapanese: "あなたはどこに住んでいますか。", note: "一般動詞の質問では疑問詞の後に do / does を置きます。" },
  { id: "g-015", level: "A1", term: "現在形の疑問・否定", japanese: "習慣について聞く、否定する", category: "基本文", label: "文法", pattern: "Do/Does + 主語 + 動詞? / don't / doesn't", example: "Does she work on Fridays?", exampleJapanese: "彼女は金曜日に働きますか。", note: "does の後ろは works ではなく、動詞の原形 work です。" },
  { id: "g-016", level: "A1", term: "所有の have", japanese: "持っていることを表す", category: "基本文", label: "文法", pattern: "have / has + 名詞", example: "He has a new bike.", exampleJapanese: "彼は新しい自転車を持っています。", note: "he / she / it では have が has になります。" },
  { id: "g-017", level: "A2", term: "some / any", japanese: "いくつか、少し", category: "名詞", label: "文法", pattern: "some: 肯定文 / any: 疑問文・否定文", example: "Do you have any questions?", exampleJapanese: "何か質問はありますか。", note: "依頼や申し出の質問では some を使うこともあります。" },
  { id: "g-018", level: "A2", term: "可算・不可算名詞", japanese: "数えられる名詞、数えられない名詞", category: "名詞", label: "文法", pattern: "many books / much water", example: "How much water do you need?", exampleJapanese: "どのくらい水が必要ですか。", note: "数えられない名詞には通常 a/an を付けません。" },
  { id: "g-019", level: "A2", term: "場所の前置詞", japanese: "場所の関係を表す", category: "前置詞", label: "文法", pattern: "in / on / at + 場所", example: "The keys are on the table.", exampleJapanese: "鍵はテーブルの上にあります。", note: "in は内部、on は表面、at は地点を表すのが基本です。" },
  { id: "g-020", level: "A2", term: "時の前置詞", japanese: "時を表す", category: "前置詞", label: "文法", pattern: "at + 時刻 / on + 曜日 / in + 月・年", example: "The class starts at 9 on Monday.", exampleJapanese: "授業は月曜日の9時に始まります。", note: "at, on, in を時の単位で使い分けます。" },
  { id: "g-021", level: "A2", term: "be going to", japanese: "予定・予測を表す", category: "時制", label: "文法", pattern: "be going to + 動詞の原形", example: "I'm going to call her tonight.", exampleJapanese: "私は今夜彼女に電話する予定です。", note: "主語に応じて be動詞を変えます。" },
  { id: "g-022", level: "A2", term: "過去進行形", japanese: "過去のある時点で進行中だったこと", category: "時制", label: "文法", pattern: "was / were + 動詞-ing", example: "I was cooking when you called.", exampleJapanese: "あなたが電話したとき、私は料理をしていました。", note: "進行中の出来事と短い出来事を組み合わせて使えます。" },
  { id: "g-023", level: "A2", term: "最上級", japanese: "最も〜だ", category: "比較", label: "文法", pattern: "the + 形容詞-est / the most + 形容詞", example: "This is the most interesting book.", exampleJapanese: "これは最も面白い本です。", note: "最上級の前には通常 the を置きます。" },
  { id: "g-024", level: "B1", term: "should / have to", japanese: "助言・必要を表す", category: "助動詞", label: "文法", pattern: "should + 動詞 / have to + 動詞", example: "You should get some rest.", exampleJapanese: "少し休んだほうがいいです。", note: "should は助言、have to は必要・義務を表します。" },
  { id: "g-025", level: "B1", term: "受動態", japanese: "行為を受ける側に注目する", category: "文のつながり", label: "文法", pattern: "be + 過去分詞", example: "The report was sent yesterday.", exampleJapanese: "報告書は昨日送られました。", note: "行為者が重要なら by + 行為者 を加えます。" },
  { id: "g-026", level: "B1", term: "現在完了と過去形", japanese: "経験・完了と完了した過去を区別する", category: "時制", label: "文法", pattern: "have + 過去分詞 / 過去形 + 過去の時点", example: "I've seen that film, but I saw it last year.", exampleJapanese: "その映画は見たことがありますが、見たのは去年です。", note: "last year のような完了した過去の時点とは現在完了を使いません。" },
  { id: "g-027", level: "B1", term: "第一条件文", japanese: "起こりうる未来の条件を表す", category: "文のつながり", label: "文法", pattern: "If + 現在形, will + 動詞", example: "If it rains, we'll stay inside.", exampleJapanese: "雨が降ったら、私たちは中にいます。", note: "if 節の中は未来のことでも通常 will を使いません。" },
  { id: "g-028", level: "B1", term: "第二条件文", japanese: "現実と異なる仮定を表す", category: "文のつながり", label: "文法", pattern: "If + 過去形, would + 動詞", example: "If I had more time, I would travel more.", exampleJapanese: "もっと時間があれば、もっと旅行するのに。", note: "現在・未来についての仮定でも if 節は過去形を使います。" },
  { id: "g-029", level: "B1", term: "間接疑問文", japanese: "丁寧に情報を尋ねる", category: "文のつながり", label: "文法", pattern: "Could you tell me + 疑問詞 + 主語 + 動詞?", example: "Could you tell me where the station is?", exampleJapanese: "駅がどこにあるか教えていただけますか。", note: "Could you tell me の後は通常の文の語順にします。" },
  { id: "g-030", level: "B1", term: "used to", japanese: "以前の習慣や状態を表す", category: "時制", label: "文法", pattern: "used to + 動詞の原形", example: "I used to live near the sea.", exampleJapanese: "私は以前、海の近くに住んでいました。", note: "今はそうではない過去の習慣・状態に使います。" }
];

export const EXTRA_INDONESIAN_TRANSLATIONS: Record<string, string> = {
  "w-031": "suka", "w-032": "tinggal; hidup", "w-033": "bekerja; pekerjaan", "w-034": "makan", "w-035": "minum; minuman", "w-036": "keluarga", "w-037": "teman", "w-038": "pagi", "w-039": "minggu", "w-040": "kecil", "w-041": "dekat", "w-042": "karena",
  "w-043": "rencana; merencanakan", "w-044": "mengundang", "w-045": "tiba", "w-046": "pergi; meninggalkan", "w-047": "meminjam", "w-048": "mengembalikan; kembali", "w-049": "pesan; mengirim pesan", "w-050": "tiket", "w-051": "masalah", "w-052": "solusi", "w-053": "setempat; lokal", "w-054": "ramai", "w-055": "mahal", "w-056": "cukup", "w-057": "sebagai gantinya", "w-058": "sudah", "w-059": "baru-baru ini", "w-060": "biasanya", "w-061": "selama", "w-062": "sebelum", "w-063": "setelah", "w-064": "bersama-sama",
  "w-065": "mencapai", "w-066": "menghindari", "w-067": "membandingkan", "w-068": "mempertimbangkan", "w-069": "bergantung pada", "w-070": "mengembangkan", "w-071": "berhasil; mengelola", "w-072": "mencegah", "w-073": "merekomendasikan", "w-074": "memerlukan", "w-075": "manfaat; bermanfaat", "w-076": "tantangan", "w-077": "pengalaman", "w-078": "tujuan", "w-079": "kebiasaan", "w-080": "masalah; isu", "w-081": "kemajuan", "w-082": "penelitian", "w-083": "bertanggung jawab", "w-084": "fleksibel", "w-085": "efektif", "w-086": "akrab dengan", "w-087": "kemungkinan besar", "w-088": "khusus; spesifik", "w-089": "berkomunikasi", "w-090": "lingkungan",
  "p-011": "... di mana?", "p-012": "Bolehkah saya minta ...?", "p-013": "Maaf.", "p-014": "Sampai nanti.", "p-015": "Saya suka ... .", "p-016": "Berapa lama waktu yang dibutuhkan?", "p-017": "Bolehkah saya mencoba ini?", "p-018": "Saya sedang mencari ... .", "p-019": "Apa yang terjadi?", "p-020": "Saya tidak yakin.", "p-021": "Tergantung.", "p-022": "Apakah Anda ingin ...?",
  "p-023": "Bisakah Anda memberi tahu saya ...?", "p-024": "Saya setuju dengan Anda.", "p-025": "Maaf, tetapi ... .", "p-026": "Alasannya adalah ... .", "p-027": "Sejauh yang saya tahu, ... .", "p-028": "Saya merekomendasikan ... .", "p-029": "Apakah mungkin untuk ...?", "p-030": "Saya ingin menanyakan apakah ... .",
  "g-010": "menunjukkan apakah kata benda bersifat umum atau tertentu", "g-011": "menyatakan ada atau terdapat", "g-012": "menunjukkan kepemilikan", "g-013": "menyatakan perintah atau permintaan", "g-014": "menanyakan apa, di mana, kapan, dan sebagainya", "g-015": "menanyakan atau menolak kebiasaan", "g-016": "menyatakan kepemilikan",
  "g-017": "beberapa; sedikit", "g-018": "kata benda yang dapat dan tidak dapat dihitung", "g-019": "menyatakan hubungan tempat", "g-020": "menyatakan waktu", "g-021": "menyatakan rencana atau prediksi", "g-022": "kejadian yang sedang berlangsung di masa lalu", "g-023": "paling ...",
  "g-024": "menyatakan saran atau keharusan", "g-025": "berfokus pada pihak yang menerima tindakan", "g-026": "membedakan pengalaman dengan masa lalu yang selesai", "g-027": "menyatakan kondisi masa depan yang mungkin terjadi", "g-028": "menyatakan pengandaian yang tidak nyata", "g-029": "bertanya dengan lebih sopan", "g-030": "menyatakan kebiasaan atau keadaan di masa lalu"
};

export const EXTRA_SECOND_WORD_EXAMPLES: Record<string, ExpandedExamplePair> = {
  "w-031": { english: "Do you like cooking?", japanese: "あなたは料理が好きですか。" },
  "w-032": { english: "I want to live abroad someday.", japanese: "私はいつか海外に住みたいです。" },
  "w-033": { english: "I have a lot of work today.", japanese: "私は今日、仕事がたくさんあります。" },
  "w-034": { english: "What do you want to eat?", japanese: "何を食べたいですか。" },
  "w-035": { english: "Would you like a cold drink?", japanese: "冷たい飲み物はいかがですか。" },
  "w-036": { english: "I have a large family.", japanese: "私は大家族です。" },
  "w-037": { english: "I met a new friend at school.", japanese: "私は学校で新しい友だちに会いました。" },
  "w-038": { english: "Good morning, everyone.", japanese: "みなさん、おはようございます。" },
  "w-039": { english: "I work five days a week.", japanese: "私は週に5日働きます。" },
  "w-040": { english: "Could I have a small coffee?", japanese: "小さいコーヒーをいただけますか。" },
  "w-041": { english: "Is there a restaurant near here?", japanese: "この近くにレストランはありますか。" },
  "w-042": { english: "She is happy because she passed the test.", japanese: "彼女は試験に合格したのでうれしいです。" },
  "w-043": { english: "What's your plan for the weekend?", japanese: "週末の予定は何ですか。" },
  "w-044": { english: "I'd like to invite my friends.", japanese: "友人たちを招待したいです。" },
  "w-045": { english: "Please arrive at the airport early.", japanese: "空港には早めに到着してください。" },
  "w-046": { english: "Please don't leave your bag here.", japanese: "ここにバッグを置いたままにしないでください。" },
  "w-047": { english: "I borrowed a book from the library.", japanese: "私は図書館から本を借りました。" },
  "w-048": { english: "We returned home after dinner.", japanese: "私たちは夕食後に家へ戻りました。" },
  "w-049": { english: "Please message me when you arrive.", japanese: "到着したら私にメッセージしてください。" },
  "w-050": { english: "Do you have your ticket with you?", japanese: "チケットを持っていますか。" },
  "w-051": { english: "Can you help me solve this problem?", japanese: "この問題を解決するのを手伝ってもらえますか。" },
  "w-052": { english: "This is a simple solution.", japanese: "これは簡単な解決策です。" },
  "w-053": { english: "Ask a local person for directions.", japanese: "地元の人に道を尋ねてください。" },
  "w-054": { english: "This beach gets crowded in summer.", japanese: "このビーチは夏に混みます。" },
  "w-055": { english: "Eating out can be expensive.", japanese: "外食は高くなることがあります。" },
  "w-056": { english: "Is the room warm enough?", japanese: "部屋は十分暖かいですか。" },
  "w-057": { english: "I had tea instead.", japanese: "私は代わりにお茶にしました。" },
  "w-058": { english: "Are you already here?", japanese: "もうここにいるのですか。" },
  "w-059": { english: "Have you seen her recently?", japanese: "最近、彼女に会いましたか。" },
  "w-060": { english: "What time do you usually get up?", japanese: "普段は何時に起きますか。" },
  "w-061": { english: "It rained during the night.", japanese: "夜の間に雨が降りました。" },
  "w-062": { english: "I've seen this film before.", japanese: "私は以前この映画を見たことがあります。" },
  "w-063": { english: "He went home after finishing work.", japanese: "彼は仕事を終えた後、家に帰りました。" },
  "w-064": { english: "Let's take a photo together.", japanese: "一緒に写真を撮りましょう。" },
  "w-065": { english: "You can achieve a lot with practice.", japanese: "練習すれば多くのことを達成できます。" },
  "w-066": { english: "He avoids driving at night.", japanese: "彼は夜に運転するのを避けます。" },
  "w-067": { english: "Don't compare yourself with others.", japanese: "自分を他人と比べないでください。" },
  "w-068": { english: "Please consider all the options.", japanese: "すべての選択肢を検討してください。" },
  "w-069": { english: "The price depends on how many people come.", japanese: "料金は何人来るかによって決まります。" },
  "w-070": { english: "The company developed a new app.", japanese: "その会社は新しいアプリを開発しました。" },
  "w-071": { english: "Can you manage this project?", japanese: "このプロジェクトを管理できますか。" },
  "w-072": { english: "This rule prevents people from parking here.", japanese: "この規則は人々がここに駐車するのを防ぎます。" },
  "w-073": { english: "Which book would you recommend?", japanese: "どの本をおすすめしますか。" },
  "w-074": { english: "The form requires you to enter your address.", japanese: "そのフォームには住所を入力する必要があります。" },
  "w-075": { english: "Students benefit from feedback.", japanese: "学生はフィードバックから利益を得ます。" },
  "w-076": { english: "This task will challenge you.", japanese: "この課題はあなたにとって挑戦になります。" },
  "w-077": { english: "Traveling abroad was a valuable experience.", japanese: "海外旅行は貴重な経験でした。" },
  "w-078": { english: "Set a small goal for this week.", japanese: "今週の小さな目標を立てましょう。" },
  "w-079": { english: "It takes time to build a new habit.", japanese: "新しい習慣を身につけるには時間がかかります。" },
  "w-080": { english: "There was an issue with the payment.", japanese: "支払いに問題がありました。" },
  "w-081": { english: "It takes time to see progress.", japanese: "進歩を実感するには時間がかかります。" },
  "w-082": { english: "I did some research before I bought it.", japanese: "私はそれを買う前に少し調べました。" },
  "w-083": { english: "Who is responsible for checking the report?", japanese: "報告書の確認を担当しているのは誰ですか。" },
  "w-084": { english: "We need a flexible plan.", japanese: "私たちには柔軟な計画が必要です。" },
  "w-085": { english: "Regular review is more effective than cramming.", japanese: "定期的な復習は詰め込み学習より効果的です。" },
  "w-086": { english: "The song sounds familiar to me.", japanese: "その歌は私には聞き覚えがあります。" },
  "w-087": { english: "She is likely to arrive late.", japanese: "彼女は遅れて到着しそうです。" },
  "w-088": { english: "We need specific information.", japanese: "私たちには具体的な情報が必要です。" },
  "w-089": { english: "We communicated by email.", japanese: "私たちはメールで連絡を取りました。" },
  "w-090": { english: "A quiet environment helps me focus.", japanese: "静かな環境は私が集中するのに役立ちます。" }
};
