import type { ExpandedExamplePair, ExpandedStudyItem } from "./expanded-study-data";

export const FURTHER_WORDS: ExpandedStudyItem[] = [
  { id: "w-151", level: "A1", term: "ask", japanese: "たずねる、頼む", category: "会話", label: "動詞", pronunciation: "/æsk/", example: "Can I ask a question?", exampleJapanese: "質問してもいいですか。", note: "ask + 人 + 質問 / ask 人 for + 物 の形で使えます。" },
  { id: "w-152", level: "A1", term: "answer", japanese: "答える、答え", category: "会話", label: "動詞/名詞", pronunciation: "/ˈænsər/", example: "Please answer this question.", exampleJapanese: "この質問に答えてください。", note: "answer の後ろには通常 to を置かず、answer a question と言います。" },
  { id: "w-153", level: "A1", term: "bring", japanese: "持ってくる", category: "日常", label: "動詞", pronunciation: "/brɪŋ/", example: "Please bring your passport.", exampleJapanese: "パスポートを持ってきてください。", note: "話し手や目的地の方へ物を持っていくときに使います。" },
  { id: "w-154", level: "A1", term: "carry", japanese: "運ぶ、持ち歩く", category: "移動", label: "動詞", pronunciation: "/ˈkæri/", example: "She carries a small bag.", exampleJapanese: "彼女は小さなバッグを持ち歩いています。", note: "手に持つ、身につけて運ぶ、どちらにも使えます。" },
  { id: "w-155", level: "A1", term: "clean", japanese: "きれいな、掃除する", category: "日常", label: "形容詞/動詞", pronunciation: "/kliːn/", example: "Please clean the table.", exampleJapanese: "テーブルをきれいにしてください。", note: "形容詞では「清潔な」、動詞では「掃除する」を表します。" },
  { id: "w-156", level: "A1", term: "cook", japanese: "料理する、料理人", category: "日常", label: "動詞/名詞", pronunciation: "/kʊk/", example: "I cook dinner every day.", exampleJapanese: "私は毎日夕食を作ります。", note: "cook + 食べ物 で料理する物を表せます。" },
  { id: "w-157", level: "A1", term: "dance", japanese: "踊る、ダンス", category: "日常", label: "動詞/名詞", pronunciation: "/dæns/", example: "They dance after dinner.", exampleJapanese: "彼らは夕食後に踊ります。", note: "動詞と名詞の両方で使えます。" },
  { id: "w-158", level: "A1", term: "draw", japanese: "描く", category: "仕事・学習", label: "動詞", pronunciation: "/drɔː/", example: "The child can draw a cat.", exampleJapanese: "その子どもは猫を描けます。", note: "draw a picture のように、絵を描くときに使います。" },
  { id: "w-159", level: "A1", term: "enjoy", japanese: "楽しむ", category: "感情・状態", label: "動詞", pronunciation: "/ɪnˈdʒɔɪ/", example: "I enjoy this class.", exampleJapanese: "私はこの授業を楽しんでいます。", note: "enjoy の後ろには名詞か -ing 形を置きます。" },
  { id: "w-160", level: "A1", term: "help", japanese: "助ける、助け", category: "人", label: "動詞/名詞", pronunciation: "/help/", example: "Can you help me?", exampleJapanese: "手伝ってもらえますか。", note: "help + 人 + (to) + 動詞 の形で、人が何かするのを助けることを表せます。" },
  { id: "w-161", level: "A1", term: "hungry", japanese: "お腹がすいた", category: "感情・状態", label: "形容詞", pronunciation: "/ˈhʌŋɡri/", example: "I'm hungry after work.", exampleJapanese: "仕事の後はお腹がすいています。", note: "be hungry で「お腹がすいている」。" },
  { id: "w-162", level: "A1", term: "thirsty", japanese: "のどが渇いた", category: "感情・状態", label: "形容詞", pronunciation: "/ˈθɜːrsti/", example: "Are you thirsty?", exampleJapanese: "のどが渇いていますか。", note: "be thirsty で「のどが渇いている」。" },
  { id: "w-163", level: "A1", term: "tired", japanese: "疲れた", category: "感情・状態", label: "形容詞", pronunciation: "/ˈtaɪərd/", example: "I'm tired today.", exampleJapanese: "私は今日疲れています。", note: "tired は人の感じ方、tiring は物事が人を疲れさせる性質を表します。" },
  { id: "w-164", level: "A1", term: "evening", japanese: "夕方、晩", category: "時間", label: "名詞", pronunciation: "/ˈiːvnɪŋ/", example: "Good evening, everyone.", exampleJapanese: "皆さん、こんばんは。", note: "in the evening で「夕方に・夜に」。" },
  { id: "w-165", level: "A1", term: "weekend", japanese: "週末", category: "時間", label: "名詞", pronunciation: "/ˈwiːkend/", example: "We visit our family on weekends.", exampleJapanese: "私たちは週末に家族を訪ねます。", note: "at the weekend も on the weekend も使われます。" },
  { id: "w-166", level: "A1", term: "weather", japanese: "天気", category: "日常", label: "名詞", pronunciation: "/ˈweðər/", example: "The weather is nice today.", exampleJapanese: "今日は天気が良いです。", note: "weather は通常数えない名詞です。" },
  { id: "w-167", level: "A1", term: "breakfast", japanese: "朝食", category: "日常", label: "名詞", pronunciation: "/ˈbrekfəst/", example: "I have breakfast at seven.", exampleJapanese: "私は7時に朝食をとります。", note: "have breakfast で「朝食をとる」。" },
  { id: "w-168", level: "A1", term: "lunch", japanese: "昼食", category: "日常", label: "名詞", pronunciation: "/lʌntʃ/", example: "Let's have lunch together.", exampleJapanese: "一緒に昼食をとりましょう。", note: "have lunch で「昼食をとる」。" },
  { id: "w-169", level: "A1", term: "dinner", japanese: "夕食", category: "日常", label: "名詞", pronunciation: "/ˈdɪnər/", example: "Dinner is ready.", exampleJapanese: "夕食の準備ができました。", note: "have dinner で「夕食をとる」。" },
  { id: "w-170", level: "A1", term: "home", japanese: "家、家へ、家で", category: "日常", label: "名詞/副詞", pronunciation: "/hoʊm/", example: "I go home at five.", exampleJapanese: "私は5時に家へ帰ります。", note: "go home の home は副詞なので、通常 to を付けません。" },

  { id: "w-171", level: "A2", term: "advice", japanese: "助言、アドバイス", category: "仕事・学習", label: "名詞", pronunciation: "/ədˈvaɪs/", example: "Can you give me some advice?", exampleJapanese: "アドバイスをいただけますか。", note: "advice は数えない名詞です。an advice ではなく some advice と言います。" },
  { id: "w-172", level: "A2", term: "allow", japanese: "許可する", category: "日常", label: "動詞", pronunciation: "/əˈlaʊ/", example: "My parents allow me to use their car.", exampleJapanese: "両親は私に車を使うことを許可しています。", note: "allow + 人 + to + 動詞 の形で使えます。" },
  { id: "w-173", level: "A2", term: "appointment", japanese: "予約、約束", category: "日常", label: "名詞", pronunciation: "/əˈpɔɪntmənt/", example: "I have a dentist's appointment on Tuesday.", exampleJapanese: "私は火曜日に歯医者の予約があります。", note: "have an appointment with + 人 で「人と予約がある」。" },
  { id: "w-174", level: "A2", term: "careful", japanese: "注意深い、気をつけて", category: "感情・状態", label: "形容詞", pronunciation: "/ˈkerfəl/", example: "Be careful with that glass.", exampleJapanese: "そのグラスには気をつけてください。", note: "be careful with + 物、be careful when + 文 の形を使えます。" },
  { id: "w-175", level: "A2", term: "change", japanese: "変える、変化", category: "日常", label: "動詞/名詞", pronunciation: "/tʃeɪndʒ/", example: "I need to change my address.", exampleJapanese: "住所を変更する必要があります。", note: "change + 物 で「物を変える」、change from A to B で変化を表せます。" },
  { id: "w-176", level: "A2", term: "contact", japanese: "連絡する、連絡先", category: "会話", label: "動詞/名詞", pronunciation: "/ˈkɑːntækt/", example: "Please contact me by email.", exampleJapanese: "メールで私に連絡してください。", note: "contact + 人 の形で、contact の後ろに with は通常置きません。" },
  { id: "w-177", level: "A2", term: "correct", japanese: "正しい", category: "仕事・学習", label: "形容詞", pronunciation: "/kəˈrekt/", example: "Is this address correct?", exampleJapanese: "この住所は正しいですか。", note: "correct answer のように、正しい情報や答えを表します。" },
  { id: "w-178", level: "A2", term: "delay", japanese: "遅れ、遅らせる", category: "移動", label: "名詞/動詞", pronunciation: "/dɪˈleɪ/", example: "The train is delayed.", exampleJapanese: "電車が遅れています。", note: "be delayed で「遅れている」、a delay で「遅れ」を表します。" },
  { id: "w-179", level: "A2", term: "directions", japanese: "道順、行き方", category: "移動", label: "名詞", pronunciation: "/dəˈrekʃənz/", example: "Could you give me directions to the museum?", exampleJapanese: "博物館までの道を教えていただけますか。", note: "道順の意味では directions と複数形で使うことが多いです。" },
  { id: "w-180", level: "A2", term: "follow", japanese: "ついて行く、従う", category: "移動", label: "動詞", pronunciation: "/ˈfɑːloʊ/", example: "Follow this road to the bridge.", exampleJapanese: "この道を橋まで進んでください。", note: "follow + 人・道・指示 の形で使えます。" },
  { id: "w-181", level: "A2", term: "happen", japanese: "起こる", category: "日常", label: "動詞", pronunciation: "/ˈhæpən/", example: "What happened after the meeting?", exampleJapanese: "会議の後に何が起きましたか。", note: "happen to + 人・物 で「〜に起こる」を表せます。" },
  { id: "w-182", level: "A2", term: "offer", japanese: "申し出る、申し出", category: "会話", label: "動詞/名詞", pronunciation: "/ˈɔːfər/", example: "Can I offer you some coffee?", exampleJapanese: "コーヒーをお出ししましょうか。", note: "offer + 人 + 物 / offer to + 動詞 の形を使えます。" },
  { id: "w-183", level: "A2", term: "promise", japanese: "約束する、約束", category: "会話", label: "動詞/名詞", pronunciation: "/ˈprɑːmɪs/", example: "I promise to call you tonight.", exampleJapanese: "今夜電話すると約束します。", note: "promise to + 動詞 で「〜すると約束する」。" },
  { id: "w-184", level: "A2", term: "receive", japanese: "受け取る", category: "日常", label: "動詞", pronunciation: "/rɪˈsiːv/", example: "Did you receive my email?", exampleJapanese: "私のメールを受け取りましたか。", note: "receive は少し改まった「受け取る」で、get より事務的な場面にも合います。" },
  { id: "w-185", level: "A2", term: "simple", japanese: "簡単な、単純な", category: "感情・状態", label: "形容詞", pronunciation: "/ˈsɪmpəl/", example: "The instructions are simple.", exampleJapanese: "説明は簡単です。", note: "simple は仕組みや説明が複雑でないことを表します。" },
  { id: "w-186", level: "A2", term: "special", japanese: "特別な", category: "日常", label: "形容詞", pronunciation: "/ˈspeʃəl/", example: "Today is a special day.", exampleJapanese: "今日は特別な日です。", note: "special for + 人 の形で「人にとって特別な」と表せます。" },
  { id: "w-187", level: "A2", term: "straight", japanese: "まっすぐに、まっすぐな", category: "移動", label: "副詞/形容詞", pronunciation: "/streɪt/", example: "Go straight for two blocks.", exampleJapanese: "二つ先の区画までまっすぐ行ってください。", note: "道順では go straight がよく使われます。" },
  { id: "w-188", level: "A2", term: "traffic", japanese: "交通、交通量", category: "移動", label: "名詞", pronunciation: "/ˈtræfɪk/", example: "There is a lot of traffic this morning.", exampleJapanese: "今朝は交通量が多いです。", note: "traffic は通常数えない名詞です。" },
  { id: "w-189", level: "A2", term: "visitor", japanese: "訪問者、観光客", category: "人", label: "名詞", pronunciation: "/ˈvɪzɪtər/", example: "The museum has many visitors today.", exampleJapanese: "その博物館には今日多くの来館者がいます。", note: "visit する人を visitor と言います。" },
  { id: "w-190", level: "A2", term: "worry", japanese: "心配する、心配", category: "感情・状態", label: "動詞/名詞", pronunciation: "/ˈwɜːri/", example: "Don't worry about the time.", exampleJapanese: "時間のことは心配しないでください。", note: "worry about + 名詞・-ing で「〜を心配する」。" },

  { id: "w-191", level: "B1", term: "arrange", japanese: "手配する、取り決める", category: "仕事・学習", label: "動詞", pronunciation: "/əˈreɪndʒ/", example: "We arranged a meeting for Friday.", exampleJapanese: "私たちは金曜日に会議を設定しました。", note: "arrange + 名詞 / arrange to + 動詞 の形で使えます。" },
  { id: "w-192", level: "B1", term: "complain", japanese: "不満を言う、苦情を言う", category: "会話", label: "動詞", pronunciation: "/kəmˈpleɪn/", example: "He complained about the noise.", exampleJapanese: "彼は騒音について不満を言いました。", note: "complain about + 問題、complain to + 人 の形を使います。" },
  { id: "w-193", level: "B1", term: "compete", japanese: "競争する", category: "仕事・学習", label: "動詞", pronunciation: "/kəmˈpiːt/", example: "Three teams will compete in the final.", exampleJapanese: "3チームが決勝で競います。", note: "compete in + 大会、compete with / against + 相手 の形を使えます。" },
  { id: "w-194", level: "B1", term: "concentrate", japanese: "集中する", category: "仕事・学習", label: "動詞", pronunciation: "/ˈkɑːnsəntreɪt/", example: "I can't concentrate in a noisy room.", exampleJapanese: "私は騒がしい部屋では集中できません。", note: "concentrate on + 名詞・-ing で「〜に集中する」。" },
  { id: "w-195", level: "B1", term: "confirm", japanese: "確認する、確定する", category: "仕事・学習", label: "動詞", pronunciation: "/kənˈfɜːrm/", example: "Please confirm your booking by email.", exampleJapanese: "メールで予約を確認してください。", note: "confirm + 名詞 で情報や予定を確認・確定します。" },
  { id: "w-196", level: "B1", term: "connect", japanese: "つなぐ、接続する", category: "日常", label: "動詞", pronunciation: "/kəˈnekt/", example: "Connect the printer to your computer.", exampleJapanese: "プリンターをコンピューターにつないでください。", note: "connect A to B で「AをBにつなぐ」。" },
  { id: "w-197", level: "B1", term: "contain", japanese: "含む", category: "仕事・学習", label: "動詞", pronunciation: "/kənˈteɪn/", example: "This report contains useful information.", exampleJapanese: "この報告書には役立つ情報が含まれています。", note: "contain + 内容物 で「〜を含む」。" },
  { id: "w-198", level: "B1", term: "control", japanese: "管理する、制御する", category: "仕事・学習", label: "動詞/名詞", pronunciation: "/kənˈtroʊl/", example: "You can control the temperature here.", exampleJapanese: "ここでは温度を調整できます。", note: "control + 名詞 で、状態や動きを管理・制御することを表します。" },
  { id: "w-199", level: "B1", term: "convince", japanese: "納得させる", category: "会話", label: "動詞", pronunciation: "/kənˈvɪns/", example: "She convinced me to try it.", exampleJapanese: "彼女は私を説得して、それを試させました。", note: "convince + 人 + to + 動詞 で「人を説得して〜させる」。" },
  { id: "w-200", level: "B1", term: "create", japanese: "作り出す、作成する", category: "仕事・学習", label: "動詞", pronunciation: "/kriˈeɪt/", example: "They created a new website.", exampleJapanese: "彼らは新しいウェブサイトを作成しました。", note: "create は新しい物・状況を作り出すときに使います。" },
  { id: "w-201", level: "B1", term: "deal", japanese: "対応する、扱う", category: "仕事・学習", label: "動詞", pronunciation: "/diːl/", example: "We need to deal with this problem now.", exampleJapanese: "私たちは今、この問題に対処する必要があります。", note: "deal with + 問題・状況 で「〜に対処する」。" },
  { id: "w-202", level: "B1", term: "demand", japanese: "要求する、需要", category: "仕事・学習", label: "動詞/名詞", pronunciation: "/dɪˈmænd/", example: "This job demands a lot of patience.", exampleJapanese: "この仕事には多くの忍耐が求められます。", note: "demand + 名詞 で、必要とされることを表せます。" },
  { id: "w-203", level: "B1", term: "focus", japanese: "集中する、焦点", category: "仕事・学習", label: "動詞/名詞", pronunciation: "/ˈfoʊkəs/", example: "Let's focus on the main idea.", exampleJapanese: "主な考えに集中しましょう。", note: "focus on + 名詞・-ing で「〜に焦点を当てる」。" },
  { id: "w-204", level: "B1", term: "include", japanese: "含む", category: "仕事・学習", label: "動詞", pronunciation: "/ɪnˈkluːd/", example: "The price includes breakfast.", exampleJapanese: "料金には朝食が含まれています。", note: "include + 内容 を使い、contain より「一部として含める」意味でよく使います。" },
  { id: "w-205", level: "B1", term: "involve", japanese: "含む、伴う、関わらせる", category: "仕事・学習", label: "動詞", pronunciation: "/ɪnˈvɑːlv/", example: "The job involves meeting new people.", exampleJapanese: "その仕事には新しい人と会うことが含まれます。", note: "involve + 名詞・-ing で、必要な活動や要素を表します。" },
  { id: "w-206", level: "B1", term: "limit", japanese: "制限する、限度", category: "仕事・学習", label: "動詞/名詞", pronunciation: "/ˈlɪmɪt/", example: "We need to limit our spending.", exampleJapanese: "私たちは支出を制限する必要があります。", note: "limit + 名詞 で量や範囲を制限します。" },
  { id: "w-207", level: "B1", term: "purpose", japanese: "目的", category: "仕事・学習", label: "名詞", pronunciation: "/ˈpɜːrpəs/", example: "What is the purpose of this meeting?", exampleJapanese: "この会議の目的は何ですか。", note: "the purpose of + 名詞・-ing で「〜の目的」。" },
  { id: "w-208", level: "B1", term: "relate", japanese: "関連がある、結びつける", category: "仕事・学習", label: "動詞", pronunciation: "/rɪˈleɪt/", example: "This example relates to our topic.", exampleJapanese: "この例は私たちの話題に関連しています。", note: "relate to + 名詞 で「〜に関連する」。" },
  { id: "w-209", level: "B1", term: "result", japanese: "結果、結果として生じる", category: "仕事・学習", label: "名詞/動詞", pronunciation: "/rɪˈzʌlt/", example: "The results were better than expected.", exampleJapanese: "結果は予想より良かったです。", note: "result in + 名詞 で「〜という結果になる」。" },
  { id: "w-210", level: "B1", term: "suitable", japanese: "適した、ふさわしい", category: "感情・状態", label: "形容詞", pronunciation: "/ˈsuːtəbəl/", example: "This course is suitable for beginners.", exampleJapanese: "このコースは初心者に適しています。", note: "be suitable for + 人・目的 で「〜に適している」。" }
];

export const FURTHER_PHRASES: ExpandedStudyItem[] = [
  { id: "p-046", level: "A1", term: "Can I ...?", japanese: "〜してもいいですか。", category: "お願い", label: "定型表現", example: "Can I sit here?", exampleJapanese: "ここに座ってもいいですか。", note: "許可を求める基本表現です。後ろには動詞の原形を置きます。" },
  { id: "p-047", level: "A1", term: "Here you are.", japanese: "はい、どうぞ。", category: "日常", label: "定型表現", example: "Here you are. This is your key.", exampleJapanese: "はい、どうぞ。こちらがあなたの鍵です。", note: "相手に物を渡すときに使います。" },
  { id: "p-048", level: "A1", term: "I'm sorry.", japanese: "すみません。ごめんなさい。", category: "会話", label: "定型表現", example: "I'm sorry. I'm late.", exampleJapanese: "すみません。遅れました。", note: "軽い謝罪や、相手の注意を引くときにも使えます。" },
  { id: "p-049", level: "A1", term: "What time is ...?", japanese: "〜は何時ですか。", category: "時間", label: "定型表現", example: "What time is the next bus?", exampleJapanese: "次のバスは何時ですか。", note: "時刻をたずねるときに使います。" },
  { id: "p-050", level: "A1", term: "See you tomorrow.", japanese: "また明日。", category: "あいさつ", label: "定型表現", example: "Thanks for today. See you tomorrow.", exampleJapanese: "今日はありがとう。また明日。", note: "別れ際のカジュアルなあいさつです。" },

  { id: "p-051", level: "A2", term: "Could I have ...?", japanese: "〜をいただけますか。", category: "買い物", label: "定型表現", example: "Could I have the bill, please?", exampleJapanese: "お会計をお願いできますか。", note: "店やレストランで丁寧に物を頼む表現です。" },
  { id: "p-052", level: "A2", term: "I'm afraid ... .", japanese: "残念ですが、〜です。", category: "会話", label: "定型表現", example: "I'm afraid I can't come tonight.", exampleJapanese: "残念ですが、今夜は行けません。", note: "断りや悪い知らせをやわらかく伝える表現です。" },
  { id: "p-053", level: "A2", term: "How about ...?", japanese: "〜はいかがですか。", category: "会話", label: "定型表現", example: "How about meeting at six?", exampleJapanese: "6時に会うのはいかがですか。", note: "提案では後ろに名詞か -ing 形を置けます。" },
  { id: "p-054", level: "A2", term: "It doesn't matter.", japanese: "気にしなくて大丈夫です。", category: "会話", label: "定型表現", example: "Sorry I'm late. - It doesn't matter.", exampleJapanese: "遅れてごめんなさい。- 気にしなくて大丈夫です。", note: "小さな問題を気にしなくてよいと伝える表現です。" },
  { id: "p-055", level: "A2", term: "I'll be back in ... .", japanese: "〜後に戻ります。", category: "日常", label: "定型表現", example: "I'll be back in ten minutes.", exampleJapanese: "10分後に戻ります。", note: "in + 時間 で、今からどのくらい後かを表します。" },

  { id: "p-056", level: "B1", term: "Would it be possible to ...?", japanese: "〜することは可能でしょうか。", category: "お願い", label: "定型表現", example: "Would it be possible to change the time?", exampleJapanese: "時間を変更することは可能でしょうか。", note: "丁寧に可能かどうかをたずねる表現です。後ろには動詞の原形を置きます。" },
  { id: "p-057", level: "B1", term: "I'm not used to ... .", japanese: "〜に慣れていません。", category: "会話", label: "定型表現", example: "I'm not used to speaking in public.", exampleJapanese: "私は人前で話すことに慣れていません。", note: "to は前置詞なので、後ろには名詞か -ing 形を置きます。" },
  { id: "p-058", level: "B1", term: "As far as I'm concerned, ...", japanese: "私としては、〜です。", category: "意見", label: "定型表現", example: "As far as I'm concerned, the plan is realistic.", exampleJapanese: "私としては、その計画は現実的です。", note: "自分の立場からの意見を述べるときの表現です。" },
  { id: "p-059", level: "B1", term: "The point is ... .", japanese: "大事な点は、〜です。", category: "意見", label: "定型表現", example: "The point is that we need more time.", exampleJapanese: "大事な点は、私たちにはもっと時間が必要だということです。", note: "the point is that + 文 で中心となる論点を示せます。" },
  { id: "p-060", level: "B1", term: "I didn't mean to ... .", japanese: "〜するつもりではありませんでした。", category: "会話", label: "定型表現", example: "I didn't mean to upset you.", exampleJapanese: "あなたを嫌な気持ちにさせるつもりではありませんでした。", note: "意図せず相手を困らせたときなどに使います。" }
];

export const FURTHER_GRAMMAR: ExpandedStudyItem[] = [
  { id: "g-046", level: "A1", term: "目的格", japanese: "動作を受ける人・物を表す", category: "基本文", label: "文法", pattern: "me / you / him / her / us / them", example: "She called me after work.", exampleJapanese: "彼女は仕事の後に私へ電話しました。", note: "動詞や前置詞の後ろには I ではなく me のような目的格を置きます。" },
  { id: "g-047", level: "A1", term: "名詞の所有格 's", japanese: "誰の物かを名詞で表す", category: "名詞", label: "文法", pattern: "Tom's bag / my parents' house", example: "This is my sister's phone.", exampleJapanese: "これは私の姉の電話です。", note: "単数名詞には 's、複数の -s で終わる名詞には ' を付けます。" },
  { id: "g-048", level: "A1", term: "be動詞の短縮形", japanese: "会話で短く言う", category: "基本文", label: "文法", pattern: "I'm / you're / he's / we're / they're", example: "We're ready to go.", exampleJapanese: "私たちは出発の準備ができています。", note: "会話やカジュアルな文章でよく使われます。肯定の短縮形を自然に覚えましょう。" },
  { id: "g-049", level: "A1", term: "場所の位置関係", japanese: "物の位置を詳しく伝える", category: "前置詞", label: "文法", pattern: "under / next to / between + 名詞", example: "The cafe is next to the bank.", exampleJapanese: "そのカフェは銀行の隣にあります。", note: "under は下、next to はすぐ隣、between は二つの物の間を表します。" },
  { id: "g-050", level: "A1", term: "Let's + 動詞", japanese: "一緒にすることを提案する", category: "基本文", label: "文法", pattern: "Let's + 動詞の原形", example: "Let's take a break.", exampleJapanese: "休憩しましょう。", note: "Let's not + 動詞 で「〜しないようにしよう」と否定の提案もできます。" },

  { id: "g-051", level: "A2", term: "未来の予定を表す現在進行形", japanese: "決まっている予定を表す", category: "時制", label: "文法", pattern: "be + 動詞-ing + 未来の時", example: "I'm meeting my friend tomorrow.", exampleJapanese: "私は明日友人に会う予定です。", note: "すでに決まった予定には現在進行形を使えます。" },
  { id: "g-052", level: "A2", term: "as ... as", japanese: "同じ程度であることを表す", category: "比較", label: "文法", pattern: "as + 形容詞・副詞 + as", example: "This bag is as light as that one.", exampleJapanese: "このバッグはあのバッグと同じくらい軽いです。", note: "否定では not as / so + 形容詞 + as を使えます。" },
  { id: "g-053", level: "A2", term: "現在完了 just / already / yet", japanese: "完了や未完了を表す", category: "時制", label: "文法", pattern: "have + just/already + 過去分詞 / haven't + 過去分詞 + yet", example: "I've just finished my work.", exampleJapanese: "私はちょうど仕事を終えたところです。", note: "just と already は通常 have の後、yet は疑問文・否定文の文末に置きます。" },
  { id: "g-054", level: "A2", term: "too much / too many", japanese: "多すぎることを表す", category: "名詞", label: "文法", pattern: "too much + 不可算名詞 / too many + 複数名詞", example: "There are too many cars on this road.", exampleJapanese: "この道には車が多すぎます。", note: "much は数えられない名詞、many は複数の数えられる名詞に使います。" },
  { id: "g-055", level: "A2", term: "不定詞で目的を表す", japanese: "何のためにするかを表す", category: "動詞の形", label: "文法", pattern: "to + 動詞の原形", example: "I went to the store to buy milk.", exampleJapanese: "私は牛乳を買うために店へ行きました。", note: "to + 動詞で、行動の目的を短く表せます。" },

  { id: "g-056", level: "B1", term: "stop to do / stop doing", japanese: "行動を止める、〜するために立ち止まる", category: "動詞の形", label: "文法", pattern: "stop doing / stop to do", example: "We stopped to have lunch.", exampleJapanese: "私たちは昼食をとるために立ち止まりました。", note: "stop doing は「その行動をやめる」、stop to do は「別の目的のためにいったん止まる」です。" },
  { id: "g-057", level: "B1", term: "so / such ... that", japanese: "結果を伴うほどの程度を表す", category: "文のつながり", label: "文法", pattern: "so + 形容詞 + that / such + 名詞 + that", example: "It was so crowded that we left early.", exampleJapanese: "とても混んでいたので、私たちは早く帰りました。", note: "so の後ろには形容詞・副詞、such の後ろには名詞を置きます。" },
  { id: "g-058", level: "B1", term: "however / therefore", japanese: "対照・結果をつなぐ", category: "文のつながり", label: "文法", pattern: "文. However, 文. / 文. Therefore, 文.", example: "The weather was bad. However, the event continued.", exampleJapanese: "天気は悪かったです。しかし、イベントは続きました。", note: "however は対照、therefore は結果を表します。文章では前後を区切って使います。" },
  { id: "g-059", level: "B1", term: "-ed / -ing 形容詞", japanese: "感じる人と、感じさせる物事を区別する", category: "形容詞", label: "文法", pattern: "interested / interesting", example: "I was interested in the interesting talk.", exampleJapanese: "私はその興味深い話に興味を持ちました。", note: "-ed は人の感じ方、-ing は物事が与える印象を表します。" },
  { id: "g-060", level: "B1", term: "前置詞の後ろの動詞", japanese: "前置詞の後ろでは -ing 形を使う", category: "動詞の形", label: "文法", pattern: "preposition + 動詞-ing", example: "She is good at explaining ideas.", exampleJapanese: "彼女は考えを説明するのが得意です。", note: "at, in, for, about などの前置詞の後ろに動詞を置くときは -ing 形にします。" }
];

export const FURTHER_INDONESIAN_TRANSLATIONS: Record<string, string> = {
  "w-151": "bertanya; meminta", "w-152": "menjawab; jawaban", "w-153": "membawa", "w-154": "membawa", "w-155": "bersih; membersihkan", "w-156": "memasak; juru masak", "w-157": "menari; tarian", "w-158": "menggambar", "w-159": "menikmati", "w-160": "membantu; bantuan", "w-161": "lapar", "w-162": "haus", "w-163": "lelah", "w-164": "sore; malam", "w-165": "akhir pekan", "w-166": "cuaca", "w-167": "sarapan", "w-168": "makan siang", "w-169": "makan malam", "w-170": "rumah; pulang",
  "w-171": "nasihat; saran", "w-172": "mengizinkan", "w-173": "janji temu", "w-174": "hati-hati", "w-175": "mengubah; perubahan", "w-176": "menghubungi; kontak", "w-177": "benar", "w-178": "keterlambatan; menunda", "w-179": "petunjuk arah", "w-180": "mengikuti", "w-181": "terjadi", "w-182": "menawarkan; tawaran", "w-183": "berjanji; janji", "w-184": "menerima", "w-185": "sederhana", "w-186": "khusus; istimewa", "w-187": "lurus", "w-188": "lalu lintas", "w-189": "pengunjung", "w-190": "khawatir; kekhawatiran",
  "w-191": "mengatur; mengurus", "w-192": "mengeluh", "w-193": "bersaing", "w-194": "berkonsentrasi", "w-195": "mengonfirmasi", "w-196": "menghubungkan", "w-197": "mengandung", "w-198": "mengendalikan; kontrol", "w-199": "meyakinkan", "w-200": "menciptakan", "w-201": "menangani", "w-202": "menuntut; permintaan", "w-203": "fokus; memusatkan perhatian", "w-204": "mencakup", "w-205": "melibatkan", "w-206": "membatasi; batas", "w-207": "tujuan", "w-208": "berhubungan", "w-209": "hasil", "w-210": "cocok; sesuai",
  "p-046": "Bolehkah saya ...?", "p-047": "Silakan.", "p-048": "Maaf.", "p-049": "Pukul berapa ...?", "p-050": "Sampai jumpa besok.", "p-051": "Bolehkah saya minta ...?", "p-052": "Maaf, tetapi ... .", "p-053": "Bagaimana kalau ...?", "p-054": "Tidak apa-apa.", "p-055": "Saya akan kembali dalam ... .", "p-056": "Apakah mungkin untuk ...?", "p-057": "Saya tidak terbiasa dengan ... .", "p-058": "Menurut saya, ...", "p-059": "Intinya adalah ... .", "p-060": "Saya tidak bermaksud untuk ... .",
  "g-046": "menyatakan orang atau benda yang menerima tindakan", "g-047": "menyatakan kepemilikan dengan kata benda", "g-048": "menyingkat kata kerja be dalam percakapan", "g-049": "menjelaskan posisi benda", "g-050": "mengajak melakukan sesuatu bersama", "g-051": "menyatakan rencana yang sudah ditetapkan", "g-052": "menyatakan tingkat yang sama", "g-053": "menyatakan tindakan yang baru selesai atau belum selesai", "g-054": "menyatakan jumlah yang terlalu banyak", "g-055": "menyatakan tujuan melakukan sesuatu", "g-056": "membedakan berhenti melakukan dan berhenti untuk melakukan", "g-057": "menyatakan tingkat yang menghasilkan suatu akibat", "g-058": "menghubungkan pertentangan atau hasil", "g-059": "membedakan perasaan dan sifat yang menimbulkan perasaan", "g-060": "menggunakan bentuk -ing setelah kata depan"
};

export const FURTHER_SECOND_WORD_EXAMPLES: Record<string, ExpandedExamplePair> = {
  "w-151": { english: "Ask your teacher for help.", japanese: "先生に助けを求めてください。" },
  "w-152": { english: "I don't know the answer.", japanese: "私は答えを知りません。" },
  "w-153": { english: "Can you bring me some water?", japanese: "水を少し持ってきてもらえますか。" },
  "w-154": { english: "This box is too heavy to carry.", japanese: "この箱は重すぎて運べません。" },
  "w-155": { english: "Your room looks clean now.", japanese: "あなたの部屋は今きれいに見えます。" },
  "w-156": { english: "My father is a good cook.", japanese: "私の父は料理が上手です。" },
  "w-157": { english: "She loves to dance.", japanese: "彼女は踊るのが大好きです。" },
  "w-158": { english: "Draw a line under the word.", japanese: "その単語の下に線を引いてください。" },
  "w-159": { english: "We enjoy walking in the park.", japanese: "私たちは公園を歩くのを楽しみます。" },
  "w-160": { english: "Thank you for your help.", japanese: "手伝ってくれてありがとうございます。" },
  "w-161": { english: "I'm hungry. Let's eat.", japanese: "お腹がすきました。食べましょう。" },
  "w-162": { english: "I'm thirsty, so I'll get some water.", japanese: "のどが渇いたので、水を取りに行きます。" },
  "w-163": { english: "This long trip made me tired.", japanese: "この長い旅行で私は疲れました。" },
  "w-164": { english: "I study in the evening.", japanese: "私は夕方に勉強します。" },
  "w-165": { english: "What are you doing this weekend?", japanese: "今週末は何をしますか。" },
  "w-166": { english: "The weather can change quickly.", japanese: "天気はすぐに変わることがあります。" },
  "w-167": { english: "Breakfast is included at this hotel.", japanese: "このホテルでは朝食が含まれています。" },
  "w-168": { english: "We had lunch near the station.", japanese: "私たちは駅の近くで昼食をとりました。" },
  "w-169": { english: "What are you having for dinner?", japanese: "夕食は何を食べますか。" },
  "w-170": { english: "She is at home now.", japanese: "彼女は今、家にいます。" },
  "w-171": { english: "Her advice was very helpful.", japanese: "彼女の助言はとても役に立ちました。" },
  "w-172": { english: "The museum does not allow food inside.", japanese: "その博物館では館内での飲食は許可されていません。" },
  "w-173": { english: "Please arrive on time for your appointment.", japanese: "予約の時間には時間どおりに来てください。" },
  "w-174": { english: "Please drive carefully in the rain.", japanese: "雨の中では注意して運転してください。" },
  "w-175": { english: "The weather changed suddenly.", japanese: "天気は急に変わりました。" },
  "w-176": { english: "You can contact the hotel directly.", japanese: "ホテルに直接連絡できます。" },
  "w-177": { english: "Please write the correct date here.", japanese: "ここに正しい日付を書いてください。" },
  "w-178": { english: "Our flight had a short delay.", japanese: "私たちの飛行機は少し遅れました。" },
  "w-179": { english: "I followed the directions on my phone.", japanese: "私は携帯電話の案内に従いました。" },
  "w-180": { english: "Please follow the instructions.", japanese: "指示に従ってください。" },
  "w-181": { english: "Accidents can happen at any time.", japanese: "事故はいつでも起こりえます。" },
  "w-182": { english: "They offered us a discount.", japanese: "彼らは私たちに割引を提示しました。" },
  "w-183": { english: "She kept her promise.", japanese: "彼女は約束を守りました。" },
  "w-184": { english: "I received a package this morning.", japanese: "私は今朝荷物を受け取りました。" },
  "w-185": { english: "Use simple words when you explain it.", japanese: "それを説明するときは簡単な言葉を使ってください。" },
  "w-186": { english: "We made a special meal for her.", japanese: "私たちは彼女のために特別な食事を作りました。" },
  "w-187": { english: "The station is straight ahead.", japanese: "駅はまっすぐ先にあります。" },
  "w-188": { english: "We were late because of the traffic.", japanese: "交通渋滞のため私たちは遅れました。" },
  "w-189": { english: "Visitors must show their tickets.", japanese: "来館者はチケットを見せなければなりません。" },
  "w-190": { english: "She worries about her family.", japanese: "彼女は家族のことを心配しています。" },
  "w-191": { english: "Can you arrange a taxi for us?", japanese: "私たちのためにタクシーを手配できますか。" },
  "w-192": { english: "Customers complained about the service.", japanese: "顧客はサービスについて苦情を言いました。" },
  "w-193": { english: "Our school will compete next week.", japanese: "私たちの学校は来週競技に参加します。" },
  "w-194": { english: "Please concentrate on this question.", japanese: "この質問に集中してください。" },
  "w-195": { english: "The hotel confirmed our reservation.", japanese: "ホテルは私たちの予約を確認しました。" },
  "w-196": { english: "The two cities are connected by train.", japanese: "その二つの都市は電車で結ばれています。" },
  "w-197": { english: "This drink contains a lot of sugar.", japanese: "この飲み物には砂糖がたくさん含まれています。" },
  "w-198": { english: "He lost control of the car.", japanese: "彼は車の制御を失いました。" },
  "w-199": { english: "The facts convinced us.", japanese: "その事実は私たちを納得させました。" },
  "w-200": { english: "This tool creates a simple chart.", japanese: "このツールは簡単なグラフを作成します。" },
  "w-201": { english: "She deals with customer questions.", japanese: "彼女は顧客からの質問に対応しています。" },
  "w-202": { english: "There is high demand for this product.", japanese: "この製品には高い需要があります。" },
  "w-203": { english: "The camera is out of focus.", japanese: "カメラの焦点が合っていません。" },
  "w-204": { english: "Please include your phone number.", japanese: "電話番号を含めてください。" },
  "w-205": { english: "The project involves several teams.", japanese: "そのプロジェクトには複数のチームが関わります。" },
  "w-206": { english: "There is a limit on the number of tickets.", japanese: "チケットの数には制限があります。" },
  "w-207": { english: "The purpose of the app is to help learners.", japanese: "このアプリの目的は学習者を助けることです。" },
  "w-208": { english: "Can you relate this idea to your experience?", japanese: "この考えをあなたの経験と結びつけられますか。" },
  "w-209": { english: "The test results will be ready tomorrow.", japanese: "テスト結果は明日準備できます。" },
  "w-210": { english: "Choose a suitable time to call.", japanese: "電話するのに適した時間を選んでください。" }
};
