import type { ExpandedExamplePair, ExpandedStudyItem } from "./expanded-study-data";

export const IDIOMS: ExpandedStudyItem[] = [
  { id: "i-001", level: "A1", term: "get up", japanese: "起きる、起き上がる", category: "毎日の行動", label: "熟語", example: "I get up at six every day.", exampleJapanese: "私は毎日6時に起きます。", note: "ベッドから起き上がることを表します。過去形は got up です。" },
  { id: "i-002", level: "A1", term: "wake up", japanese: "目が覚める、起こす", category: "毎日の行動", label: "熟語", example: "I woke up at five this morning.", exampleJapanese: "今朝は5時に目が覚めました。", note: "wake up は自分が目を覚ます意味と、人を起こす意味の両方で使えます。" },
  { id: "i-003", level: "A1", term: "sit down", japanese: "座る", category: "毎日の行動", label: "熟語", example: "Please sit down here.", exampleJapanese: "ここに座ってください。", note: "丁寧な指示では Please sit down. のように使います。" },
  { id: "i-004", level: "A1", term: "stand up", japanese: "立ち上がる", category: "毎日の行動", label: "熟語", example: "Please stand up when your name is called.", exampleJapanese: "名前を呼ばれたら立ち上がってください。", note: "sit down の反対の動きです。" },
  { id: "i-005", level: "A1", term: "come in", japanese: "入る", category: "毎日の行動", label: "熟語", example: "Come in and have a seat.", exampleJapanese: "入って、座ってください。", note: "部屋や建物の中に入るよう促すときに使います。" },
  { id: "i-006", level: "A1", term: "go out", japanese: "外出する", category: "毎日の行動", label: "熟語", example: "We went out for dinner.", exampleJapanese: "私たちは夕食を食べに出かけました。", note: "go out for + 活動 で「〜をしに出かける」。" },
  { id: "i-007", level: "A1", term: "put on", japanese: "着る、身につける", category: "服・持ち物", label: "熟語", example: "Put on your jacket.", exampleJapanese: "上着を着てください。", note: "服、靴、帽子などを身につけるときに使います。" },
  { id: "i-008", level: "A1", term: "take off", japanese: "脱ぐ", category: "服・持ち物", label: "熟語", example: "Take off your shoes, please.", exampleJapanese: "靴を脱いでください。", note: "ここでは服や靴を脱ぐ意味です。put on の反対です。" },
  { id: "i-009", level: "A1", term: "turn on", japanese: "つける、作動させる", category: "家・生活", label: "熟語", example: "Turn on the light.", exampleJapanese: "電気をつけてください。", note: "電気製品やスイッチをつけるときに使います。" },
  { id: "i-010", level: "A1", term: "turn off", japanese: "消す、止める", category: "家・生活", label: "熟語", example: "Please turn off your phone.", exampleJapanese: "携帯電話の電源を切ってください。", note: "turn on の反対で、電源や機器を止める意味です。" },
  { id: "i-011", level: "A1", term: "look at", japanese: "見る", category: "毎日の行動", label: "熟語", example: "Look at this picture.", exampleJapanese: "この写真を見てください。", note: "look at の後ろに、見る対象を置きます。" },
  { id: "i-012", level: "A1", term: "look for", japanese: "探す", category: "毎日の行動", label: "熟語", example: "I'm looking for my keys.", exampleJapanese: "私は鍵を探しています。", note: "look for は、まだ見つかっていないものを探すときに使います。" },
  { id: "i-013", level: "A1", term: "pick up", japanese: "拾う、迎えに行く", category: "移動", label: "熟語", example: "Pick up that paper.", exampleJapanese: "その紙を拾ってください。", note: "物を拾うほか、人を車などで迎えに行く意味でも使います。" },
  { id: "i-014", level: "A1", term: "write down", japanese: "書き留める", category: "学習", label: "熟語", example: "Write down the new word.", exampleJapanese: "その新しい単語を書き留めてください。", note: "あとで忘れないように情報を記録するときに使います。" },
  { id: "i-015", level: "A1", term: "wait for", japanese: "待つ", category: "移動", label: "熟語", example: "Wait for me outside.", exampleJapanese: "外で私を待っていてください。", note: "wait の後ろに待つ相手や物を置くときは for が必要です。" },
  { id: "i-016", level: "A2", term: "look after", japanese: "世話をする、気を配る", category: "人・生活", label: "熟語", example: "She looks after her little brother.", exampleJapanese: "彼女は弟の世話をしています。", note: "人、子ども、ペット、物の世話をするときに使います。" },
  { id: "i-017", level: "A2", term: "get on", japanese: "乗る", category: "移動", label: "熟語", example: "Get on the bus at this stop.", exampleJapanese: "この停留所でバスに乗ってください。", note: "バス、電車、飛行機などの公共交通機関に乗るときに使います。" },
  { id: "i-018", level: "A2", term: "get off", japanese: "降りる", category: "移動", label: "熟語", example: "Get off at the next station.", exampleJapanese: "次の駅で降りてください。", note: "get on の反対で、公共交通機関から降りるときに使います。" },
  { id: "i-019", level: "A2", term: "try on", japanese: "試着する", category: "買い物", label: "熟語", example: "Try on this shirt.", exampleJapanese: "このシャツを試着してみてください。", note: "服や靴が合うか確認するために身につけることを表します。" },
  { id: "i-020", level: "A2", term: "fill in", japanese: "書き込む、記入する", category: "手続き", label: "熟語", example: "Please fill in this form.", exampleJapanese: "この用紙に記入してください。", note: "フォームの空欄に必要な情報を書くときに使います。" },
  { id: "i-021", level: "A2", term: "check in", japanese: "チェックインする", category: "旅行", label: "熟語", example: "We checked in at the hotel.", exampleJapanese: "私たちはホテルでチェックインしました。", note: "ホテルや空港で到着を登録するときに使います。" },
  { id: "i-022", level: "A2", term: "go back", japanese: "戻る", category: "移動", label: "熟語", example: "I need to go back to work.", exampleJapanese: "私は仕事に戻る必要があります。", note: "話し手から離れる方向へ元の場所に戻るときに使います。" },
  { id: "i-023", level: "A2", term: "come back", japanese: "戻る、帰ってくる", category: "移動", label: "熟語", example: "She came back from Bali yesterday.", exampleJapanese: "彼女は昨日バリから帰ってきました。", note: "話し手や聞き手のいる場所へ戻るイメージです。" },
  { id: "i-024", level: "A2", term: "give back", japanese: "返す", category: "毎日の行動", label: "熟語", example: "Please give back the book tomorrow.", exampleJapanese: "明日その本を返してください。", note: "借りた物などを持ち主に返すときに使います。" },
  { id: "i-025", level: "A2", term: "put away", japanese: "片付ける、しまう", category: "家・生活", label: "熟語", example: "Put your toys away.", exampleJapanese: "おもちゃを片付けてください。", note: "使った物を元の場所にしまう意味です。" },
  { id: "i-026", level: "A2", term: "find out", japanese: "調べて知る、突き止める", category: "学習", label: "熟語", example: "I need to find out the opening hours.", exampleJapanese: "営業時間を調べる必要があります。", note: "情報を調べた結果、知ることを表します。" },
  { id: "i-027", level: "A2", term: "run out of", japanese: "〜を使い果たす、〜がなくなる", category: "家・生活", label: "熟語", example: "We've run out of milk.", exampleJapanese: "牛乳を使い切ってしまいました。", note: "run out of + 名詞で、必要な物が残っていないことを表します。" },
  { id: "i-028", level: "A2", term: "set off", japanese: "出発する", category: "旅行", label: "熟語", example: "We set off early in the morning.", exampleJapanese: "私たちは早朝に出発しました。", note: "旅行や移動を始めることを表します。" },
  { id: "i-029", level: "A2", term: "take away", japanese: "持ち帰る", category: "買い物", label: "熟語", example: "Can I take this coffee away?", exampleJapanese: "このコーヒーを持ち帰りにできますか。", note: "特に飲食店で、店内で食べずに持ち帰ることを表します。" },
  { id: "i-030", level: "A2", term: "work out", japanese: "解く、理解する", category: "学習", label: "熟語", example: "Can you work out the answer?", exampleJapanese: "その答えを解けますか。", note: "問題の答えや方法を考えて見つける意味で使います。" },
  { id: "i-031", level: "B1", term: "get along with", japanese: "〜と仲良くする、うまくやる", category: "人間関係", label: "熟語", example: "I get along well with my coworkers.", exampleJapanese: "私は同僚と仲良くやっています。", note: "get along well with + 人で、人間関係が良好であることを表します。" },
  { id: "i-032", level: "B1", term: "look forward to", japanese: "〜を楽しみに待つ", category: "会話", label: "熟語", example: "I'm looking forward to meeting you.", exampleJapanese: "お会いできるのを楽しみにしています。", note: "to は前置詞なので、後ろには名詞か -ing 形を置きます。" },
  { id: "i-033", level: "B1", term: "take part in", japanese: "〜に参加する", category: "仕事・学習", label: "熟語", example: "Many students took part in the event.", exampleJapanese: "多くの学生がその行事に参加しました。", note: "take part in + 行事・活動 の形で使います。" },
  { id: "i-034", level: "B1", term: "put up with", japanese: "〜を我慢する", category: "日常", label: "熟語", example: "I can't put up with this noise.", exampleJapanese: "私はこの騒音に耐えられません。", note: "不快なことを我慢する意味で使い、後ろには名詞を置きます。" },
  { id: "i-035", level: "B1", term: "turn down", japanese: "断る、小さくする", category: "仕事・学習", label: "熟語", example: "He turned down the job offer.", exampleJapanese: "彼はその仕事の申し出を断りました。", note: "申し出を断る意味と、音量などを下げる意味があります。" },
  { id: "i-036", level: "B1", term: "come across", japanese: "偶然見つける", category: "毎日の行動", label: "熟語", example: "I came across an old photo.", exampleJapanese: "私は古い写真を偶然見つけました。", note: "探していたわけではないものを、たまたま見つけるときに使います。" },
  { id: "i-037", level: "B1", term: "run into", japanese: "偶然会う", category: "人間関係", label: "熟語", example: "I ran into an old friend yesterday.", exampleJapanese: "昨日、昔の友人に偶然会いました。", note: "予定せずに人にばったり会う意味で使います。" },
  { id: "i-038", level: "B1", term: "carry on", japanese: "続ける", category: "仕事・学習", label: "熟語", example: "Please carry on with your work.", exampleJapanese: "仕事を続けてください。", note: "carry on with + 名詞 / carry on -ing の形で続行を表します。" },
  { id: "i-039", level: "B1", term: "bring up", japanese: "育てる、話題に出す", category: "人間関係", label: "熟語", example: "She brought up two children.", exampleJapanese: "彼女は2人の子どもを育てました。", note: "子どもを育てる意味と、話題を持ち出す意味があります。" },
  { id: "i-040", level: "B1", term: "make up your mind", japanese: "決心する", category: "毎日の行動", label: "熟語", example: "Have you made up your mind yet?", exampleJapanese: "もう決心しましたか。", note: "make up one's mind の形で、one's を主語に合わせて変えます。" },
  { id: "i-041", level: "B1", term: "deal with", japanese: "対処する、扱う", category: "仕事・学習", label: "熟語", example: "We need to deal with this problem.", exampleJapanese: "私たちはこの問題に対処する必要があります。", note: "問題、人、状況などを扱ったり対処したりする意味です。" },
  { id: "i-042", level: "B1", term: "set up", japanese: "設立する、設定する", category: "仕事・学習", label: "熟語", example: "They set up a new business.", exampleJapanese: "彼らは新しい事業を立ち上げました。", note: "組織を設立する意味のほか、機器を設定する意味でも使います。" },
  { id: "i-043", level: "B1", term: "take over", japanese: "引き継ぐ、引き受ける", category: "仕事・学習", label: "熟語", example: "Maria will take over the project next week.", exampleJapanese: "マリアが来週そのプロジェクトを引き継ぎます。", note: "仕事や役割の責任を別の人から引き継ぐときに使います。" },
  { id: "i-044", level: "B1", term: "keep up with", japanese: "遅れずについていく", category: "仕事・学習", label: "熟語", example: "It's hard to keep up with the lesson.", exampleJapanese: "その授業についていくのは大変です。", note: "変化や進み方に遅れずに対応することを表します。" },
  { id: "i-045", level: "B1", term: "point out", japanese: "指摘する", category: "会話", label: "熟語", example: "She pointed out a mistake in my email.", exampleJapanese: "彼女は私のメールの間違いを指摘しました。", note: "人に気付いていない事実や間違いを示すときに使います。" }
];

export const IDIOM_INDONESIAN_TRANSLATIONS: Record<string, string> = {
  "i-001": "bangun", "i-002": "bangun; membangunkan", "i-003": "duduk", "i-004": "berdiri", "i-005": "masuk", "i-006": "keluar; pergi keluar", "i-007": "memakai", "i-008": "melepas", "i-009": "menyalakan", "i-010": "mematikan", "i-011": "melihat", "i-012": "mencari", "i-013": "memungut; menjemput", "i-014": "menuliskan; mencatat", "i-015": "menunggu",
  "i-016": "menjaga; merawat", "i-017": "naik (kendaraan)", "i-018": "turun (kendaraan)", "i-019": "mencoba (pakaian)", "i-020": "mengisi", "i-021": "melakukan check-in", "i-022": "kembali", "i-023": "kembali", "i-024": "mengembalikan", "i-025": "menyimpan; merapikan", "i-026": "mencari tahu; mengetahui", "i-027": "kehabisan", "i-028": "berangkat", "i-029": "membawa pulang", "i-030": "memecahkan; memahami",
  "i-031": "akur dengan", "i-032": "menantikan", "i-033": "berpartisipasi dalam", "i-034": "menahan; mentolerir", "i-035": "menolak; mengecilkan", "i-036": "menemukan secara kebetulan", "i-037": "bertemu secara kebetulan", "i-038": "melanjutkan", "i-039": "membesarkan; mengemukakan", "i-040": "memutuskan", "i-041": "menangani", "i-042": "mendirikan; mengatur", "i-043": "mengambil alih", "i-044": "tetap mengikuti", "i-045": "menunjukkan; menunjuk"
};

export const IDIOM_SECOND_EXAMPLES: Record<string, ExpandedExamplePair> = {
  "i-001": { english: "He got up late on Sunday.", japanese: "彼は日曜日に遅く起きました。" },
  "i-002": { english: "Please wake me up at seven.", japanese: "7時に私を起こしてください。" },
  "i-003": { english: "We sat down near the window.", japanese: "私たちは窓の近くに座りました。" },
  "i-004": { english: "He stood up to open the door.", japanese: "彼はドアを開けるために立ち上がりました。" },
  "i-005": { english: "May I come in?", japanese: "入ってもよろしいですか。" },
  "i-006": { english: "I don't want to go out tonight.", japanese: "今夜は出かけたくありません。" },
  "i-007": { english: "She put on her shoes.", japanese: "彼女は靴を履きました。" },
  "i-008": { english: "He took off his coat.", japanese: "彼はコートを脱ぎました。" },
  "i-009": { english: "Can you turn on the TV?", japanese: "テレビをつけてくれますか。" },
  "i-010": { english: "She turned off the fan.", japanese: "彼女は扇風機を消しました。" },
  "i-011": { english: "Don't look at your phone during class.", japanese: "授業中は携帯電話を見ないでください。" },
  "i-012": { english: "We looked for a cafe near the station.", japanese: "私たちは駅の近くのカフェを探しました。" },
  "i-013": { english: "I'll pick you up at the station.", japanese: "駅まであなたを迎えに行きます。" },
  "i-014": { english: "I wrote down her phone number.", japanese: "私は彼女の電話番号を書き留めました。" },
  "i-015": { english: "They are waiting for the bus.", japanese: "彼らはバスを待っています。" },
  "i-016": { english: "Can you look after my bag?", japanese: "私のバッグを見ていてくれますか。" },
  "i-017": { english: "We got on the train at nine.", japanese: "私たちは9時に電車に乗りました。" },
  "i-018": { english: "She got off the bus near the hotel.", japanese: "彼女はホテルの近くでバスを降りました。" },
  "i-019": { english: "I tried the shoes on before buying them.", japanese: "私は買う前にその靴を試着しました。" },
  "i-020": { english: "Fill in your name and address.", japanese: "名前と住所を記入してください。" },
  "i-021": { english: "You need to check in two hours before the flight.", japanese: "フライトの2時間前までにチェックインする必要があります。" },
  "i-022": { english: "We went back home after lunch.", japanese: "私たちは昼食後に家へ戻りました。" },
  "i-023": { english: "Come back soon.", japanese: "またすぐに戻ってきてください。" },
  "i-024": { english: "He gave my pen back to me.", japanese: "彼は私のペンを私に返してくれました。" },
  "i-025": { english: "She put the dishes away after dinner.", japanese: "彼女は夕食後に食器を片付けました。" },
  "i-026": { english: "We found out that the shop was closed.", japanese: "私たちはその店が閉まっていると知りました。" },
  "i-027": { english: "Don't run out of time.", japanese: "時間を使い切らないようにしてください。" },
  "i-028": { english: "The bus set off at six.", japanese: "バスは6時に出発しました。" },
  "i-029": { english: "They took the food away after dinner.", japanese: "彼らは夕食後にその食べ物を持ち帰りました。" },
  "i-030": { english: "We worked out how to use the new app.", japanese: "私たちは新しいアプリの使い方を理解しました。" },
  "i-031": { english: "Do you get along with your neighbors?", japanese: "近所の人たちとうまくやっていますか。" },
  "i-032": { english: "She looks forward to the weekend.", japanese: "彼女は週末を楽しみにしています。" },
  "i-033": { english: "I'd like to take part in the discussion.", japanese: "その話し合いに参加したいです。" },
  "i-034": { english: "She put up with the delay patiently.", japanese: "彼女はその遅れを辛抱強く我慢しました。" },
  "i-035": { english: "Could you turn down the music?", japanese: "音楽の音量を下げてもらえますか。" },
  "i-036": { english: "She came across a useful website.", japanese: "彼女は役に立つウェブサイトを偶然見つけました。" },
  "i-037": { english: "We ran into our teacher at the mall.", japanese: "私たちはショッピングモールで先生に偶然会いました。" },
  "i-038": { english: "They carried on talking after class.", japanese: "彼らは授業の後も話し続けました。" },
  "i-039": { english: "He brought up an important question.", japanese: "彼は重要な質問を話題に出しました。" },
  "i-040": { english: "It took me a long time to make up my mind.", japanese: "決心するのに長い時間がかかりました。" },
  "i-041": { english: "She deals with customer emails.", japanese: "彼女は顧客からのメールに対応しています。" },
  "i-042": { english: "Can you help me set up my phone?", japanese: "携帯電話の設定を手伝ってくれますか。" },
  "i-043": { english: "A larger company took over the store.", japanese: "より大きな会社がその店を引き継ぎました。" },
  "i-044": { english: "I can't keep up with all the messages.", japanese: "私は全てのメッセージについていけません。" },
  "i-045": { english: "Let me point out one important detail.", japanese: "一つ重要な点を指摘させてください。" }
};
