import type { ExpandedExamplePair, ExpandedStudyItem } from "./expanded-study-data";

export const IDIOMS: ExpandedStudyItem[] = [
  { id: "i-001", level: "A1", term: "get up", japanese: "起きる、起き上がる", category: "毎日の行動", label: "熟語", example: "I get up at six every day.", exampleJapanese: "私は毎日6時に起きます。", note: "ベッドから起き上がることを表します。過去形は got up です。" },
  { id: "i-002", level: "A1", term: "wake up", japanese: "目が覚める、起こす", category: "毎日の行動", label: "熟語", example: "I woke up at five this morning.", exampleJapanese: "今朝は5時に目が覚めました。", note: "wake up は自分が目を覚ます意味と、人を起こす意味の両方で使えます。" },
  { id: "i-003", level: "A1", term: "sit down", japanese: "座る", category: "毎日の行動", label: "熟語", example: "Please sit down here.", exampleJapanese: "ここに座ってください。", note: "丁寧な指示では Please sit down. のように使います。" },
  { id: "i-004", level: "A1", term: "stand up", japanese: "立ち上がる", category: "毎日の行動", label: "熟語", example: "Please stand up when your name is called.", exampleJapanese: "名前を呼ばれたら立ち上がってください。", note: "sit down の反対の動きです。" },
  { id: "i-005", level: "A1", term: "come in", japanese: "入る", category: "毎日の行動", label: "熟語", example: "Come in and have a seat.", exampleJapanese: "入って、座ってください。", note: "部屋や建物の中に入るよう促すときに使います。" },
  { id: "i-006", level: "A1", term: "go out", japanese: "外出する", category: "毎日の行動", label: "熟語", example: "We went out for dinner.", exampleJapanese: "私たちは夕食を食べに出かけました。", note: "go out for + 活動 で「〜をしに出かける」。" },
  { id: "i-007", level: "A1", term: "put on", japanese: "着る、身につける", category: "服・持ち物", label: "熟語", example: "Put on your jacket.", exampleJapanese: "上着を着てください。", note: "服、靴、帽子などを身につけるときに使います。" },
  { id: "i-008", level: "A1", term: "take off", japanese: "脱ぐ", category: "服・持ち物", label: "熟語", example: "Take off your shoes, please.", exampleJapanese: "靴を脱いでください。", note: "ここでは服や靴を脱ぐ意味です。put on の反対です。" },
  { id: "i-009", level: "A1", term: "turn on", japanese: "つける、作動させる", category: "家・生活", label: "熟語", example: "Turn on the light.", exampleJapanese: "電気をつけてください。", note: "電気製品やスイッチをつけるときに使います。" },
  { id: "i-010", level: "A1", term: "turn off", japanese: "消す、止める", category: "家・生活", label: "熟語", example: "Please turn off your phone.", exampleJapanese: "携帯電話の電源を切ってください。", note: "turn on の反対で、電源や機器を止める意味です。" },
  { id: "i-011", level: "A1", term: "look at", japanese: "見る", category: "毎日の行動", label: "熟語", example: "Look at this picture.", exampleJapanese: "この写真を見てください。", note: "look at の後ろに、見る対象を置きます。" },
  { id: "i-012", level: "A1", term: "look for", japanese: "探す", category: "毎日の行動", label: "熟語", example: "I'm looking for my keys.", exampleJapanese: "私は鍵を探しています。", note: "look for は、まだ見つかっていないものを探すときに使います。" },
  { id: "i-013", level: "A1", term: "pick up", japanese: "拾う、迎えに行く", category: "移動", label: "熟語", example: "Pick up that paper.", exampleJapanese: "その紙を拾ってください。", note: "物を拾うほか、人を車などで迎えに行く意味でも使います。" },
  { id: "i-014", level: "A1", term: "write down", japanese: "書き留める", category: "学習", label: "熟語", example: "Write down the new word.", exampleJapanese: "その新しい単語を書き留めてください。", note: "あとで忘れないように情報を記録するときに使います。" },
  { id: "i-015", level: "A1", term: "wait for", japanese: "待つ", category: "移動", label: "熟語", example: "Wait for me outside.", exampleJapanese: "外で私を待っていてください。", note: "wait の後ろに待つ相手や物を置くときは for が必要です。" },
  { id: "i-016", level: "A2", term: "look after", japanese: "世話をする、気を配る", category: "人・生活", label: "熟語", example: "She looks after her little brother.", exampleJapanese: "彼女は弟の世話をしています。", note: "人、子ども、ペット、物の世話をするときに使います。" },
  { id: "i-017", level: "A2", term: "get on", japanese: "乗る", category: "移動", label: "熟語", example: "Get on the bus at this stop.", exampleJapanese: "この停留所でバスに乗ってください。", note: "バス、電車、飛行機などの公共交通機関に乗るときに使います。" },
  { id: "i-018", level: "A2", term: "get off", japanese: "降りる", category: "移動", label: "熟語", example: "Get off at the next station.", exampleJapanese: "次の駅で降りてください。", note: "get on の反対で、公共交通機関から降りるときに使います。" },
  { id: "i-019", level: "A2", term: "try on", japanese: "試着する", category: "買い物", label: "熟語", example: "Try on this shirt.", exampleJapanese: "このシャツを試着してみてください。", note: "服や靴が合うか確認するために身につけることを表します。" },
  { id: "i-020", level: "A2", term: "fill in", japanese: "書き込む、記入する", category: "手続き", label: "熟語", example: "Please fill in this form.", exampleJapanese: "この用紙に記入してください。", note: "フォームの空欄に必要な情報を書くときに使います。" },
  { id: "i-021", level: "A2", term: "check in", japanese: "チェックインする", category: "旅行", label: "熟語", example: "We checked in at the hotel.", exampleJapanese: "私たちはホテルでチェックインしました。", note: "ホテルや空港で到着を登録するときに使います。" },
  { id: "i-022", level: "A2", term: "go back", japanese: "戻る", category: "移動", label: "熟語", example: "I need to go back to work.", exampleJapanese: "私は仕事に戻る必要があります。", note: "話し手から離れる方向へ元の場所に戻るときに使います。" },
  { id: "i-023", level: "A2", term: "come back", japanese: "戻る、帰ってくる", category: "移動", label: "熟語", example: "She came back from Bali yesterday.", exampleJapanese: "彼女は昨日バリから帰ってきました。", note: "話し手や聞き手のいる場所へ戻るイメージです。" },
  { id: "i-024", level: "A2", term: "give back", japanese: "返す", category: "毎日の行動", label: "熟語", example: "Please give back the book tomorrow.", exampleJapanese: "明日その本を返してください。", note: "借りた物などを持ち主に返すときに使います。" },
  { id: "i-025", level: "A2", term: "put away", japanese: "片付ける、しまう", category: "家・生活", label: "熟語", example: "Put your toys away.", exampleJapanese: "おもちゃを片付けてください。", note: "使った物を元の場所にしまう意味です。" },
  { id: "i-026", level: "A2", term: "find out", japanese: "調べて知る、突き止める", category: "学習", label: "熟語", example: "I need to find out the opening hours.", exampleJapanese: "営業時間を調べる必要があります。", note: "情報を調べた結果、知ることを表します。" },
  { id: "i-027", level: "A2", term: "run out of", japanese: "〜を使い果たす、〜がなくなる", category: "家・生活", label: "熟語", example: "We've run out of milk.", exampleJapanese: "牛乳を使い切ってしまいました。", note: "run out of + 名詞で、必要な物が残っていないことを表します。" },
  { id: "i-028", level: "A2", term: "set off", japanese: "出発する", category: "旅行", label: "熟語", example: "We set off early in the morning.", exampleJapanese: "私たちは早朝に出発しました。", note: "旅行や移動を始めることを表します。" },
  { id: "i-029", level: "A2", term: "take away", japanese: "持ち帰る", category: "買い物", label: "熟語", example: "Can I take this coffee away?", exampleJapanese: "このコーヒーを持ち帰りにできますか。", note: "特に飲食店で、店内で食べずに持ち帰ることを表します。" },
  { id: "i-030", level: "A2", term: "work out", japanese: "解く、理解する", category: "学習", label: "熟語", example: "Can you work out the answer?", exampleJapanese: "その答えを解けますか。", note: "問題の答えや方法を考えて見つける意味で使います。" },
  { id: "i-031", level: "B1", term: "get along with", japanese: "〜と仲良くする、うまくやる", category: "人間関係", label: "熟語", example: "I get along well with my coworkers.", exampleJapanese: "私は同僚と仲良くやっています。", note: "get along well with + 人で、人間関係が良好であることを表します。" },
  { id: "i-032", level: "B1", term: "look forward to", japanese: "〜を楽しみに待つ", category: "会話", label: "熟語", example: "I'm looking forward to meeting you.", exampleJapanese: "お会いできるのを楽しみにしています。", note: "to は前置詞なので、後ろには名詞か -ing 形を置きます。" },
  { id: "i-033", level: "B1", term: "take part in", japanese: "〜に参加する", category: "仕事・学習", label: "熟語", example: "Many students took part in the event.", exampleJapanese: "多くの学生がその行事に参加しました。", note: "take part in + 行事・活動 の形で使います。" },
  { id: "i-034", level: "B1", term: "put up with", japanese: "〜を我慢する", category: "日常", label: "熟語", example: "I can't put up with this noise.", exampleJapanese: "私はこの騒音に耐えられません。", note: "不快なことを我慢する意味で使い、後ろには名詞を置きます。" },
  { id: "i-035", level: "B1", term: "turn down", japanese: "断る、小さくする", category: "仕事・学習", label: "熟語", example: "He turned down the job offer.", exampleJapanese: "彼はその仕事の申し出を断りました。", note: "申し出を断る意味と、音量などを下げる意味があります。" },
  { id: "i-036", level: "B1", term: "come across", japanese: "偶然見つける", category: "毎日の行動", label: "熟語", example: "I came across an old photo.", exampleJapanese: "私は古い写真を偶然見つけました。", note: "探していたわけではないものを、たまたま見つけるときに使います。" },
  { id: "i-037", level: "B1", term: "run into", japanese: "偶然会う", category: "人間関係", label: "熟語", example: "I ran into an old friend yesterday.", exampleJapanese: "昨日、昔の友人に偶然会いました。", note: "予定せずに人にばったり会う意味で使います。" },
  { id: "i-038", level: "B1", term: "carry on", japanese: "続ける", category: "仕事・学習", label: "熟語", example: "Please carry on with your work.", exampleJapanese: "仕事を続けてください。", note: "carry on with + 名詞 / carry on -ing の形で続行を表します。" },
  { id: "i-039", level: "B1", term: "bring up", japanese: "育てる、話題に出す", category: "人間関係", label: "熟語", example: "She brought up two children.", exampleJapanese: "彼女は2人の子どもを育てました。", note: "子どもを育てる意味と、話題を持ち出す意味があります。" },
  { id: "i-040", level: "B1", term: "make up your mind", japanese: "決心する", category: "毎日の行動", label: "熟語", example: "Have you made up your mind yet?", exampleJapanese: "もう決心しましたか。", note: "make up one's mind の形で、one's を主語に合わせて変えます。" },
  { id: "i-041", level: "B1", term: "deal with", japanese: "対処する、扱う", category: "仕事・学習", label: "熟語", example: "We need to deal with this problem.", exampleJapanese: "私たちはこの問題に対処する必要があります。", note: "問題、人、状況などを扱ったり対処したりする意味です。" },
  { id: "i-042", level: "B1", term: "set up", japanese: "設立する、設定する", category: "仕事・学習", label: "熟語", example: "They set up a new business.", exampleJapanese: "彼らは新しい事業を立ち上げました。", note: "組織を設立する意味のほか、機器を設定する意味でも使います。" },
  { id: "i-043", level: "B1", term: "take over", japanese: "引き継ぐ、引き受ける", category: "仕事・学習", label: "熟語", example: "Maria will take over the project next week.", exampleJapanese: "マリアが来週そのプロジェクトを引き継ぎます。", note: "仕事や役割の責任を別の人から引き継ぐときに使います。" },
  { id: "i-044", level: "B1", term: "keep up with", japanese: "遅れずについていく", category: "仕事・学習", label: "熟語", example: "It's hard to keep up with the lesson.", exampleJapanese: "その授業についていくのは大変です。", note: "変化や進み方に遅れずに対応することを表します。" },
  { id: "i-045", level: "B1", term: "point out", japanese: "指摘する", category: "会話", label: "熟語", example: "She pointed out a mistake in my email.", exampleJapanese: "彼女は私のメールの間違いを指摘しました。", note: "人に気付いていない事実や間違いを示すときに使います。" },
  { id: "i-046", level: "A1", term: "get dressed", japanese: "服を着る、身支度をする", category: "毎日の行動", label: "熟語", example: "I get dressed before breakfast.", exampleJapanese: "私は朝食の前に服を着ます。", note: "着ている途中ではなく、服を着て身支度を整えることを表します。" },
  { id: "i-047", level: "A1", term: "have breakfast", japanese: "朝食をとる", category: "毎日の行動", label: "熟語", example: "We have breakfast at seven.", exampleJapanese: "私たちは7時に朝食をとります。", note: "have lunch / have dinner にも同じ形を使えます。" },
  { id: "i-048", level: "A1", term: "go home", japanese: "家に帰る", category: "移動", label: "熟語", example: "I go home by bus.", exampleJapanese: "私はバスで家に帰ります。", note: "home の前に to は通常付けません。" },
  { id: "i-049", level: "A1", term: "come home", japanese: "帰宅する", category: "移動", label: "熟語", example: "He comes home late on Fridays.", exampleJapanese: "彼は金曜日は遅く帰宅します。", note: "話し手のいる家に帰ってくるイメージで使います。" },
  { id: "i-050", level: "A1", term: "get in", japanese: "（車に）乗る", category: "移動", label: "熟語", example: "Get in the car, please.", exampleJapanese: "車に乗ってください。", note: "車やタクシーには get in を使います。バスや電車には get on を使います。" },
  { id: "i-051", level: "A1", term: "get out of", japanese: "（車など）から降りる、出る", category: "移動", label: "熟語", example: "Get out of the car here.", exampleJapanese: "ここで車から降りてください。", note: "get in の反対です。後ろに出る場所を置くときは of が必要です。" },
  { id: "i-052", level: "A1", term: "put back", japanese: "元の場所に戻す", category: "家・生活", label: "熟語", example: "Put the book back on the shelf.", exampleJapanese: "その本を棚に戻してください。", note: "代名詞を使うときは put it back の語順にします。" },
  { id: "i-053", level: "A1", term: "clean up", japanese: "きれいにする、片付ける", category: "家・生活", label: "熟語", example: "Let's clean up the kitchen.", exampleJapanese: "キッチンを片付けましょう。", note: "部屋や場所をきれいにすることを表します。" },
  { id: "i-054", level: "A1", term: "hurry up", japanese: "急ぐ", category: "毎日の行動", label: "熟語", example: "Hurry up, or we'll be late.", exampleJapanese: "急がないと遅れます。", note: "急いでほしいときによく使う表現です。" },
  { id: "i-055", level: "A1", term: "slow down", japanese: "速度を落とす、ゆっくりする", category: "移動", label: "熟語", example: "Please slow down.", exampleJapanese: "ゆっくりしてください。", note: "車の速度だけでなく、話す速さや行動の速さにも使えます。" },
  { id: "i-056", level: "A1", term: "come over", japanese: "（家などに）来る、訪ねてくる", category: "人・生活", label: "熟語", example: "Come over after school.", exampleJapanese: "放課後にうちへ来てください。", note: "相手を自分の家などへ招く、カジュアルな表現です。" },
  { id: "i-057", level: "A1", term: "go away", japanese: "去る、どこかへ行く", category: "毎日の行動", label: "熟語", example: "He went away for the weekend.", exampleJapanese: "彼は週末の間、出かけていました。", note: "人に直接 Please go away. と言うと強い言い方になります。" },
  { id: "i-058", level: "A1", term: "ask for", japanese: "求める、注文する", category: "会話", label: "熟語", example: "I'd like to ask for the menu.", exampleJapanese: "メニューをお願いします。", note: "ask for + 欲しい物・人 の形で使います。" },
  { id: "i-059", level: "A1", term: "call back", japanese: "電話をかけ直す", category: "会話", label: "熟語", example: "I'll call you back later.", exampleJapanese: "あとで電話をかけ直します。", note: "代名詞は call me back のように真ん中に置きます。" },
  { id: "i-060", level: "A1", term: "look out", japanese: "気をつける", category: "毎日の行動", label: "熟語", example: "Look out! There's a car coming.", exampleJapanese: "気をつけて！ 車が来ています。", note: "危険を知らせる短い警告として使います。" },
  { id: "i-061", level: "A2", term: "break down", japanese: "故障する、動かなくなる", category: "移動", label: "熟語", example: "Our car broke down on the way home.", exampleJapanese: "私たちの車は帰宅途中で故障しました。", note: "車や機械が動かなくなるときに使います。" },
  { id: "i-062", level: "A2", term: "bring back", japanese: "持ち戻る、思い出させる", category: "毎日の行動", label: "熟語", example: "Please bring back my book tomorrow.", exampleJapanese: "明日、私の本を返してください。", note: "物を元の場所へ持ち帰る意味のほか、記憶をよみがえらせる意味もあります。" },
  { id: "i-063", level: "A2", term: "call off", japanese: "中止する", category: "予定", label: "熟語", example: "They called off the game because of rain.", exampleJapanese: "雨のため、彼らは試合を中止しました。", note: "予定していた行事や会議などを中止するときに使います。" },
  { id: "i-064", level: "A2", term: "drop off", japanese: "送り届ける、置いていく", category: "移動", label: "熟語", example: "I can drop you off at the station.", exampleJapanese: "駅まであなたを送っていけます。", note: "人を車で目的地まで送る意味でよく使います。" },
  { id: "i-065", level: "A2", term: "eat out", japanese: "外食する", category: "食事", label: "熟語", example: "We eat out once a week.", exampleJapanese: "私たちは週に一度外食します。", note: "家で食べずにレストランなどで食事をすることを表します。" },
  { id: "i-066", level: "A2", term: "get together", japanese: "集まる", category: "人間関係", label: "熟語", example: "Let's get together this weekend.", exampleJapanese: "今週末に集まりましょう。", note: "友人や家族が会うことを提案するときに便利です。" },
  { id: "i-067", level: "A2", term: "give up", japanese: "やめる、あきらめる", category: "毎日の行動", label: "熟語", example: "He gave up smoking last year.", exampleJapanese: "彼は昨年たばこをやめました。", note: "give up + 名詞 / -ing で、習慣や行動をやめることを表します。" },
  { id: "i-068", level: "A2", term: "hand in", japanese: "提出する", category: "学習", label: "熟語", example: "Please hand in your homework by Friday.", exampleJapanese: "金曜日までに宿題を提出してください。", note: "先生や担当者に書類・宿題などを提出するときに使います。" },
  { id: "i-069", level: "A2", term: "hang out", japanese: "一緒に時間を過ごす", category: "人間関係", label: "熟語", example: "We like to hang out at the park.", exampleJapanese: "私たちは公園で一緒に過ごすのが好きです。", note: "友人と気軽に時間を過ごすカジュアルな表現です。" },
  { id: "i-070", level: "A2", term: "look out for", japanese: "注意して探す、気を配る", category: "毎日の行動", label: "熟語", example: "Look out for the blue sign.", exampleJapanese: "青い標識に気をつけて探してください。", note: "見つけるべき物に注意を向けるときに使います。" },
  { id: "i-071", level: "A2", term: "pay for", japanese: "〜の代金を払う", category: "買い物", label: "熟語", example: "Who is going to pay for dinner?", exampleJapanese: "夕食代は誰が払いますか。", note: "pay for + 商品・サービス の形で使います。" },
  { id: "i-072", level: "A2", term: "put off", japanese: "延期する、後回しにする", category: "予定", label: "熟語", example: "Don't put off your homework.", exampleJapanese: "宿題を後回しにしないでください。", note: "put off + 名詞 / -ing で、予定を先延ばしにすることを表します。" },
  { id: "i-073", level: "A2", term: "take care of", japanese: "世話をする、管理する", category: "人・生活", label: "熟語", example: "Can you take care of the dog?", exampleJapanese: "犬の世話をしてくれますか。", note: "人、動物、仕事などを責任を持って扱うときに使います。" },
  { id: "i-074", level: "A2", term: "turn up", japanese: "現れる、音量を上げる", category: "予定", label: "熟語", example: "He turned up late for the meeting.", exampleJapanese: "彼は会議に遅れて現れました。", note: "人が現れる意味のほか、音量などを上げる意味もあります。" },
  { id: "i-075", level: "A2", term: "use up", japanese: "使い切る", category: "家・生活", label: "熟語", example: "Don't use up all the paper.", exampleJapanese: "紙を全部使い切らないでください。", note: "使える物を残さず使い切ることを表します。" },
  { id: "i-076", level: "B1", term: "back up", japanese: "支える、バックアップを取る", category: "仕事・学習", label: "熟語", example: "My coworkers backed me up during the meeting.", exampleJapanese: "同僚は会議中に私を支えてくれました。", note: "人を支持する意味と、データのコピーを保存する意味があります。" },
  { id: "i-077", level: "B1", term: "break up", japanese: "別れる、解散する", category: "人間関係", label: "熟語", example: "They broke up last year.", exampleJapanese: "彼らは昨年別れました。", note: "恋人同士が別れる意味のほか、集まりが解散する意味もあります。" },
  { id: "i-078", level: "B1", term: "come up with", japanese: "考え出す、思いつく", category: "仕事・学習", label: "熟語", example: "She came up with a great idea.", exampleJapanese: "彼女はすばらしいアイデアを思いつきました。", note: "解決策・アイデア・答えなどを考え出すときに使います。" },
  { id: "i-079", level: "B1", term: "cut down on", japanese: "〜を減らす", category: "毎日の行動", label: "熟語", example: "I'm trying to cut down on sugar.", exampleJapanese: "私は砂糖を減らそうとしています。", note: "cut down on + 名詞で、量や回数を減らすことを表します。" },
  { id: "i-080", level: "B1", term: "end up", japanese: "結局〜になる、最後には〜する", category: "会話", label: "熟語", example: "We ended up taking a taxi.", exampleJapanese: "私たちは結局タクシーに乗ることになりました。", note: "end up + -ing で、最終的な結果を表せます。" },
  { id: "i-081", level: "B1", term: "get back to", japanese: "後で返事をする、再び連絡する", category: "仕事・学習", label: "熟語", example: "I'll get back to you tomorrow.", exampleJapanese: "明日あなたに返事します。", note: "すぐに答えられないとき、後で連絡することを伝える表現です。" },
  { id: "i-082", level: "B1", term: "give in", japanese: "屈する、譲歩する", category: "会話", label: "熟語", example: "He finally gave in and agreed.", exampleJapanese: "彼はついに折れて同意しました。", note: "抵抗や主張をやめて相手に譲るときに使います。" },
  { id: "i-083", level: "B1", term: "go over", japanese: "見直す、確認する", category: "仕事・学習", label: "熟語", example: "Let's go over the plan once more.", exampleJapanese: "もう一度その計画を確認しましょう。", note: "内容を注意深く確認したり復習したりすることを表します。" },
  { id: "i-084", level: "B1", term: "make up for", japanese: "埋め合わせをする、補う", category: "仕事・学習", label: "熟語", example: "I want to make up for being late.", exampleJapanese: "遅れた埋め合わせをしたいです。", note: "make up for + 失敗・不足 の形で、悪い結果を補うことを表します。" },
  { id: "i-085", level: "B1", term: "sort out", japanese: "解決する、整理する", category: "仕事・学習", label: "熟語", example: "We need to sort out this problem.", exampleJapanese: "私たちはこの問題を解決する必要があります。", note: "問題を解決する意味と、物を分類・整理する意味があります。" },
  { id: "i-086", level: "B1", term: "stand for", japanese: "意味する、表す", category: "会話", label: "熟語", example: "What does DIY stand for?", exampleJapanese: "DIYは何を意味しますか。", note: "略語や記号が何を意味するかを尋ねたり説明したりするときに使います。" },
  { id: "i-087", level: "B1", term: "take on", japanese: "引き受ける、担う", category: "仕事・学習", label: "熟語", example: "I can't take on another project.", exampleJapanese: "これ以上別のプロジェクトを引き受けられません。", note: "仕事・責任・役割を新たに引き受けることを表します。" },
  { id: "i-088", level: "B1", term: "turn out", japanese: "結果的に〜になる、判明する", category: "会話", label: "熟語", example: "The event turned out well.", exampleJapanese: "そのイベントはうまくいきました。", note: "turn out + 形容詞、または It turned out that ... の形で結果を表します。" },
  { id: "i-089", level: "B1", term: "work on", japanese: "取り組む、改善する", category: "仕事・学習", label: "熟語", example: "I'm working on a report this week.", exampleJapanese: "私は今週、報告書に取り組んでいます。", note: "work on + 仕事・課題・スキル の形で使います。" },
  { id: "i-090", level: "B1", term: "stick to", japanese: "守る、従う、続ける", category: "毎日の行動", label: "熟語", example: "Try to stick to your plan.", exampleJapanese: "計画を守るようにしてください。", note: "stick to + 計画・ルール・習慣 の形で、変えずに続けることを表します。" }
];

export const IDIOM_INDONESIAN_TRANSLATIONS: Record<string, string> = {
  "i-001": "bangun", "i-002": "bangun; membangunkan", "i-003": "duduk", "i-004": "berdiri", "i-005": "masuk", "i-006": "keluar; pergi keluar", "i-007": "memakai", "i-008": "melepas", "i-009": "menyalakan", "i-010": "mematikan", "i-011": "melihat", "i-012": "mencari", "i-013": "memungut; menjemput", "i-014": "menuliskan; mencatat", "i-015": "menunggu",
  "i-016": "menjaga; merawat", "i-017": "naik (kendaraan)", "i-018": "turun (kendaraan)", "i-019": "mencoba (pakaian)", "i-020": "mengisi", "i-021": "melakukan check-in", "i-022": "kembali", "i-023": "kembali", "i-024": "mengembalikan", "i-025": "menyimpan; merapikan", "i-026": "mencari tahu; mengetahui", "i-027": "kehabisan", "i-028": "berangkat", "i-029": "membawa pulang", "i-030": "memecahkan; memahami",
  "i-031": "akur dengan", "i-032": "menantikan", "i-033": "berpartisipasi dalam", "i-034": "menahan; mentolerir", "i-035": "menolak; mengecilkan", "i-036": "menemukan secara kebetulan", "i-037": "bertemu secara kebetulan", "i-038": "melanjutkan", "i-039": "membesarkan; mengemukakan", "i-040": "memutuskan", "i-041": "menangani", "i-042": "mendirikan; mengatur", "i-043": "mengambil alih", "i-044": "tetap mengikuti", "i-045": "menunjukkan; menunjuk",
  "i-046": "berpakaian", "i-047": "sarapan", "i-048": "pulang", "i-049": "pulang ke rumah", "i-050": "masuk; naik (mobil)", "i-051": "keluar dari; turun dari", "i-052": "mengembalikan ke tempat semula", "i-053": "membersihkan; merapikan", "i-054": "bergegas", "i-055": "memperlambat; pelan-pelan", "i-056": "datang berkunjung", "i-057": "pergi; menjauh", "i-058": "meminta; memesan", "i-059": "menelepon kembali", "i-060": "hati-hati",
  "i-061": "rusak; mogok", "i-062": "membawa kembali; mengingatkan", "i-063": "membatalkan", "i-064": "mengantar; menurunkan", "i-065": "makan di luar", "i-066": "berkumpul", "i-067": "berhenti; menyerah", "i-068": "menyerahkan", "i-069": "menghabiskan waktu bersama", "i-070": "mencari dengan waspada; memperhatikan", "i-071": "membayar", "i-072": "menunda", "i-073": "merawat; mengurus", "i-074": "muncul; menaikkan", "i-075": "menghabiskan",
  "i-076": "mendukung; mencadangkan", "i-077": "putus; berpisah", "i-078": "memikirkan; menemukan", "i-079": "mengurangi", "i-080": "akhirnya; berakhir", "i-081": "kembali menghubungi", "i-082": "menyerah; mengalah", "i-083": "meninjau; memeriksa", "i-084": "menebus; mengganti", "i-085": "menyelesaikan; membereskan", "i-086": "berarti", "i-087": "menerima; mengambil", "i-088": "ternyata; menjadi", "i-089": "mengerjakan; meningkatkan", "i-090": "berpegang pada; menaati"
};

export const IDIOM_SECOND_EXAMPLES: Record<string, ExpandedExamplePair> = {
  "i-001": { english: "He got up late on Sunday.", japanese: "彼は日曜日に遅く起きました。" },
  "i-002": { english: "Please wake me up at seven.", japanese: "7時に私を起こしてください。" },
  "i-003": { english: "We sat down near the window.", japanese: "私たちは窓の近くに座りました。" },
  "i-004": { english: "He stood up to open the door.", japanese: "彼はドアを開けるために立ち上がりました。" },
  "i-005": { english: "May I come in?", japanese: "入ってもよろしいですか。" },
  "i-006": { english: "I don't want to go out tonight.", japanese: "今夜は出かけたくありません。" },
  "i-007": { english: "She put on her shoes.", japanese: "彼女は靴を履きました。" },
  "i-008": { english: "He took off his coat.", japanese: "彼はコートを脱ぎました。" },
  "i-009": { english: "Can you turn on the TV?", japanese: "テレビをつけてくれますか。" },
  "i-010": { english: "She turned off the fan.", japanese: "彼女は扇風機を消しました。" },
  "i-011": { english: "Don't look at your phone during class.", japanese: "授業中は携帯電話を見ないでください。" },
  "i-012": { english: "We looked for a cafe near the station.", japanese: "私たちは駅の近くのカフェを探しました。" },
  "i-013": { english: "I'll pick you up at the station.", japanese: "駅まであなたを迎えに行きます。" },
  "i-014": { english: "I wrote down her phone number.", japanese: "私は彼女の電話番号を書き留めました。" },
  "i-015": { english: "They are waiting for the bus.", japanese: "彼らはバスを待っています。" },
  "i-016": { english: "Can you look after my bag?", japanese: "私のバッグを見ていてくれますか。" },
  "i-017": { english: "We got on the train at nine.", japanese: "私たちは9時に電車に乗りました。" },
  "i-018": { english: "She got off the bus near the hotel.", japanese: "彼女はホテルの近くでバスを降りました。" },
  "i-019": { english: "I tried the shoes on before buying them.", japanese: "私は買う前にその靴を試着しました。" },
  "i-020": { english: "Fill in your name and address.", japanese: "名前と住所を記入してください。" },
  "i-021": { english: "You need to check in two hours before the flight.", japanese: "フライトの2時間前までにチェックインする必要があります。" },
  "i-022": { english: "We went back home after lunch.", japanese: "私たちは昼食後に家へ戻りました。" },
  "i-023": { english: "Come back soon.", japanese: "またすぐに戻ってきてください。" },
  "i-024": { english: "He gave my pen back to me.", japanese: "彼は私のペンを私に返してくれました。" },
  "i-025": { english: "She put the dishes away after dinner.", japanese: "彼女は夕食後に食器を片付けました。" },
  "i-026": { english: "We found out that the shop was closed.", japanese: "私たちはその店が閉まっていると知りました。" },
  "i-027": { english: "Don't run out of time.", japanese: "時間を使い切らないようにしてください。" },
  "i-028": { english: "The bus set off at six.", japanese: "バスは6時に出発しました。" },
  "i-029": { english: "They took the food away after dinner.", japanese: "彼らは夕食後にその食べ物を持ち帰りました。" },
  "i-030": { english: "We worked out how to use the new app.", japanese: "私たちは新しいアプリの使い方を理解しました。" },
  "i-031": { english: "Do you get along with your neighbors?", japanese: "近所の人たちとうまくやっていますか。" },
  "i-032": { english: "She looks forward to the weekend.", japanese: "彼女は週末を楽しみにしています。" },
  "i-033": { english: "I'd like to take part in the discussion.", japanese: "その話し合いに参加したいです。" },
  "i-034": { english: "She put up with the delay patiently.", japanese: "彼女はその遅れを辛抱強く我慢しました。" },
  "i-035": { english: "Could you turn down the music?", japanese: "音楽の音量を下げてもらえますか。" },
  "i-036": { english: "She came across a useful website.", japanese: "彼女は役に立つウェブサイトを偶然見つけました。" },
  "i-037": { english: "We ran into our teacher at the mall.", japanese: "私たちはショッピングモールで先生に偶然会いました。" },
  "i-038": { english: "They carried on talking after class.", japanese: "彼らは授業の後も話し続けました。" },
  "i-039": { english: "He brought up an important question.", japanese: "彼は重要な質問を話題に出しました。" },
  "i-040": { english: "It took me a long time to make up my mind.", japanese: "決心するのに長い時間がかかりました。" },
  "i-041": { english: "She deals with customer emails.", japanese: "彼女は顧客からのメールに対応しています。" },
  "i-042": { english: "Can you help me set up my phone?", japanese: "携帯電話の設定を手伝ってくれますか。" },
  "i-043": { english: "A larger company took over the store.", japanese: "より大きな会社がその店を引き継ぎました。" },
  "i-044": { english: "I can't keep up with all the messages.", japanese: "私は全てのメッセージについていけません。" },
  "i-045": { english: "Let me point out one important detail.", japanese: "一つ重要な点を指摘させてください。" },
  "i-046": { english: "The children got dressed quickly.", japanese: "子どもたちはすぐに服を着ました。" },
  "i-047": { english: "She had breakfast with her family.", japanese: "彼女は家族と朝食をとりました。" },
  "i-048": { english: "Let's go home now.", japanese: "もう家に帰りましょう。" },
  "i-049": { english: "What time did you come home?", japanese: "何時に帰宅しましたか。" },
  "i-050": { english: "She got in a taxi.", japanese: "彼女はタクシーに乗りました。" },
  "i-051": { english: "He got out of the taxi.", japanese: "彼はタクシーから降りました。" },
  "i-052": { english: "Please put it back after you use it.", japanese: "使った後はそれを元に戻してください。" },
  "i-053": { english: "They cleaned up after the party.", japanese: "彼らはパーティーの後で片付けました。" },
  "i-054": { english: "She hurried up to catch the bus.", japanese: "彼女はバスに間に合うよう急ぎました。" },
  "i-055": { english: "The driver slowed down near the school.", japanese: "運転手は学校の近くで速度を落としました。" },
  "i-056": { english: "My friends came over for dinner.", japanese: "友人たちが夕食にうちへ来ました。" },
  "i-057": { english: "Please go away and give me some time.", japanese: "行って、少し時間をください。" },
  "i-058": { english: "She asked for a glass of water.", japanese: "彼女はコップ一杯の水を頼みました。" },
  "i-059": { english: "Please call me back when you're free.", japanese: "時間があるときに電話をかけ直してください。" },
  "i-060": { english: "Look out! The box is falling.", japanese: "気をつけて！ 箱が落ちています。" },
  "i-061": { english: "The washing machine broke down yesterday.", japanese: "洗濯機は昨日故障しました。" },
  "i-062": { english: "This song brings back happy memories.", japanese: "この歌は楽しい思い出をよみがえらせます。" },
  "i-063": { english: "We had to call off the meeting.", japanese: "私たちは会議を中止しなければなりませんでした。" },
  "i-064": { english: "She dropped off the package at the office.", japanese: "彼女は荷物を会社に届けました。" },
  "i-065": { english: "Let's eat out tonight.", japanese: "今夜は外食しましょう。" },
  "i-066": { english: "The family gets together every New Year.", japanese: "その家族は毎年新年に集まります。" },
  "i-067": { english: "Don't give up when it gets difficult.", japanese: "難しくなってもあきらめないでください。" },
  "i-068": { english: "She handed in the form yesterday.", japanese: "彼女は昨日その用紙を提出しました。" },
  "i-069": { english: "They hung out after class.", japanese: "彼らは授業の後に一緒に過ごしました。" },
  "i-070": { english: "I'm looking out for a message from the hotel.", japanese: "私はホテルからのメッセージを注意して待っています。" },
  "i-071": { english: "I paid for the tickets online.", japanese: "私はチケット代をオンラインで払いました。" },
  "i-072": { english: "They put off the trip until Monday.", japanese: "彼らは旅行を月曜日まで延期しました。" },
  "i-073": { english: "He takes care of the garden.", japanese: "彼は庭の手入れをしています。" },
  "i-074": { english: "Could you turn up the volume?", japanese: "音量を上げてもらえますか。" },
  "i-075": { english: "We used up the last of the milk.", japanese: "私たちは残りの牛乳を使い切りました。" },
  "i-076": { english: "Back up your photos regularly.", japanese: "写真は定期的にバックアップしてください。" },
  "i-077": { english: "The meeting broke up at five.", japanese: "会議は5時に解散しました。" },
  "i-078": { english: "Can you come up with a solution?", japanese: "解決策を考え出せますか。" },
  "i-079": { english: "He cut down on his screen time.", japanese: "彼は画面を見る時間を減らしました。" },
  "i-080": { english: "The movie ended up being much better than I expected.", japanese: "その映画は予想よりずっと良いものになりました。" },
  "i-081": { english: "She got back to me with the answer.", japanese: "彼女は答えを持って私に返事をくれました。" },
  "i-082": { english: "Don't give in to pressure.", japanese: "圧力に屈しないでください。" },
  "i-083": { english: "She went over her notes before the test.", japanese: "彼女はテスト前にノートを見直しました。" },
  "i-084": { english: "I need to make up for the lost time.", japanese: "失った時間を取り戻す必要があります。" },
  "i-085": { english: "She sorted out the files by date.", japanese: "彼女はファイルを日付ごとに整理しました。" },
  "i-086": { english: "The letters stand for the names of the teams.", japanese: "その文字はチーム名を表しています。" },
  "i-087": { english: "She took on more responsibility at work.", japanese: "彼女は仕事でより多くの責任を引き受けました。" },
  "i-088": { english: "It turned out that the store was closed.", japanese: "その店は閉まっていたことが分かりました。" },
  "i-089": { english: "She is working on her pronunciation.", japanese: "彼女は発音の改善に取り組んでいます。" },
  "i-090": { english: "He sticks to his budget each month.", japanese: "彼は毎月予算を守っています。" }
};
