import type { ExpandedExamplePair, ExpandedStudyItem } from "./expanded-study-data";

export const MORE_WORDS: ExpandedStudyItem[] = [
  { id: "w-091", level: "A1", term: "learn", japanese: "学ぶ、覚える", category: "仕事・学習", label: "動詞", pronunciation: "/lɜːrn/", example: "I learn new words every day.", exampleJapanese: "私は毎日新しい単語を学びます。", note: "learn + 名詞 / learn to + 動詞 の形で使います。" },
  { id: "w-092", level: "A1", term: "speak", japanese: "話す", category: "会話", label: "動詞", pronunciation: "/spiːk/", example: "Can you speak slowly?", exampleJapanese: "ゆっくり話してもらえますか。", note: "speak + 言語、speak to + 人 の形で使います。" },
  { id: "w-093", level: "A1", term: "read", japanese: "読む", category: "仕事・学習", label: "動詞", pronunciation: "/riːd/", example: "I read the news every morning.", exampleJapanese: "私は毎朝ニュースを読みます。", note: "現在形と過去形は同じつづりですが、過去形は /red/ と発音します。" },
  { id: "w-094", level: "A1", term: "write", japanese: "書く", category: "仕事・学習", label: "動詞", pronunciation: "/raɪt/", example: "Write your name here.", exampleJapanese: "ここに名前を書いてください。", note: "write to + 人 で「人に手紙やメールを書く」。" },
  { id: "w-095", level: "A1", term: "listen", japanese: "聞く", category: "会話", label: "動詞", pronunciation: "/ˈlɪsən/", example: "Listen to this podcast.", exampleJapanese: "このポッドキャストを聞いてください。", note: "listen の後ろには通常 to を置きます。" },
  { id: "w-096", level: "A1", term: "watch", japanese: "見る、注意して見る", category: "日常", label: "動詞", pronunciation: "/wɑːtʃ/", example: "We watch a movie on Friday.", exampleJapanese: "私たちは金曜日に映画を見ます。", note: "watch TV / a film のように、動きのあるものを見るときによく使います。" },
  { id: "w-097", level: "A1", term: "buy", japanese: "買う", category: "買い物", label: "動詞", pronunciation: "/baɪ/", example: "I need to buy some fruit.", exampleJapanese: "私は果物を少し買う必要があります。", note: "過去形・過去分詞は bought です。" },
  { id: "w-098", level: "A1", term: "pay", japanese: "支払う", category: "買い物", label: "動詞", pronunciation: "/peɪ/", example: "Can I pay by card?", exampleJapanese: "カードで支払えますか。", note: "pay for + 物、pay by card の形を覚えましょう。" },
  { id: "w-099", level: "A1", term: "open", japanese: "開ける、開いている", category: "日常", label: "動詞/形容詞", pronunciation: "/ˈoʊpən/", example: "Please open the door.", exampleJapanese: "ドアを開けてください。", note: "動詞と形容詞の両方で使えます。" },
  { id: "w-100", level: "A1", term: "close", japanese: "閉める、閉まる", category: "日常", label: "動詞", pronunciation: "/kloʊz/", example: "Close the window, please.", exampleJapanese: "窓を閉めてください。", note: "店などが閉まるときにも使います。" },
  { id: "w-101", level: "A1", term: "start", japanese: "始める、始まる", category: "時間", label: "動詞", pronunciation: "/stɑːrt/", example: "The meeting starts at nine.", exampleJapanese: "会議は9時に始まります。", note: "start to + 動詞 と start -ing はどちらも使えます。" },
  { id: "w-102", level: "A1", term: "finish", japanese: "終える、終わる", category: "時間", label: "動詞", pronunciation: "/ˈfɪnɪʃ/", example: "I finish work at six.", exampleJapanese: "私は6時に仕事を終えます。", note: "finish の後ろには名詞か -ing 形を置けます。" },
  { id: "w-103", level: "A1", term: "busy", japanese: "忙しい", category: "感情・状態", label: "形容詞", pronunciation: "/ˈbɪzi/", example: "I'm busy this afternoon.", exampleJapanese: "私は今日の午後は忙しいです。", note: "be busy + -ing で「〜するのに忙しい」と表せます。" },
  { id: "w-104", level: "A1", term: "free", japanese: "自由な、空いている、無料の", category: "感情・状態", label: "形容詞", pronunciation: "/friː/", example: "Are you free on Saturday?", exampleJapanese: "土曜日は空いていますか。", note: "人が空いている、料金が無料、の両方を表します。" },
  { id: "w-105", level: "A1", term: "easy", japanese: "簡単な", category: "感情・状態", label: "形容詞", pronunciation: "/ˈiːzi/", example: "This question is easy.", exampleJapanese: "この質問は簡単です。", note: "It is easy to + 動詞 の形がよく使われます。" },
  { id: "w-106", level: "A1", term: "hot", japanese: "熱い、暑い", category: "感情・状態", label: "形容詞", pronunciation: "/hɑːt/", example: "The soup is hot.", exampleJapanese: "そのスープは熱いです。", note: "物が熱いことと、天気が暑いことの両方に使えます。" },
  { id: "w-107", level: "A1", term: "cold", japanese: "冷たい、寒い、風邪", category: "感情・状態", label: "形容詞/名詞", pronunciation: "/koʊld/", example: "The water is cold.", exampleJapanese: "水は冷たいです。", note: "have a cold で「風邪をひいている」。" },
  { id: "w-108", level: "A1", term: "left", japanese: "左、残った", category: "移動", label: "名詞/形容詞", pronunciation: "/left/", example: "Turn left at the corner.", exampleJapanese: "角を左に曲がってください。", note: "left は left side の左と、物が残っている意味の両方があります。" },
  { id: "w-109", level: "A1", term: "right", japanese: "右、正しい", category: "移動", label: "名詞/形容詞", pronunciation: "/raɪt/", example: "The post office is on the right.", exampleJapanese: "郵便局は右側にあります。", note: "right answer は「正しい答え」です。" },
  { id: "w-110", level: "A1", term: "next", japanese: "次の、次に", category: "時間", label: "形容詞/副詞", pronunciation: "/nekst/", example: "See you next week.", exampleJapanese: "また来週。", note: "next week のように、next の前には通常 the を置きません。" },
  { id: "w-111", level: "A2", term: "order", japanese: "注文する、順番", category: "買い物", label: "動詞/名詞", pronunciation: "/ˈɔːrdər/", example: "I'd like to order lunch.", exampleJapanese: "昼食を注文したいです。", note: "order food のように注文する対象を後ろに置けます。" },
  { id: "w-112", level: "A2", term: "reserve", japanese: "予約する、取っておく", category: "日常", label: "動詞", pronunciation: "/rɪˈzɜːrv/", example: "I'd like to reserve a table.", exampleJapanese: "テーブルを予約したいです。", note: "reserve a table / room / seat のように使います。" },
  { id: "w-113", level: "A2", term: "cancel", japanese: "取り消す、中止する", category: "日常", label: "動詞", pronunciation: "/ˈkænsəl/", example: "I need to cancel my appointment.", exampleJapanese: "予約を取り消す必要があります。", note: "cancel a meeting / reservation のように使います。" },
  { id: "w-114", level: "A2", term: "check", japanese: "確認する、点検する", category: "仕事・学習", label: "動詞", pronunciation: "/tʃek/", example: "Please check the time.", exampleJapanese: "時間を確認してください。", note: "check + 名詞 で確認する対象を示します。" },
  { id: "w-115", level: "A2", term: "deliver", japanese: "配達する、届ける", category: "日常", label: "動詞", pronunciation: "/dɪˈlɪvər/", example: "They deliver food to this area.", exampleJapanese: "彼らはこの地域に食べ物を配達します。", note: "deliver + 物 to + 場所・人 の形で使えます。" },
  { id: "w-116", level: "A2", term: "organize", japanese: "整理する、計画する", category: "仕事・学習", label: "動詞", pronunciation: "/ˈɔːrɡənaɪz/", example: "Let's organize the files.", exampleJapanese: "ファイルを整理しましょう。", note: "organize an event で行事を企画する意味にもなります。" },
  { id: "w-117", level: "A2", term: "prefer", japanese: "より好む", category: "日常", label: "動詞", pronunciation: "/prɪˈfɜːr/", example: "I prefer tea to coffee.", exampleJapanese: "私はコーヒーよりお茶のほうが好きです。", note: "prefer A to B で「BよりAを好む」。" },
  { id: "w-118", level: "A2", term: "prepare", japanese: "準備する", category: "仕事・学習", label: "動詞", pronunciation: "/prɪˈper/", example: "We need to prepare for the meeting.", exampleJapanese: "私たちは会議の準備をする必要があります。", note: "prepare for + 行事・目的 の形がよく使われます。" },
  { id: "w-119", level: "A2", term: "repair", japanese: "修理する", category: "日常", label: "動詞", pronunciation: "/rɪˈper/", example: "Can you repair this chair?", exampleJapanese: "この椅子を修理できますか。", note: "壊れた物を直すときに使います。" },
  { id: "w-120", level: "A2", term: "request", japanese: "頼む、依頼", category: "仕事・学習", label: "動詞/名詞", pronunciation: "/rɪˈkwest/", example: "I'd like to request more information.", exampleJapanese: "もっと情報をお願いしたいです。", note: "request + 名詞 / request that + 文 の形で使えます。" },
  { id: "w-121", level: "A2", term: "share", japanese: "共有する、分け合う", category: "人", label: "動詞", pronunciation: "/ʃer/", example: "Can you share the document?", exampleJapanese: "その書類を共有してもらえますか。", note: "share + 物 with + 人 で誰かと共有することを表せます。" },
  { id: "w-122", level: "A2", term: "spend", japanese: "過ごす、使う", category: "時間", label: "動詞", pronunciation: "/spend/", example: "I spend an hour studying each day.", exampleJapanese: "私は毎日1時間勉強して過ごします。", note: "spend 時間 -ing、spend お金 on + 名詞 の形を使います。" },
  { id: "w-123", level: "A2", term: "support", japanese: "支援する、支え", category: "人", label: "動詞/名詞", pronunciation: "/səˈpɔːrt/", example: "My friends support my decision.", exampleJapanese: "友人たちは私の決断を支えてくれます。", note: "動詞と名詞の両方で使えます。" },
  { id: "w-124", level: "A2", term: "useful", japanese: "役に立つ", category: "仕事・学習", label: "形容詞", pronunciation: "/ˈjuːsfəl/", example: "This guide is useful.", exampleJapanese: "このガイドは役に立ちます。", note: "useful advice のように、役立つ物や情報に使います。" },
  { id: "w-125", level: "A2", term: "quiet", japanese: "静かな", category: "感情・状態", label: "形容詞", pronunciation: "/ˈkwaɪət/", example: "Please be quiet in the library.", exampleJapanese: "図書館では静かにしてください。", note: "be quiet は「静かにする」という依頼にも使います。" },
  { id: "w-126", level: "A2", term: "safe", japanese: "安全な", category: "日常", label: "形容詞", pronunciation: "/seɪf/", example: "This area is safe at night.", exampleJapanese: "この地域は夜でも安全です。", note: "safe place / safe to + 動詞 の形を使えます。" },
  { id: "w-127", level: "A2", term: "around", japanese: "〜の周りに、だいたい", category: "移動", label: "前置詞/副詞", pronunciation: "/əˈraʊnd/", example: "There are cafes around the station.", exampleJapanese: "駅の周りにはカフェがあります。", note: "数や時間のおおよその量にも使えます。" },
  { id: "w-128", level: "A2", term: "through", japanese: "〜を通って、〜を通じて", category: "移動", label: "前置詞", pronunciation: "/θruː/", example: "We walked through the park.", exampleJapanese: "私たちは公園を通って歩きました。", note: "場所を通り抜ける意味と、手段を通じる意味があります。" },
  { id: "w-129", level: "A2", term: "possible", japanese: "可能な", category: "感情・状態", label: "形容詞", pronunciation: "/ˈpɑːsəbəl/", example: "Is it possible to pay later?", exampleJapanese: "あとで支払うことは可能ですか。", note: "It is possible to + 動詞 の形がよく使われます。" },
  { id: "w-130", level: "A2", term: "customer", japanese: "客、顧客", category: "仕事・学習", label: "名詞", pronunciation: "/ˈkʌstəmər/", example: "The customer asked a question.", exampleJapanese: "そのお客様は質問をしました。", note: "店やサービスを利用する人を表します。" },
  { id: "w-131", level: "B1", term: "apply", japanese: "申し込む、応募する", category: "仕事・学習", label: "動詞", pronunciation: "/əˈplaɪ/", example: "I applied for the job last week.", exampleJapanese: "私は先週その仕事に応募しました。", note: "apply for + 仕事・コース・許可 の形を使います。" },
  { id: "w-132", level: "B1", term: "attend", japanese: "出席する", category: "仕事・学習", label: "動詞", pronunciation: "/əˈtend/", example: "She attended the meeting.", exampleJapanese: "彼女は会議に出席しました。", note: "attend の後ろに meeting や class を直接置けます。" },
  { id: "w-133", level: "B1", term: "contribute", japanese: "貢献する、寄付する", category: "仕事・学習", label: "動詞", pronunciation: "/kənˈtrɪbjuːt/", example: "Everyone can contribute to the project.", exampleJapanese: "誰もがそのプロジェクトに貢献できます。", note: "contribute to + 名詞で「〜に貢献する」。" },
  { id: "w-134", level: "B1", term: "decrease", japanese: "減少する、減らす", category: "仕事・学習", label: "動詞", pronunciation: "/dɪˈkriːs/", example: "The number of visitors decreased.", exampleJapanese: "訪問者数は減少しました。", note: "自動詞と他動詞の両方で使えます。" },
  { id: "w-135", level: "B1", term: "encourage", japanese: "励ます、促す", category: "人", label: "動詞", pronunciation: "/ɪnˈkɜːrɪdʒ/", example: "Her teacher encouraged her to speak.", exampleJapanese: "先生は彼女に話すよう励ましました。", note: "encourage 人 to + 動詞 の形を使います。" },
  { id: "w-136", level: "B1", term: "expect", japanese: "期待する、予想する", category: "感情・状態", label: "動詞", pronunciation: "/ɪkˈspekt/", example: "I expect the train to be late.", exampleJapanese: "電車は遅れると思います。", note: "expect + 名詞 / expect 人・物 to + 動詞 の形を使います。" },
  { id: "w-137", level: "B1", term: "handle", japanese: "対応する、扱う", category: "仕事・学習", label: "動詞", pronunciation: "/ˈhændəl/", example: "She can handle difficult questions.", exampleJapanese: "彼女は難しい質問に対応できます。", note: "問題・状況・物の扱いに使える動詞です。" },
  { id: "w-138", level: "B1", term: "identify", japanese: "特定する、見分ける", category: "仕事・学習", label: "動詞", pronunciation: "/aɪˈdentɪfaɪ/", example: "Can you identify the problem?", exampleJapanese: "問題を特定できますか。", note: "identify + 名詞で対象を特定します。" },
  { id: "w-139", level: "B1", term: "increase", japanese: "増加する、増やす", category: "仕事・学習", label: "動詞", pronunciation: "/ɪnˈkriːs/", example: "Prices increased last month.", exampleJapanese: "価格は先月上がりました。", note: "自動詞と他動詞の両方で使えます。" },
  { id: "w-140", level: "B1", term: "influence", japanese: "影響を与える", category: "仕事・学習", label: "動詞", pronunciation: "/ˈɪnfluəns/", example: "Weather can influence travel plans.", exampleJapanese: "天気は旅行計画に影響を与えることがあります。", note: "influence + 名詞で「〜に影響を与える」。" },
  { id: "w-141", level: "B1", term: "maintain", japanese: "維持する", category: "仕事・学習", label: "動詞", pronunciation: "/meɪnˈteɪn/", example: "It is hard to maintain a good habit.", exampleJapanese: "良い習慣を維持するのは難しいです。", note: "maintain a habit / standard / relationship のように使います。" },
  { id: "w-142", level: "B1", term: "mention", japanese: "言及する", category: "会話", label: "動詞", pronunciation: "/ˈmenʃən/", example: "She mentioned your name.", exampleJapanese: "彼女はあなたの名前に触れました。", note: "mention + 名詞で話題に出すことを表します。" },
  { id: "w-143", level: "B1", term: "notice", japanese: "気づく、お知らせ", category: "仕事・学習", label: "動詞/名詞", pronunciation: "/ˈnoʊtɪs/", example: "I noticed a mistake in the report.", exampleJapanese: "私は報告書の誤りに気づきました。", note: "notice + 名詞で見たり気づいたりすることを表します。" },
  { id: "w-144", level: "B1", term: "perform", japanese: "行う、うまくやる", category: "仕事・学習", label: "動詞", pronunciation: "/pərˈfɔːrm/", example: "The team performed well.", exampleJapanese: "チームは良い成果を出しました。", note: "perform well で「うまくやる」、perform a task で「作業を行う」。" },
  { id: "w-145", level: "B1", term: "provide", japanese: "提供する", category: "仕事・学習", label: "動詞", pronunciation: "/prəˈvaɪd/", example: "The hotel provides free breakfast.", exampleJapanese: "そのホテルは無料の朝食を提供しています。", note: "provide 人 with 物 の形もよく使われます。" },
  { id: "w-146", level: "B1", term: "respond", japanese: "返答する、反応する", category: "会話", label: "動詞", pronunciation: "/rɪˈspɑːnd/", example: "He responded to my email quickly.", exampleJapanese: "彼は私のメールにすぐ返信しました。", note: "respond to + 名詞で「〜に返答・反応する」。" },
  { id: "w-147", level: "B1", term: "schedule", japanese: "予定、予定を組む", category: "仕事・学習", label: "名詞/動詞", pronunciation: "/ˈskedʒuːl/", example: "The meeting is scheduled for Monday.", exampleJapanese: "会議は月曜日に予定されています。", note: "schedule a meeting で会議を予定に入れられます。" },
  { id: "w-148", level: "B1", term: "source", japanese: "情報源、源", category: "仕事・学習", label: "名詞", pronunciation: "/sɔːrs/", example: "Please check the source of the information.", exampleJapanese: "情報の出典を確認してください。", note: "source of + 情報・エネルギー などの形で使います。" },
  { id: "w-149", level: "B1", term: "task", japanese: "課題、仕事", category: "仕事・学習", label: "名詞", pronunciation: "/tæsk/", example: "My first task is to reply to emails.", exampleJapanese: "私の最初の仕事はメールに返信することです。", note: "task は完了すべき具体的な仕事を表します。" },
  { id: "w-150", level: "B1", term: "approach", japanese: "方法、取り組み方", category: "仕事・学習", label: "名詞", pronunciation: "/əˈproʊtʃ/", example: "We need a different approach.", exampleJapanese: "私たちには別の方法が必要です。", note: "approach to + 名詞で「〜への取り組み方」。" }
];

export const MORE_PHRASES: ExpandedStudyItem[] = [
  { id: "p-031", level: "A1", term: "What is your name?", japanese: "お名前は何ですか。", category: "あいさつ", label: "定型表現", example: "What is your name? - I'm Rina.", exampleJapanese: "お名前は何ですか。- リナです。", note: "初対面で名前をたずねる基本表現です。" },
  { id: "p-032", level: "A1", term: "I don't know.", japanese: "わかりません。", category: "会話", label: "定型表現", example: "I don't know the answer.", exampleJapanese: "答えはわかりません。", note: "I don't know + 名詞・疑問詞節 と続けられます。" },
  { id: "p-033", level: "A1", term: "Please say that again.", japanese: "もう一度言ってください。", category: "会話", label: "定型表現", example: "Sorry, please say that again.", exampleJapanese: "すみません、もう一度言ってください。", note: "聞き取れなかったときの丁寧な言い方です。" },
  { id: "p-034", level: "A1", term: "How do you spell ...?", japanese: "〜はどのようにつづりますか。", category: "会話", label: "定型表現", example: "How do you spell your last name?", exampleJapanese: "苗字はどのようにつづりますか。", note: "名前・地名・単語のつづりを確認するときに使います。" },
  { id: "p-035", level: "A1", term: "What would you like?", japanese: "何になさいますか。", category: "買い物", label: "定型表現", example: "What would you like to drink?", exampleJapanese: "何を飲みたいですか。", note: "店や食事の場面で、丁寧に希望をたずねる表現です。" },
  { id: "p-036", level: "A2", term: "Can you show me ...?", japanese: "〜を見せてもらえますか。", category: "お願い", label: "定型表現", example: "Can you show me the way to the station?", exampleJapanese: "駅までの道を教えてもらえますか。", note: "物を見せてもらう、道を教えてもらう、どちらにも使えます。" },
  { id: "p-037", level: "A2", term: "I'd rather ... .", japanese: "むしろ〜したいです。", category: "会話", label: "定型表現", example: "I'd rather stay home tonight.", exampleJapanese: "今夜はむしろ家にいたいです。", note: "would rather の後ろには動詞の原形を置きます。" },
  { id: "p-038", level: "A2", term: "Do you have ...?", japanese: "〜はありますか。", category: "買い物", label: "定型表現", example: "Do you have this in a larger size?", exampleJapanese: "これのもっと大きいサイズはありますか。", note: "店で在庫や別のサイズをたずねるときに便利です。" },
  { id: "p-039", level: "A2", term: "Why don't we ...?", japanese: "〜しませんか。", category: "会話", label: "定型表現", example: "Why don't we meet after work?", exampleJapanese: "仕事の後に会いませんか。", note: "相手への提案には Why don't we + 動詞の原形 を使えます。" },
  { id: "p-040", level: "A2", term: "I'll take it.", japanese: "それにします。", category: "買い物", label: "定型表現", example: "This one is perfect. I'll take it.", exampleJapanese: "これはぴったりです。これにします。", note: "買い物で購入を決めたときの自然な表現です。" },
  { id: "p-041", level: "B1", term: "Would you mind if ...?", japanese: "もし〜したら気になりますか。", category: "お願い", label: "定型表現", example: "Would you mind if I opened the window?", exampleJapanese: "私が窓を開けたら気になりますか。", note: "丁寧に許可を求める表現で、if 節には過去形を使うことが多いです。" },
  { id: "p-042", level: "B1", term: "I appreciate it.", japanese: "感謝します。", category: "会話", label: "定型表現", example: "Thanks for your help. I really appreciate it.", exampleJapanese: "手伝ってくれてありがとう。本当に感謝しています。", note: "相手の助けや配慮に丁寧に感謝するときに使います。" },
  { id: "p-043", level: "B1", term: "That makes sense.", japanese: "なるほど、それはもっともです。", category: "会話", label: "定型表現", example: "Taking the train is faster. - That makes sense.", exampleJapanese: "電車のほうが速いです。- なるほど、それはもっともです。", note: "相手の説明に納得したことを表す自然な返答です。" },
  { id: "p-044", level: "B1", term: "I'm looking forward to ... .", japanese: "〜を楽しみにしています。", category: "会話", label: "定型表現", example: "I'm looking forward to meeting you.", exampleJapanese: "お会いできるのを楽しみにしています。", note: "to は前置詞なので、後ろには名詞か -ing 形を置きます。" },
  { id: "p-045", level: "B1", term: "Could you let me know ...?", japanese: "〜を知らせていただけますか。", category: "お願い", label: "定型表現", example: "Could you let me know when you arrive?", exampleJapanese: "到着したら知らせていただけますか。", note: "後ろは通常の文の語順にします。" }
];

export const MORE_GRAMMAR: ExpandedStudyItem[] = [
  { id: "g-031", level: "A1", term: "can / can't", japanese: "できる、できない、許可を表す", category: "助動詞", label: "文法", pattern: "can / can't + 動詞の原形", example: "Can you swim?", exampleJapanese: "あなたは泳げますか。", note: "can の後ろは常に動詞の原形です。" },
  { id: "g-032", level: "A1", term: "複数形", japanese: "二つ以上の名詞を表す", category: "名詞", label: "文法", pattern: "one book / two books", example: "These boxes are heavy.", exampleJapanese: "これらの箱は重いです。", note: "多くの名詞は -s / -es を付けますが、不規則な複数形もあります。" },
  { id: "g-033", level: "A1", term: "this / that / these / those", japanese: "近い物、遠い物を指す", category: "基本文", label: "文法", pattern: "this/these: 近い / that/those: 遠い", example: "These shoes are comfortable.", exampleJapanese: "この靴は履き心地が良いです。", note: "this と that は単数、these と those は複数です。" },
  { id: "g-034", level: "A1", term: "like + -ing", japanese: "好きな行動を表す", category: "動詞の形", label: "文法", pattern: "like + 動詞-ing", example: "I like reading before bed.", exampleJapanese: "私は寝る前に読むのが好きです。", note: "好きな習慣や活動には -ing 形を使えます。" },
  { id: "g-035", level: "A1", term: "and / but / or", japanese: "単語や文をつなぐ", category: "文のつながり", label: "文法", pattern: "and: そして / but: しかし / or: または", example: "I want tea, but I don't want coffee.", exampleJapanese: "お茶は欲しいですが、コーヒーはいりません。", note: "but は対照、or は選択肢を示します。" },
  { id: "g-036", level: "A2", term: "will", japanese: "未来の予測・その場の決定を表す", category: "時制", label: "文法", pattern: "will + 動詞の原形", example: "I'll call you later.", exampleJapanese: "あとで電話します。", note: "will の短縮形は I'll, you'll, we'll などです。" },
  { id: "g-037", level: "A2", term: "副詞の形", japanese: "動作のしかたを表す", category: "副詞", label: "文法", pattern: "形容詞 + -ly", example: "Please speak slowly.", exampleJapanese: "ゆっくり話してください。", note: "多くの副詞は -ly を付けますが、fast のように形容詞と同じ形の語もあります。" },
  { id: "g-038", level: "A2", term: "too / enough", japanese: "度が過ぎること、十分であることを表す", category: "比較", label: "文法", pattern: "too + 形容詞 / 形容詞 + enough", example: "This bag is too heavy to carry.", exampleJapanese: "このバッグは重すぎて運べません。", note: "too は問題になるほど過度、enough は十分な量・程度を表します。" },
  { id: "g-039", level: "A2", term: "現在完了 ever / never", japanese: "経験を尋ねる、経験がないことを表す", category: "時制", label: "文法", pattern: "Have you ever + 過去分詞? / have never + 過去分詞", example: "Have you ever tried Indonesian food?", exampleJapanese: "インドネシア料理を食べたことがありますか。", note: "ever / never は完了した過去の時点とは通常一緒に使いません。" },
  { id: "g-040", level: "A2", term: "動詞 + to / -ing", japanese: "後ろに来る動詞の形を使い分ける", category: "動詞の形", label: "文法", pattern: "want to do / enjoy doing", example: "I enjoy learning new things.", exampleJapanese: "私は新しいことを学ぶのを楽しみます。", note: "動詞ごとに続ける形が決まるので、まとまりで覚えます。" },
  { id: "g-041", level: "B1", term: "間接話法", japanese: "他人の発言を伝える", category: "文のつながり", label: "文法", pattern: "said (that) + 文", example: "She said that she was tired.", exampleJapanese: "彼女は疲れていると言いました。", note: "伝える時点が過去なら、時制が一つ過去へ移ることが多いです。" },
  { id: "g-042", level: "B1", term: "although / despite", japanese: "対照的な二つの内容をつなぐ", category: "文のつながり", label: "文法", pattern: "although + 文 / despite + 名詞・-ing", example: "Although it was raining, we went out.", exampleJapanese: "雨が降っていましたが、私たちは出かけました。", note: "although の後ろは文、despite の後ろは名詞か -ing 形です。" },
  { id: "g-043", level: "B1", term: "wish", japanese: "現在と異なる願いを表す", category: "文のつながり", label: "文法", pattern: "wish + 過去形", example: "I wish I had more time.", exampleJapanese: "もっと時間があればいいのに。", note: "現在の事実と異なる願いには wish の後ろで過去形を使います。" },
  { id: "g-044", level: "B1", term: "動詞と前置詞", japanese: "動詞の後に決まった前置詞を置く", category: "前置詞", label: "文法", pattern: "agree with / rely on / respond to", example: "I agree with your idea.", exampleJapanese: "私はあなたの考えに賛成です。", note: "動詞と前置詞は組み合わせとして覚えるのが大切です。" },
  { id: "g-045", level: "B1", term: "make / let + 人 + 動詞", japanese: "人に〜させる、〜するのを許す", category: "動詞の形", label: "文法", pattern: "make / let + 人 + 動詞の原形", example: "The teacher let us use a dictionary.", exampleJapanese: "先生は私たちに辞書を使わせてくれました。", note: "make と let の後ろは to を付けず、動詞の原形を置きます。" }
];

export const MORE_INDONESIAN_TRANSLATIONS: Record<string, string> = {
  "w-091": "belajar; mempelajari", "w-092": "berbicara", "w-093": "membaca", "w-094": "menulis", "w-095": "mendengarkan", "w-096": "menonton; melihat", "w-097": "membeli", "w-098": "membayar", "w-099": "membuka; terbuka", "w-100": "menutup", "w-101": "memulai; mulai", "w-102": "menyelesaikan; selesai", "w-103": "sibuk", "w-104": "bebas; kosong; gratis", "w-105": "mudah", "w-106": "panas", "w-107": "dingin; pilek", "w-108": "kiri; tersisa", "w-109": "kanan; benar", "w-110": "berikutnya; selanjutnya",
  "w-111": "memesan; pesanan", "w-112": "memesan; mencadangkan", "w-113": "membatalkan", "w-114": "memeriksa", "w-115": "mengantar; mengirim", "w-116": "mengatur; mengorganisasi", "w-117": "lebih memilih", "w-118": "mempersiapkan", "w-119": "memperbaiki", "w-120": "meminta; permintaan", "w-121": "berbagi", "w-122": "menghabiskan", "w-123": "mendukung; dukungan", "w-124": "berguna", "w-125": "tenang", "w-126": "aman", "w-127": "di sekitar; kira-kira", "w-128": "melalui", "w-129": "mungkin", "w-130": "pelanggan",
  "w-131": "melamar; mengajukan", "w-132": "menghadiri", "w-133": "berkontribusi", "w-134": "menurun; mengurangi", "w-135": "mendorong; menyemangati", "w-136": "mengharapkan", "w-137": "menangani", "w-138": "mengidentifikasi", "w-139": "meningkat; meningkatkan", "w-140": "memengaruhi", "w-141": "mempertahankan", "w-142": "menyebutkan", "w-143": "menyadari; pemberitahuan", "w-144": "melakukan; tampil", "w-145": "menyediakan", "w-146": "menanggapi", "w-147": "jadwal; menjadwalkan", "w-148": "sumber", "w-149": "tugas", "w-150": "pendekatan; cara",
  "p-031": "Siapa nama Anda?", "p-032": "Saya tidak tahu.", "p-033": "Tolong katakan itu lagi.", "p-034": "Bagaimana Anda mengeja ...?", "p-035": "Apa yang Anda inginkan?", "p-036": "Bisakah Anda menunjukkan ... kepada saya?", "p-037": "Saya lebih suka ... .", "p-038": "Apakah Anda memiliki ...?", "p-039": "Mengapa kita tidak ...?", "p-040": "Saya akan mengambilnya.", "p-041": "Apakah Anda keberatan jika ...?", "p-042": "Saya menghargainya.", "p-043": "Itu masuk akal.", "p-044": "Saya menantikan ... .", "p-045": "Bisakah Anda memberi tahu saya ...?",
  "g-031": "menyatakan kemampuan, ketidakmampuan, atau izin", "g-032": "menyatakan lebih dari satu kata benda", "g-033": "menunjuk benda yang dekat atau jauh", "g-034": "menyatakan kegiatan yang disukai", "g-035": "menghubungkan kata atau kalimat", "g-036": "menyatakan prediksi atau keputusan masa depan", "g-037": "menyatakan cara melakukan tindakan", "g-038": "menyatakan berlebihan atau cukup", "g-039": "menanyakan atau menyatakan pengalaman", "g-040": "memilih bentuk kata kerja setelah kata kerja lain", "g-041": "menyampaikan ucapan orang lain", "g-042": "menghubungkan dua gagasan yang berlawanan", "g-043": "menyatakan harapan yang berbeda dari kenyataan", "g-044": "menggunakan kata depan yang tetap setelah kata kerja", "g-045": "membuat atau mengizinkan seseorang melakukan sesuatu"
};

export const MORE_SECOND_WORD_EXAMPLES: Record<string, ExpandedExamplePair> = {
  "w-091": { english: "We are learning English at school.", japanese: "私たちは学校で英語を学んでいます。" },
  "w-092": { english: "She speaks English and Indonesian.", japanese: "彼女は英語とインドネシア語を話します。" },
  "w-093": { english: "Please read this message.", japanese: "このメッセージを読んでください。" },
  "w-094": { english: "He writes emails in English.", japanese: "彼は英語でメールを書きます。" },
  "w-095": { english: "I like listening to music.", japanese: "私は音楽を聴くのが好きです。" },
  "w-096": { english: "Watch out! The floor is wet.", japanese: "気をつけて。床が濡れています。" },
  "w-097": { english: "She bought a new phone yesterday.", japanese: "彼女は昨日新しい電話を買いました。" },
  "w-098": { english: "We paid for dinner.", japanese: "私たちは夕食代を支払いました。" },
  "w-099": { english: "The store opens at ten.", japanese: "その店は10時に開きます。" },
  "w-100": { english: "The bank closes at five.", japanese: "銀行は5時に閉まります。" },
  "w-101": { english: "Let's start with an easy question.", japanese: "簡単な質問から始めましょう。" },
  "w-102": { english: "Have you finished your homework?", japanese: "宿題は終わりましたか。" },
  "w-103": { english: "The cafe is busy at lunch time.", japanese: "そのカフェは昼食時に混みます。" },
  "w-104": { english: "This app is free to use.", japanese: "このアプリは無料で使えます。" },
  "w-105": { english: "It is easy to make a mistake.", japanese: "間違いをするのは簡単です。" },
  "w-106": { english: "It is very hot today.", japanese: "今日はとても暑いです。" },
  "w-107": { english: "I have a cold today.", japanese: "私は今日風邪をひいています。" },
  "w-108": { english: "There is some food left.", japanese: "食べ物が少し残っています。" },
  "w-109": { english: "Your answer is right.", japanese: "あなたの答えは正しいです。" },
  "w-110": { english: "What should we do next?", japanese: "次に何をすべきですか。" },
  "w-111": { english: "Your order will arrive soon.", japanese: "ご注文はまもなく届きます。" },
  "w-112": { english: "We reserved seats online.", japanese: "私たちはオンラインで座席を予約しました。" },
  "w-113": { english: "The flight was canceled because of the storm.", japanese: "嵐のため飛行機は欠航になりました。" },
  "w-114": { english: "I checked my email this morning.", japanese: "私は今朝メールを確認しました。" },
  "w-115": { english: "The package was delivered yesterday.", japanese: "荷物は昨日配達されました。" },
  "w-116": { english: "She organized a small event.", japanese: "彼女は小さなイベントを企画しました。" },
  "w-117": { english: "Do you prefer to sit inside or outside?", japanese: "中と外のどちらに座りたいですか。" },
  "w-118": { english: "She prepared dinner for her family.", japanese: "彼女は家族のために夕食を用意しました。" },
  "w-119": { english: "The mechanic repaired my bike.", japanese: "整備士が私の自転車を修理しました。" },
  "w-120": { english: "They requested a meeting.", japanese: "彼らは会議を依頼しました。" },
  "w-121": { english: "We shared a taxi home.", japanese: "私たちはタクシーを相乗りして帰りました。" },
  "w-122": { english: "How much did you spend on the ticket?", japanese: "チケットにいくら使いましたか。" },
  "w-123": { english: "Thank you for your support.", japanese: "支援してくれてありがとうございます。" },
  "w-124": { english: "The teacher gave us useful advice.", japanese: "先生は私たちに役立つ助言をくれました。" },
  "w-125": { english: "It's quiet here in the morning.", japanese: "ここは朝は静かです。" },
  "w-126": { english: "Keep your passport in a safe place.", japanese: "パスポートは安全な場所に保管してください。" },
  "w-127": { english: "It takes around twenty minutes.", japanese: "だいたい20分かかります。" },
  "w-128": { english: "I learned about it through a friend.", japanese: "私は友人を通じてそれについて知りました。" },
  "w-129": { english: "Please reply as soon as possible.", japanese: "できるだけ早く返信してください。" },
  "w-130": { english: "The customer was very friendly.", japanese: "そのお客様はとても親しみやすい人でした。" },
  "w-131": { english: "You can apply online.", japanese: "オンラインで申し込めます。" },
  "w-132": { english: "More than fifty people attended the event.", japanese: "50人以上がそのイベントに出席しました。" },
  "w-133": { english: "He contributed an article to the magazine.", japanese: "彼はその雑誌に記事を寄稿しました。" },
  "w-134": { english: "We need to decrease our costs.", japanese: "私たちは費用を減らす必要があります。" },
  "w-135": { english: "This program encourages people to recycle.", japanese: "このプログラムは人々にリサイクルを促します。" },
  "w-136": { english: "What do you expect from this course?", japanese: "このコースに何を期待していますか。" },
  "w-137": { english: "Please handle this glass carefully.", japanese: "このグラスは慎重に扱ってください。" },
  "w-138": { english: "The police identified the owner.", japanese: "警察は所有者を特定しました。" },
  "w-139": { english: "We need to increase sales.", japanese: "私たちは売上を増やす必要があります。" },
  "w-140": { english: "His parents influenced his choice.", japanese: "彼の両親は彼の選択に影響を与えました。" },
  "w-141": { english: "The team maintained a high standard.", japanese: "チームは高い水準を維持しました。" },
  "w-142": { english: "Don't forget to mention the deadline.", japanese: "締め切りに触れるのを忘れないでください。" },
  "w-143": { english: "Did you notice the new sign?", japanese: "新しい看板に気づきましたか。" },
  "w-144": { english: "The doctor performed the operation.", japanese: "医師は手術を行いました。" },
  "w-145": { english: "Please provide your contact details.", japanese: "連絡先の詳細を提供してください。" },
  "w-146": { english: "How should we respond to this complaint?", japanese: "この苦情にどう対応すべきですか。" },
  "w-147": { english: "We need to schedule a call.", japanese: "電話の予定を組む必要があります。" },
  "w-148": { english: "The article uses reliable sources.", japanese: "その記事は信頼できる情報源を使っています。" },
  "w-149": { english: "This task takes about an hour.", japanese: "この作業には約1時間かかります。" },
  "w-150": { english: "Her approach to learning is practical.", japanese: "彼女の学び方は実践的です。" }
};
