import type { ExpandedExamplePair } from "./expanded-study-data";

export const NON_WORD_SECOND_EXAMPLES: Record<string, ExpandedExamplePair> = {
  "p-001": { english: "Nice to meet you, Ms. Sato.", japanese: "佐藤さん、はじめまして。" },
  "p-002": { english: "How are you today? - I'm great, thanks.", japanese: "今日は元気ですか。- とても元気です、ありがとう。" },
  "p-003": { english: "Could you help me find this address?", japanese: "この住所を探すのを手伝っていただけますか。" },
  "p-004": { english: "I don't understand this question.", japanese: "この質問がわかりません。" },
  "p-005": { english: "How much is this ticket?", japanese: "このチケットはいくらですか。" },
  "p-006": { english: "I'd like to speak to the manager.", japanese: "責任者の方とお話ししたいのですが。" },
  "p-007": { english: "What do you mean by 'available'?", japanese: "available はどういう意味ですか。" },
  "p-008": { english: "Your idea sounds great.", japanese: "あなたのアイデアはとても良さそうです。" },
  "p-009": { english: "Would you mind closing the door?", japanese: "ドアを閉めていただけますか。" },
  "p-010": { english: "In my opinion, practice is important.", japanese: "私の意見では、練習は大切です。" },
  "p-011": { english: "Where is the restroom?", japanese: "お手洗いはどこですか。" },
  "p-012": { english: "Can I have two tickets, please?", japanese: "チケットを2枚いただけますか。" },
  "p-013": { english: "I'm sorry. I made a mistake.", japanese: "すみません。間違えました。" },
  "p-014": { english: "I have to go now. See you later.", japanese: "もう行かなければなりません。またあとで。" },
  "p-015": { english: "I like coffee without sugar.", japanese: "私は砂糖なしのコーヒーが好きです。" },
  "p-016": { english: "How long does the movie last?", japanese: "映画はどのくらい続きますか。" },
  "p-017": { english: "Could I try these shoes on?", japanese: "この靴を試着してもいいですか。" },
  "p-018": { english: "I'm looking for a quiet cafe.", japanese: "静かなカフェを探しています。" },
  "p-019": { english: "What happened to your phone?", japanese: "あなたの電話に何があったのですか。" },
  "p-020": { english: "I'm not sure about the answer.", japanese: "その答えには確信がありません。" },
  "p-021": { english: "It depends on the weather.", japanese: "天気によります。" },
  "p-022": { english: "Would you like to sit by the window?", japanese: "窓際に座りませんか。" },
  "p-023": { english: "Could you tell me how much it costs?", japanese: "いくらかかるか教えていただけますか。" },
  "p-024": { english: "I agree with you completely.", japanese: "私はあなたに完全に賛成です。" },
  "p-025": { english: "I'm afraid that I need to leave now.", japanese: "残念ですが、もう行かなければなりません。" },
  "p-026": { english: "The reason is that the train was late.", japanese: "理由は電車が遅れたからです。" },
  "p-027": { english: "As far as I know, the store opens at ten.", japanese: "私の知る限り、その店は10時に開きます。" },
  "p-028": { english: "I'd recommend this book to beginners.", japanese: "私はこの本を初心者におすすめします。" },
  "p-029": { english: "Would it be possible to pay by card?", japanese: "カードで支払うことは可能でしょうか。" },
  "p-030": { english: "I was wondering if the room is available.", japanese: "部屋が空いているかと思っていたのですが。" },
  "p-031": { english: "What's your name? - I'm Rina.", japanese: "お名前は何ですか。- リナです。" },
  "p-032": { english: "I don't know where he lives.", japanese: "彼がどこに住んでいるのか知りません。" },
  "p-033": { english: "Please say that again more slowly.", japanese: "もう一度、もっとゆっくり言ってください。" },
  "p-034": { english: "How do you spell your last name?", japanese: "あなたの名字はどうつづりますか。" },
  "p-035": { english: "What would you like to eat?", japanese: "何を食べたいですか。" },
  "p-036": { english: "Can you show me your ID?", japanese: "身分証明書を見せてもらえますか。" },
  "p-037": { english: "I'd rather walk than wait for a bus.", japanese: "バスを待つより歩きたいです。" },
  "p-038": { english: "Do you have any vegetarian dishes?", japanese: "ベジタリアン向けの料理はありますか。" },
  "p-039": { english: "Why don't we take a short break?", japanese: "少し休憩しませんか。" },
  "p-040": { english: "This one fits well. I'll take it.", japanese: "これはよく合います。これにします。" },
  "p-041": { english: "Would you mind if I used your phone?", japanese: "あなたの電話を使ったら気になりますか。" },
  "p-042": { english: "I appreciate it when you explain things clearly.", japanese: "物事をわかりやすく説明してくださることに感謝しています。" },
  "p-043": { english: "The shop is closed today. - That makes sense; it's a holiday.", japanese: "今日は店が閉まっています。- なるほど、祝日ですからね。" },
  "p-044": { english: "I'm looking forward to the weekend.", japanese: "週末を楽しみにしています。" },
  "p-045": { english: "Could you let me know the price?", japanese: "料金を知らせていただけますか。" },
  "p-046": { english: "Can I use your pen?", japanese: "あなたのペンを使ってもいいですか。" },
  "p-047": { english: "Here you are. Your coffee is ready.", japanese: "どうぞ。コーヒーの準備ができました。" },
  "p-048": { english: "I'm sorry. Could you repeat that?", japanese: "すみません。もう一度言っていただけますか。" },
  "p-049": { english: "What time is lunch?", japanese: "昼食は何時ですか。" },
  "p-050": { english: "See you tomorrow at school.", japanese: "また明日、学校で会いましょう。" },
  "p-051": { english: "Could I have some more water?", japanese: "お水をもう少しいただけますか。" },
  "p-052": { english: "I'm afraid the bus has already left.", japanese: "残念ですが、バスはすでに出発しました。" },
  "p-053": { english: "How about a walk after dinner?", japanese: "夕食後に散歩はいかがですか。" },
  "p-054": { english: "I forgot my bag. - It doesn't matter.", japanese: "バッグを忘れました。- 気にしなくて大丈夫です。" },
  "p-055": { english: "I'll be back in an hour.", japanese: "1時間後に戻ります。" },
  "p-056": { english: "Would it be possible to send it today?", japanese: "今日それを送ることは可能でしょうか。" },
  "p-057": { english: "I'm not used to cold weather.", japanese: "私は寒い天気に慣れていません。" },
  "p-058": { english: "As far as I'm concerned, we should wait.", japanese: "私としては、待ったほうがよいと思います。" },
  "p-059": { english: "The point is that everyone needs to agree.", japanese: "大事な点は、全員が同意する必要があることです。" },
  "p-060": { english: "I didn't mean to interrupt you.", japanese: "あなたの話をさえぎるつもりではありませんでした。" },

  "g-001": { english: "They are not at home.", japanese: "彼らは家にいません。" },
  "g-002": { english: "My brother plays tennis on Sundays.", japanese: "私の兄は日曜日にテニスをします。" },
  "g-003": { english: "Can she drive?", japanese: "彼女は運転できますか。" },
  "g-004": { english: "Did you see him yesterday?", japanese: "あなたは昨日彼に会いましたか。" },
  "g-005": { english: "My phone is more expensive than yours.", japanese: "私の電話はあなたのより高価です。" },
  "g-006": { english: "I'm writing an email now.", japanese: "私は今メールを書いています。" },
  "g-007": { english: "She has already finished the report.", japanese: "彼女はすでに報告書を終えています。" },
  "g-008": { english: "We need a place to stay.", japanese: "私たちには泊まる場所が必要です。" },
  "g-009": { english: "The book that you gave me is useful.", japanese: "あなたが私にくれた本は役に立ちます。" },
  "g-010": { english: "She bought an umbrella because it was raining.", japanese: "雨が降っていたので、彼女は傘を買いました。" },
  "g-011": { english: "There is a bus stop near here.", japanese: "この近くにバス停があります。" },
  "g-012": { english: "Their house is near the station.", japanese: "彼らの家は駅の近くにあります。" },
  "g-013": { english: "Don't forget your keys.", japanese: "鍵を忘れないでください。" },
  "g-014": { english: "Why does he study English?", japanese: "なぜ彼は英語を勉強するのですか。" },
  "g-015": { english: "They don't work on Sundays.", japanese: "彼らは日曜日には働きません。" },
  "g-016": { english: "We have two cats.", japanese: "私たちは猫を2匹飼っています。" },
  "g-017": { english: "Would you like some tea?", japanese: "お茶はいかがですか。" },
  "g-018": { english: "There aren't many shops near here.", japanese: "この近くには店があまりありません。" },
  "g-019": { english: "We met at the station.", japanese: "私たちは駅で会いました。" },
  "g-020": { english: "My birthday is in July.", japanese: "私の誕生日は7月です。" },
  "g-021": { english: "Look at those clouds. It's going to rain.", japanese: "あの雲を見てください。雨が降りそうです。" },
  "g-022": { english: "They were watching a movie at eight.", japanese: "彼らは8時に映画を見ていました。" },
  "g-023": { english: "This is the best restaurant in town.", japanese: "これは町で一番良いレストランです。" },
  "g-024": { english: "You have to wear a seat belt.", japanese: "シートベルトを着用しなければなりません。" },
  "g-025": { english: "The meeting is held every Monday.", japanese: "会議は毎週月曜日に行われます。" },
  "g-026": { english: "I lost my keys yesterday.", japanese: "私は昨日鍵をなくしました。" },
  "g-027": { english: "If you finish early, call me.", japanese: "早く終わったら、私に電話してください。" },
  "g-028": { english: "If I were you, I'd take the train.", japanese: "私があなたなら、電車に乗ります。" },
  "g-029": { english: "Do you know what time it starts?", japanese: "それが何時に始まるか知っていますか。" },
  "g-030": { english: "He used to play the guitar.", japanese: "彼は以前ギターを弾いていました。" },
  "g-031": { english: "She can't come today.", japanese: "彼女は今日来られません。" },
  "g-032": { english: "My feet are cold.", japanese: "私の足は冷たいです。" },
  "g-033": { english: "That book is interesting, but those books are boring.", japanese: "あの本は面白いですが、それらの本は退屈です。" },
  "g-034": { english: "He likes playing football.", japanese: "彼はサッカーをするのが好きです。" },
  "g-035": { english: "Would you like tea or coffee?", japanese: "お茶とコーヒーのどちらがいいですか。" },
  "g-036": { english: "I think it will rain tomorrow.", japanese: "明日は雨が降ると思います。" },
  "g-037": { english: "She answered the question correctly.", japanese: "彼女はその質問に正しく答えました。" },
  "g-038": { english: "The soup isn't warm enough.", japanese: "そのスープは十分に温かくありません。" },
  "g-039": { english: "I've never been to Singapore.", japanese: "私はシンガポールに行ったことがありません。" },
  "g-040": { english: "We decided to leave early.", japanese: "私たちは早く出発することに決めました。" },
  "g-041": { english: "He told me that he was busy.", japanese: "彼は私に忙しいと言いました。" },
  "g-042": { english: "Despite the rain, we had a good time.", japanese: "雨にもかかわらず、私たちは楽しい時間を過ごしました。" },
  "g-043": { english: "I wish I knew the answer.", japanese: "答えを知っていればいいのに。" },
  "g-044": { english: "She relies on her calendar.", japanese: "彼女は予定表を頼りにしています。" },
  "g-045": { english: "The joke made everyone laugh.", japanese: "その冗談はみんなを笑わせました。" },
  "g-046": { english: "The teacher gave us homework.", japanese: "先生は私たちに宿題を出しました。" },
  "g-047": { english: "Those are my parents' bags.", japanese: "あれらは私の両親のバッグです。" },
  "g-048": { english: "She's in the kitchen.", japanese: "彼女は台所にいます。" },
  "g-049": { english: "The keys are under the chair.", japanese: "鍵は椅子の下にあります。" },
  "g-050": { english: "Let's not be late.", japanese: "遅れないようにしましょう。" },
  "g-051": { english: "We're flying to Jakarta next week.", japanese: "私たちは来週ジャカルタへ飛行機で行く予定です。" },
  "g-052": { english: "My car isn't as fast as yours.", japanese: "私の車はあなたの車ほど速くありません。" },
  "g-053": { english: "Have you finished your homework yet?", japanese: "もう宿題を終えましたか。" },
  "g-054": { english: "There is too much sugar in this drink.", japanese: "この飲み物には砂糖が多すぎます。" },
  "g-055": { english: "She studies hard to pass the exam.", japanese: "彼女は試験に合格するために一生懸命勉強しています。" },
  "g-056": { english: "He stopped smoking last year.", japanese: "彼は昨年たばこをやめました。" },
  "g-057": { english: "It was such a useful lesson that I took notes.", japanese: "とても役立つ授業だったので、私はメモを取りました。" },
  "g-058": { english: "The road was closed; therefore, we took a different route.", japanese: "道路が閉鎖されていたため、私たちは別の道を通りました。" },
  "g-059": { english: "The instructions were confusing, so I was confused.", japanese: "説明がわかりにくかったので、私は混乱しました。" },
  "g-060": { english: "Thank you for helping me.", japanese: "手伝ってくれてありがとうございます。" }
};
